### ISSUE TITLE
Variable Build.Repository.LocalPath changed

### ISSUE THREAD

**Issue by itsme112358** [microsoft/azure-pipelines-agent#3295] opened 2021-03-02 16:14 UTC
## Agent Version and Platform
2.181.0 (OK) vs. 2.182.1 (Not OK?) / Windows / self hosted

## Azure DevOps Type and Version
https://dev.azure.com/AareonRELionGmbH

## What's not working?
Behavior of Variable Build.Repository.LocalPath changed
We have two Repos:
1. Our "App"
Automatically checks out to `../_work/2/s/App`
2. Our Build Repo (all the Scripts and stuff to handle the build process
Automatically checks out to  `../_work/2/s/BuildRepo`

One of our first steps is to read some settings from a json file within the **App** Repo:
```powershell
$settings = (Get-Content (Join-Path $ENV:BUILD_REPOSITORY_LOCALPATH "AzurePipeLine\settings.json") | ConvertFrom-Json)
```

This worked until today, when we updated our agents from 2.181.0 to 2.182.1
Before the Variable resolved to `../_work/2/s/App`
Now the Variable is resolved as `../_work/2/s`

This effectively breaks all our Pipelines!
Of course I can change our scripts, but I want to know whether this is by design or by accident. Otherwise I'll have to change it back on the next update...

**Comment by itsme112358** [comment] 2021-03-02 16:23
If this is not by design: How do I "downdate" our agents without having to reregister them all?
Just stop the services, and overwrite the folder and all its content?

**Comment by itsme112358** [comment] 2021-03-02 17:07
I updated all our scripts so it works now, please document these changes in future. I reviewed the [release notes](https://github.com/microsoft/azure-pipelines-agent/releases/) and found #3249 but we're not setting the variable anywhere, only reading so it shouldn't affect our builds - am I wrong here?

**Comment by BBI-JamesFairweather** [comment] 2021-03-02 17:16
Could it have been #3237 that caused this change for you?

**Comment by mjroghelia** [comment] 2021-03-02 22:35
@EzzhevNikita @anatolybolshakov Please investigate this as a high priority. It sounds related to #3237. We don't want to break compatibility with any of the existing variables, so this would be a regression that should be hot fixed. Could it be related to the order in which the checkouts are performed?

**Comment by itsme112358** [comment] 2021-03-03 00:46
> Could it have been #3237 that caused this change for you?

Sounds closer than 3249, yes. 
This is our yaml file cropped by some lines so everything fits in the screenshot. 
This is the order in which we check out:
![Screenshot_20210303-013830_Chrome](https://user-images.githubusercontent.com/16080908/109734765-dbb66380-7bc1-11eb-9820-0d46e0fa31a6.jpg)

**Comment by EzzhevNikita** [comment] 2021-03-03 11:01
@itsme112358 We found the root cause of the issue, and it is not expected behavior that the value of Build.Repository.LocalPath was changed. We are planning to provide a hotfix to resolve it.

**Comment by mjroghelia** [comment] 2021-03-03 19:58
@itsme112358 Thanks for the report. Be aware before upgrading that the forthcoming 2.183.1 agent release will restore the previous behavior.

**Comment by itsme112358** [comment] 2021-03-08 10:36
Thanks for the update! :)

**Comment by EzzhevNikita** [comment] 2021-03-09 05:57
@itsme112358 Agent 2.183.1 with reverting of the changes that caused the issue have been released. I'm currently closing this issue.

**Closed by EzzhevNikita** 2021-03-09 05:57 UTC
Labels: Area: ABTT, Area: Agent, bug
