### ISSUE TITLE
Update bundled git-lfs version

### ISSUE THREAD

**Issue by michha** [microsoft/azure-pipelines-agent#4123] opened 2023-01-20 08:17 UTC
The currently bundled git-lfs version ist 2.13.3, which was released in March 2021.
It would be nice if a more current version would be bundled, because 3.x releases brought some nice improvements with them.

https://github.com/git-lfs/git-lfs/blob/main/CHANGELOG.md

**Comment by ivanduplenskikh** [comment] 2023-01-20 10:42
Hi @michha thanks for reporting! We are working on more prioritized issues at the moment, but will get back to this one soon.

**Comment by MoritzGSchmid** [comment] 2023-02-13 05:34
Hi, unfortunately, the outdated git-lfs version causes this error during the checkout command of a pipeline:
```
git lfs install --local
Hook already exists: pre-push

	#!/bin/sh
	command -v git-lfs >/dev/null 2>&1 || { echo >&2 "\nThis repository is configured for Git LFS but 'git-lfs' was not found on your path. If you no longer wish to use Git LFS, remove this hook by deleting '.git/hooks/pre-push'.\n"; exit 2; }
	git lfs pre-push "$@"

To resolve this, either:
  1: run `git lfs update --manual` for instructions on how to merge hooks.
  2: run `git lfs update --force` to overwrite your hook.
##[error]Git-lfs installation failed with exit code: 2
```

According to https://developercommunity.visualstudio.com/t/using-git-lfs-checkout-results-in-error-git-lfs-in/845516, the solution is to update the git-lfs version. Could you please give this a higher priority or let us know how to do this ourselves?
That would be awesome, Thanks

**Comment by ma0ho** [comment] 2023-02-14 11:39
I can confirm that having the old version turns out to become troublesome. So I'd opt for a higher priority as well!

**Comment by utzms** [comment] 2023-02-20 07:39
The aforementioned issue of the old version (by @MoritzGSchmid) is very obstructive and an update would be very much appreciated! Could you please give this a higher priority?

**Comment by dstewart-minitab** [comment] 2023-03-04 03:39
I agree, this should be a higher priority since this intermittently breaks the git lfs hooks on checkout.  As a workaround, we've set the System.PreferGitFromPath=true pipeline variable which forces it to use the locally installed git.

**Comment by xenon8** [comment] 2023-04-14 13:15
If anyone else is hitting this issue (where they have Git LFS v3.1.4 or later installed on their agent server), then you can solve it by using this System variable on the Pipeline. I was able to add the setting without updating our pipeline yaml by using the trigger options in the pipeline settings:

System.PreferGitFromPath=true

hopefully the new version of the agent will be out soon and we can use this.

**Comment by ismayilov-ismayil** [comment] 2023-08-31 15:09
Agent with git-lfs v3.3.0 was deployed, so closing this one. Feel free to re-open or create new ticket if you have related issue.

**Closed by ismayilov-ismayil** 2023-08-31 15:09 UTC
Labels: enhancement, Area: Agent
