### ISSUE TITLE
Azure DevOps on prem build missing capabilities after Visual studio upgrade.

### ISSUE THREAD

**Issue by kcherewyk** [microsoft/azure-pipelines-agent#3444] opened 2021-06-18 22:02 UTC
Hello,

We recently upgraded Visual studio from 16.8.4.0 to 16.10.2.0 on our self-hosted Windows build agent using Puppet to keep our agents' capabilities in sync. We have noticed that after upgrading the Visual Studio version that our agent is missing some of the capabilities that it previously had, specifically :
- SqlPackage
- VisualStudio
- VisualStudio_16.0
- VisualStudio_IDE
- VisualStudio_IDE_16.0
- MSBuild_16.0
- MSBuild_16.0_x64
- VSTest
- VSTest_16.0

We have tried restarting the agent service and the server with no success. We have also tried upgrading the build agent through the Azure DevOps portal. But it would seem our agents are at the most recent version of 2.188.1.

Please advise, 
Thank you for your time.

Agent with the orginal version of Visual studio (16.8.4.0)  : 
![image](https://user-images.githubusercontent.com/60932303/122619211-86f60600-d055-11eb-9001-a05ed4003de4.png) ![image](https://user-images.githubusercontent.com/60932303/122619089-3e3e4d00-d055-11eb-8abc-50e6969bed98.png) 

Agent with the upgraded version of Visual Studio (16.10.2.0): 
![image](https://user-images.githubusercontent.com/60932303/122619317-ca507480-d055-11eb-8a3d-074478fc8e58.png) ![image](https://user-images.githubusercontent.com/60932303/122619337-d89e9080-d055-11eb-83b1-36c7e34cfaa1.png)

**Comment by DaniilShmelev** [comment] 2021-06-23 15:53
Hey @kcherewyk! I wasn't able to reproduce the issue using agent 2.188.1 and Visual Studio 16.10.2.
Did you try reconfiguring the agent?
Also, could you please run `*path to agent 2.188.2*\externals\vswhere.exe -version 16 -format json` and share the output?

**Comment by kcherewyk** [comment] 2021-06-23 21:58
No I haven't tried to reconfigure the agent yet but this is the JSON output that was generated. 

> [
  {
    "instanceId": "b7cb1478",
    "installDate": "2020-06-12T19:48:16Z",
    "installationName": "VisualStudio/16.10.2+31410.357",
    "installationPath": "C:\\Program Files (x86)\\Microsoft Visual Studio\\2019\\Enterprise",
    "installationVersion": "16.10.31410.357",
    "productId": "Microsoft.VisualStudio.Product.Enterprise",
    "productPath": "C:\\Program Files (x86)\\Microsoft Visual Studio\\2019\\Enterprise\\Common7\\IDE\\devenv.exe",
    "state": 4294967295,
    "isComplete": true,
    "isLaunchable": true,
    "isPrerelease": false,
    "isRebootRequired": false,
    "displayName": "Visual Studio Enterprise 2019",
    "description": "Scalable, end-to-end solution for teams of any size",
    "channelId": "VisualStudio.16.Release",
    "channelUri": "https://aka.ms/vs/16/release/channel",
    "enginePath": "C:\\Program Files (x86)\\Microsoft Visual Studio\\Installer\\resources\\app\\ServiceHub\\Services\\Microsoft.VisualStudio.Setup.Service",
    "releaseNotes": "https://docs.microsoft.com/en-us/visualstudio/releases/2019/release-notes-v16.10#16.10.2",
    "thirdPartyNotices": "https://go.microsoft.com/fwlink/?LinkId=660909",
    "updateDate": "2021-06-18T18:07:36.6475947Z",
    "catalog": {
      "buildBranch": "d16.10",
      "buildVersion": "16.10.31410.357",
      "id": "VisualStudio/16.10.2+31410.357",
      "localBuild": "build-lab",
      "manifestName": "VisualStudio",
      "manifestType": "installer",
      "productDisplayVersion": "16.10.2",
      "productLine": "Dev16",
      "productLineVersion": "2019",
      "productMilestone": "RTW",
      "productMilestoneIsPreRelease": "False",
      "productName": "Visual Studio",
      "productPatchVersion": "2",
      "productPreReleaseMilestoneSuffix": "1.0",
      "productSemanticVersion": "16.10.2+31410.357",
      "requiredEngineVersion": "2.10.2174.31177"
    },
    "properties": {
      "campaignId": "",
      "channelManifestId": "VisualStudio.16.Release/16.10.2+31410.357",
      "nickname": "",
      "setupEngineFilePath": "C:\\Program Files (x86)\\Microsoft Visual Studio\\Installer\\vs_installershell.exe"
    }
  }
]

**Comment by deadlydog** [comment] 2021-06-28 00:15
Hey guys, I work with @kcherewyk and the issue seemed to resolve itself after a couple days. We updated Visual Studio our other on-prem build agents and they did not encounter the problem, so it seems to have been a fluke or a temporary thing. I believe this issue can be closed. Thanks for looking :)

**Comment by DaniilShmelev** [comment] 2021-07-02 08:15
We couldn't reproduce the issue on our side, and it seems to be resolved for @kcherewyk, so I'm closing this for now.
Feel free to ping me if the issue is still present for you

**Closed by DaniilShmelev** 2021-07-02 08:15 UTC
Labels: Area: Agent, bug
