### ISSUE TITLE
NuGet restore is very slow on self-hosted agent run as service

### ISSUE THREAD

**Issue by satano** [microsoft/azure-pipelines-agent#2356] opened 2019-07-22 14:45 UTC
## Agent Version and Platform
Current agent version: '2.154.3'
OS: Windows
Platform: x64

## Azure DevOps Type and Version
dev.azure.com, just build agent is self-hosted.
https://dev.azure.com/krossk/

## What's not working?
NuGet restore task is very slow. I have already tried [Developer Community](https://developercommunity.visualstudio.com/content/problem/632309/devops-build-pipeline-nuget-restore-very-slow-on-s.html). So the setup is this:

- We use latest `nuget.exe`, now it is the version 5.1.0.
- We use custom `nuget.config` where there are two nuget sources: standard _nuget.org_ and our own nuget server. Our nuget server is not private. It is public, so from the agent view, it is the same as nuget.org, just different URL.
- Solution has 7 projects.
- The total number of restored packages is 81. Only 4 of them are hosted on our own nuget server, the rest are packages from nuget.org.
- Total size of restored packages is around 830 MB.
- The build runs on our self-hosted machine/agent.
- Our build agent(s) run as a service.
- The machine is not bad: Intel Xeon, 64GB RAM, SSD disk. And this is our build machine - there is no other software running.

NuGet restore task always takes around **11 minutes** (usually between 10 and 13). And all the packages are in the local NuGet cache, they are not downloaded from the internet. I tried standard _NuGetCommand@2_ task and also simple script step running `nuget.exe` directly - this makes no difference.

At the Developer Community [we were suggested to try changing the mode the agent is running](https://developercommunity.visualstudio.com/comments/635033/view.html). And this is the thing. **When the agent is started manually (interactively), everything is OK.** NuGet restore takes 15 seconds when all the packages are in local cache, and around 40 seconds when the cache is empty and the packages are downloaded from the internet.

When the agent is started as a service again, package restore lasts 11 minutes again.

We do not experience this slowness with the other types of steps (build, publish artifacts...). All of them are fine, just nuget restore is not working as expected.

For testing purposes, there were no steps in the build pipeline, just NuGet restore.

## Agent and Worker's Diagnostic Logs
[Agent_20190719-140904-utc.log](https://github.com/microsoft/azure-pipelines-agent/files/3417872/Agent_20190719-140904-utc.log)
[Worker_20190722-140600-utc.log](https://github.com/microsoft/azure-pipelines-agent/files/3417873/Worker_20190722-140600-utc.log)

**Comment by juliobbv** [comment] 2019-08-05 20:22
@aasim, can you take a look at this issue?

Looks like the "NuGet Restore" task can take much longer to complete when the agent is configured to run as a service vs. when it's run interactively.

From the agent's point of view, once the agent is launched, it doesn't take any specific decisions on whether it's running as any of the modes. The only difference is that running an account as a service allows running as the agent as another account. Maybe doing so causes the authentication/authorization flow in NuGet to take a slower path?

**Comment by ltrzesniewski** [comment] 2020-02-12 23:58
I've noticed that NuGet restore is also very slow on Microsoft-hosted agents (also see #2134, which got dismissed). I guess the underlying issue is the same.

Anyway, here's some info I found out from a project of mine, in case it could be helpful:

 - [Caching the global packages cache](https://docs.microsoft.com/en-us/azure/devops/pipelines/caching/?view=azure-devops) does not seem to help, so the problem is apparently not tied to network speed. This is slow even though NuGet is not supposed to need network access.
 - I took a binary log of a restore through MSBuild (with all packages already cached), and here's what it shows:
   - Most time is spent in `RestoreTask`, and it is definitely the bottleneck
   - The `MsBuild` task which invokes the `_IsProjectRestoreSupported` target (in `_FilterRestoreGraphProjectInputItems`) also seems a bit too slow, but this may be an unrelated issue.
   - The logs of `RestoreTask` are similar to what I'm getting on my machine, and I couldn't spot any meaningful difference except for the concurrent job count. Unfortunately, MSBuildLogViewer doesn't show the timestamps of individual log lines and I don't know if this information is available in the binlog itself, but I can check that.

**Comment by MehdiSaeedifar** [comment] 2020-06-08 05:12
We have the same issue. It takes 5 minutes to restore packages. Any solution found?

**Comment by alexstdev** [comment] 2020-06-30 11:45
Hi there, we seem to have the same Problem, Nuget restore sitting around 5 minutes before the logs come in, the total task takes 9minutes...

**Comment by igor-teresco** [comment] 2020-07-03 07:57
Hi, what was taking 20-30 seconds before, now lasts for 10-15 mins - very disappointing... Please check and fix!

**Comment by Jetski5822** [comment] 2020-08-31 13:31
Same issue here - I just installed a fresh agent and NugetCommand is taking 11ish minute.

**Comment by weloytty** [comment] 2020-09-10 16:04
me too, I've been pulling my hair out -- 11 minutes to restore a ~65 project sln, that's been unchanged for over a year.  (Build is running under a service account as well)

**Comment by daviesro** [comment] 2020-09-11 09:14
4-5 minutes per nuget restore on our Azure build pipelines. 15 seconds on local machine.

**Comment by hoborm** [comment] 2020-10-05 12:06
I experience similar issues as described above, however I do not think that this can be necessarily linked to azure pipelines agent. I have a restore time around 2.5 minutes on a Jenkins node (run as a service) and 10-20 seconds on my local machine. (tried with -NoCache as well) My best guess would be to poke around the nuget.exe issues.

**Comment by ArtourK** [comment] 2020-10-27 07:13
We also experience this issue!
Some time 1 month back both Jenkins and TFS, nuget restore times went x10. 
For the Jenkins we run the service as a user, I just logged in as that user and restarted the server. 
After that the problem was solved! 

For TFS I have tried more or less everything I can think of! The times are not going down :/

**Comment by anatolybolshakov** [comment] 2021-01-19 16:12
Hi everyone, this seems to be a known issue with NuGet - please see [this link](https://docs.microsoft.com/en-us/nuget/reference/errors-and-warnings/nu3028#revocation-check-mode-481) for more details.
As @ArtourK mentioned - one of possible solution could be to set environment variable NUGET_CERT_REVOCATION_MODE = "offline" - it is not recommended under normal circumstances, but could help to resolve issue with longer execution time.
Let me close this at the moment since it doesn't seem to be related to agent - please feel free to ask any further questions.

**Closed by anatolybolshakov** 2021-01-19 16:12 UTC
Labels: bug, question

**Comment by dssagar93** [comment] 2021-04-29 11:57
What a disappointment, Restore Packages took 3 mins, Build solution took <50 seconds. Extremely slow.

**Comment by DerekFoulk** [comment] 2021-07-16 21:22
@anatolybolshakov Can you please share how to set this "environment variable" in Azure Pipelines? The documentation I found does not say anything about setting environment variables... https://docs.microsoft.com/en-us/azure/devops/pipelines/process/variables?view=azure-devops&tabs=yaml%2Cbatch#environment-variables

**Comment by janisBerz** [comment] 2022-02-03 12:39
For me, the restore took 3 minutes. Ended up switching from NuGet restore task (NuGetCommand@2) to DotNet restore task (DotNetCoreCLI@2). Now the restore takes only 16 seconds.

**Comment by robmen** [comment] 2022-02-03 12:44
I don't have the issue number (sorry 😢) but there was a long open issue in the NuGet repo pointing out that the NuGet restore was many orders slower when run in an Azure pipeline with the task agent registered as an NT service. People kept adding to the issue but the NuGet team eventually closed it saying they couldn't reproduce the problem. This root problem has probably been around for a long time.

**Comment by dobri-popov-tiebreak-solutions** [comment] 2023-10-16 15:22
We have the same issue - NuGet restore task is extremely slow.

```
2023-10-16T13:16:01.4641069Z [command]D:\NuGet\nuget.exe restore D:\AzureBuild\agent\_work\Solution1.sln -Verbosity Detailed -NonInteractive -ConfigFile D:\AzureBuild\agent\_work\nuget.config
2023-10-16T13:16:25.7774019Z NuGet Version: 6.5.0.154
2023-10-16T13:16:25.7776436Z MSBuild auto-detection: using msbuild version '17.5.1.16304' from 'C:\Program Files (x86)\Microsoft Visual Studio\2022\BuildTools\MSBuild\Current\bin'. Use option -MSBuildVersion to force nuget to use a specific version of MSBuild.
2023-10-16T13:16:25.7781152Z MSBuild P2P timeout [ms]: 408000
2023-10-16T13:16:25.7785147Z C:\Program Files (x86)\Microsoft Visual Studio\2022\BuildTools\MSBuild\Current\bin\msbuild.exe "C:\WINDOWS\TEMP\NuGetScratch\****.nugetinputs.targets" /t:GenerateRestoreGraphFile /nologo /nr:false /v:q /p:NuGetRestoreTargets="C:\WINDOWS\TEMP\NuGetScratch\****.nugetrestore.targets" /p:RestoreUseCustomAfterTargets="True" /p:DisableCheckingDuplicateNuGetItems="True" /p:RestoreTaskAssemblyFile="D:\NuGet\nuget.exe" /p:RestoreSolutionDirectory="D:\AzureBuild\agent\_work\" /p:RestoreConfigFile="D:\AzureBuild\agent\_work\nuget.config" /p:SolutionDir="D:\AzureBuild\agent\_work\" /p:SolutionName="Solution1"
....
2023-10-16T13:16:27.8906813Z     15 package(s) to D:\AzureBuild\agent\_work\Proj1.csproj
```

As you can see, there is almost 25 seconds delay after the **nuget** command is executed and only then we see the output. The real package restore takes around 2 seconds. When I execute the same command from the command line it executes immediately - this delay of 25 seconds does not exist.

Any idea what might be wrong? Each pipeline restores 10+ solutions and when there is a 30 seconds delay per each restore task, 5 minutes are lost for the machine doing nothing.

**Comment by ebuter9292** [comment] 2024-03-08 10:21
Why is disabling an important security feature considered an acceptable resolution to this problem?

**Comment by SG57** [comment] 2024-05-16 08:05
Struggled with this forever.  Only solution I discovered that wasn't waiting forever was to use MSBuild task and the deprecated Nuget restore configuration setting.

```
steps:
- task: MSBuild@1
  displayName: 'Restore Nuget Packages (deprecated but fast)'
  inputs:
    platform: '$(BuildPlatform)'
    configuration: '$(BuildConfiguration)'
    msbuildArguments: '-target:Restore /p:RestoreUseSkipNonexistentTargets="false"'
    restoreNugetPackages: true
```

**Comment by naradae** [comment] 2024-06-14 01:18
I've noticed the same issue where it seems the startup time for nuget.exe to get to the first log message (printing the nuget.exe version string) takes 30 seconds - 1.5 minutes. Once the package restoring begins, that goes quickly. Must be wasting huge amounts of capacity across the entire fleet of hosted agents

**Comment by CzBuCHi** [comment] 2024-06-25 07:57
same issue here - in my case i took ~15 seconds just to tell me this: (called `nuget -x`)
```cs
NuGet.Commands.CommandException: Unknown command: "-x"
   v NuGet.CommandLine.CommandManager.GetCommand(String commandName)
   v NuGet.CommandLine.CommandLineParser.ParseCommandLine(IEnumerable`1 commandLineArgs)
   v NuGet.CommandLine.Program.MainCore(String workingDirectory, String[] args)
```

**Comment by eggman211** [comment] 2025-03-26 19:15
I've been having this issue for a year or more.  I finally set NUGET_CERT_REVOCATION_MODE : 'offline' and 16 minutes is now 20 seconds.  I do not want to use this long term.  Has anyone figured out how to fix this without disabling cert checks?  I have tried so many things without any luck.
