### ISSUE TITLE
Cancelling builds has no effect on one of my pipelines

### ISSUE THREAD

**Issue by alecmocatta** [microsoft/azure-pipelines-agent#2402] opened 2019-08-23 06:21 UTC
## Agent Version and Platform
Version of your agent? **2.155.1**

OS of the machine running the agent? **OSX and Linux**

## Azure DevOps Type and Version
dev.azure.com (formerly visualstudio.com) ~~or on-premises TFS/Azure DevOps Server?~~

If dev.azure.com, what is your organization name? **https://dev.azure.com/alecmocatta**

## What's not working?
The "Cancel" button has no effect on one of my pipelines.

For example, I clicked "Cancel" for this build and it's still building: https://dev.azure.com/alecmocatta/constellation/_build/results?buildId=469

I clicked "Cancel" for this build, and it continued building for another 2 hours: https://dev.azure.com/alecmocatta/constellation/_build/results?buildId=464

## Agent and Worker's Diagnostic Logs
Do I get this with "Queue with diagnostics"? If so I'll update this issue with it shortly.

**Comment by alecmocatta** [comment] 2019-09-16 09:24
Cross-posted https://developercommunity.visualstudio.com/content/problem/735409/cancelling-a-build-doesnt-work.html

**Comment by jtpetty** [comment] 2020-01-27 17:13
closing since the referenced issue was root caused and closed

**Closed by jtpetty** 2020-01-27 17:13 UTC
