### ISSUE TITLE
Custom tasks and node versions

### ISSUE THREAD

**Issue by rossbeehler** [microsoft/azure-pipelines-agent#3195] opened 2020-12-21 19:31 UTC
I'm trying to run a custom task on node 12 or newer.  The azure-pipelines-task-lib repo claims that node14 is supported: https://github.com/microsoft/azure-pipelines-task-lib/blob/master/node/docs/nodeEnvironment.md.  However, in my usage of the self-hosted agent in docker (as explained in https://docs.microsoft.com/en-us/azure/devops/pipelines/agents/docker?view=azure-devops), only node versions 6 and 10 are available if you look in the underlying setup in /azp/agent/externals.  I checked this is true for all flavors of the self-hosted agent.

I thought the way to pull this off was to use the "Node.js Tool Installer task" (NodeTool@0), but this does not seem to have an effect on the execution of my custom task.  I see it installing a newer version to, for example, /azp/agent/_work/_tool/node/12.20.0/x64/bin, but when the custom task runs, it always uses the node versions packaged with the agent.

Here's the relevant piece of my task.json

```
    "execution": {
        "Node10": {
            "target": "main.js"
        }
    }
```

And my pipelines.yml related to this task (custom task info obscured):

```
          - task: NodeTool@0
            displayName: Use Node 12.x
            inputs:
              versionSpec: 12.x
              checkLatest: true

          - task: MyCustomTask@1
            inputs:
              input1: value1
```

And output in my custom task saying it's using node10:

```
Starting: MyCustomTask
==============================================================================
Task         : My Custom Task
Description  : My Custom Task
Version      : 1.0.0
Author       : Author1
Help         : https://dev.azure.com/MyOrg/MyProject/_git/my-custom-task
==============================================================================
##[debug]Using node path: /azp/agent/externals/node10/bin/node
```

Am I missing something, or is this simply not supported until the agents ship with specifically something like node14?

**Comment by anatolybolshakov** [comment] 2020-12-22 09:17
Hi @rossbeehler we have reverted Node 14 handler (see https://github.com/microsoft/azure-pipelines-agent/pull/3151) - since we faced with with issues on several platforms during this migration. We are planning to complete it, but only after we migrate all pipeline tasks to Node 10 execution handler - so at the time there's no Node 14 execution handler on agent.
Thanks for heads up about task-lib docs - let me prepare PR to update it also.

**Comment by rossbeehler** [comment] 2020-12-22 16:00
Hi @anatolybolshakov, thanks for the quick reply.

How about the usage of NodeTool@0?  Is there any reason why that version of node isn't used for task execution?  The docs aren't very clear about when the specified node version is and isn't used.

**Comment by anatolybolshakov** [comment] 2020-12-23 11:06
@rossbeehler there are two different node versions shipped with agent which are used for task execution at the moment (please see [docs](https://github.com/microsoft/azure-pipelines-agent/blob/master/docs/node6.md) here). This is by design, one of the reason as I see - we can't guarantee that pipeline tasks will work as expected on any node version selected by NodeTool task.

**Comment by anatolybolshakov** [comment] 2020-12-24 14:59
@rossbeehler let me close this at the moment - please feel free to ask any questions also about this.

**Closed by anatolybolshakov** 2020-12-24 14:59 UTC
Labels: Area: Agent, question
