### ISSUE TITLE
[enhancement]: SelfUpdater.cs check/wait for processes to end

### ISSUE THREAD

**Issue by hedasp** [microsoft/azure-pipelines-agent#4799] opened 2024-05-15 16:00 UTC
When updating Windows Server deployment targets to lates version using the self updater from ADO the update script failed on two targets. 
\externals folder could not be renamed as  SMS Agent Host Service was holding files when the update ran. 
On one target, the processes had ended and upgrade was successful after re-naming the bin folder from bin.3.236.0 to bin and rerunning the _update.cmd from _work folder. 
Could it be possible to add a wait x seconds for processes to end step in the update script?

**Comment by kirill-ivlev** [comment] 2024-05-16 14:02
Duplicate of #4800, I will close this one

**Closed by kirill-ivlev** 2024-05-16 14:02 UTC
Labels: enhancement, Area: Agent, triage
