### ISSUE TITLE
"Connection reset" error when attempting to download JCenter binaries on Windows agent

### ISSUE THREAD

**Issue by hanselip** [microsoft/azure-pipelines-agent#3434] opened 2021-06-07 17:59 UTC
OS of the machine running the agent? Windows

Azure DevOps Type and Version: dev.azure.com

If dev.azure.com, what is your organization name? https://onedrive.visualstudio.com

## What's not working?
Without any changes in our builds or pipelines, we're seeing consistent "**Connection reset**" errors when our build attempts to fetch a binary from JCenter:

> Could not resolve all files for configuration ':onedrivecore:lintClassPath'. 
 > Could not download groovy-all-2.4.15.jar (org.codehaus.groovy:groovy-all:2.4.15) 
 > Could not get resource 'https://jcenter.bintray.com/org/codehaus/groovy/groovy-all/2.4.15/groovy-all-2.4.15.jar'. 
 > Could not GET 'https://jcenter.bintray.com/org/codehaus/groovy/groovy-all/2.4.15/groovy-all-2.4.15.jar'. 
 > Connection reset 
 > Could not download kotlin-reflect-1.3.72.jar (org.jetbrains.kotlin:kotlin-reflect:1.3.72) 
 > Could not get resource 'https://jcenter.bintray.com/org/jetbrains/kotlin/kotlin-reflect/1.3.72/kotlin-reflect-1.3.72.jar'. 
 > Could not GET 'https://jcenter.bintray.com/org/jetbrains/kotlin/kotlin-reflect/1.3.72/kotlin-reflect-1.3.72.jar'. 
 > Connection reset

These resources are available and can be downloaded locally without any issues.

**Comment by EzzhevNikita** [comment] 2021-06-08 05:45
Hi @hanselip, Could you please share full agent logs, they are located in _diag folder in the agent root.
And also, If I understand you correctly this functionality was working previously, so it will be great if you will be able to share the logs for those successful runs if possible or at least check which agent version was used in those successful runs.

**Comment by EzzhevNikita** [comment] 2021-06-09 05:51
@hanselip We have a similar issue that was reported in the internal ms channel. After investigation of your logs and logs for a similar issue, we didn't find any changes on Agent or Task's that could produce such behavior.
But during investigation, we found interesting thing regarding Bintray according to the message in their blog Bintray services seems to be deprecated from the 1 of May https://jfrog.com/blog/into-the-sunset-bintray-jcenter-gocenter-and-chartcenter/ . And we assume it could be the reason for the problems that you started to see recently in your pipelines. I suggest you contact their support at first https://jfrog.com/support/ . Since currently, this issue seems to be external for Azure DevOps.

**Comment by EzzhevNikita** [comment] 2021-06-10 05:49
Hi @hanselip that still seems to be an external issue, but we received several other issues for the same problem and the problem happens not only for JCenter binaries. Seems the internet connection issue caused by some infrastructure problems. As a workaround, could you please try to increase the timeout for the connection?

For Gradle it can be done by adding the following parameters to your build command:

./gradlew build -Dorg.gradle.internal.http.socketTimeout=60000 -Dorg.gradle.internal.http.connectionTimeout=60000

**Comment by EzzhevNikita** [comment] 2021-06-22 13:42
@hanselip Could you please try to upgrade Gradle to the 6.7.1 version? Please let me know if it will help you to resolve the issue.

**Comment by EzzhevNikita** [comment] 2021-06-28 15:01
@hanselip I am closing this item since this issue is external to the Azure DevOps agent.

**Closed by EzzhevNikita** 2021-06-28 15:01 UTC
Labels: Area: Agent, bug

**Comment by carstenhag** [comment] 2021-07-28 11:08
Hello there, we are having this issue on macOS agents, see Ticket 2107260050001036. We are not only having this issue with JCenter though, we also have it with Apache's Maven repo:

```
* What went wrong:
Execution failed for task ':libaddressinput:compileJava'.
> Could not resolve all files for configuration ':libaddressinput:compileClasspath'.
   > Could not download json-20171018.jar (org.json:json:20171018)
      > Could not get resource 'https://jcenter.bintray.com/org/json/json/20171018/json-20171018.jar'.
         > Could not GET 'https://jcenter.bintray.com/org/json/json/20171018/json-20171018.jar'.
            > Connection reset
```

```
* What went wrong:
Execution failed for task ':libaddressinput:compileJava'.
> Could not resolve all files for configuration ':libaddressinput:compileClasspath'.
   > Could not download json-20171018.jar (org.json:json:20171018)
      > Could not get resource 'https://repo.maven.apache.org/maven2/org/json/json/20171018/json-20171018.jar'.
         > Could not GET 'https://repo.maven.apache.org/maven2/org/json/json/20171018/json-20171018.jar'.

```
