### ISSUE TITLE
Self-hosted agent performs too slow

### ISSUE THREAD

**Issue by kolosovpetro** [microsoft/azure-pipelines-agent#4113] opened 2023-01-11 13:38 UTC
Version of your agent? **2.213.2**
OS of the machine running the agent? **Windows Server 2012 R2 Datacenter**
Azure Devops Type and Version: **dev.azure.com**

Agent software was reinstalled today, I thought that it might be some cache issue with locally downloaded tasks etc.

## Problem
Self-hosted azure pipelines agent performs too slow 
- Downloading tasks takes 15 minutes

![image](https://user-images.githubusercontent.com/31904595/211819838-1edb4fdf-b199-40dc-9e9d-7cd17f8f40d8.png)

- IIS Deploy task takes 1 hour while for other self-hosted environments it is around 2-3 minutes
![image](https://user-images.githubusercontent.com/31904595/211826515-05af3bd1-2d79-49e8-9c9a-757d4d882204.png)

## Worker log output
![image](https://user-images.githubusercontent.com/31904595/211828965-1b115c33-1726-4d65-8f12-34eb5dedd169.png)

As we can see, task is downloaded in nearly 1 second and then 11 minutes of idle of the agent

**Comment by Roman-Shchukin** [comment] 2023-01-11 15:37
Hi @kolosovpetro, could you please share more details about your issue:

- Did I understand correctly that on some machines everything works correctly, and on one of them this problem occurs?
- Does this problem occur every run or not? 
- When did this problem occur? 
- Was it working correctly before?

**Comment by kolosovpetro** [comment] 2023-01-13 13:20
> Do I understand correct that you are using MS-Hosted agent? The 214.1 agent version has been released, could you check, does it work better or not?

@Roman-Shchukin No, I mean agent on my **azure-hosted virtual machine** under **windows 2012 R2 Datacenter OS**, this VM is pinned under **uat** environment at azure devops. So it is not exactly machine under agent pool, it is machine under **uat** environment

There are three environments currently: 
- **dev**
- **qa**
- **uat**

Each environment has at only one VM, for **dev** & **qa** these are azure hosted VMs under Windows 2019 Datacenter OS, 
For **uat** is under **windows 2012 R2 Datacenter OS**

So, **dev** and **qa** environments are deployed OK. The problem only with IIS Deploy Task under **uat** environment, it takes too long according to the screenshots above.

I cannot test **uat** right now because I need to wait until next release.
Also, I gonna update agent to the latest version before next release

**Comment by Borda** [comment] 2023-02-21 23:55
We are facing similar issue; download 3.5GB takes 20-30min, so in such case it is 10x faster just to download models from hub straight with each run... :thinking: 
![image](https://user-images.githubusercontent.com/6035284/220485519-4186b154-6ff4-427d-a837-d7c184946804.png)
see log: https://dev.azure.com/Lightning-AI/Metrics/_build/results?buildId=138450&view=logs&j=5ea502cf-d418-510c-3b5f-c4ba606ae534&t=7d22084b-05ec-50ed-a57a-20ddc18c02c9

**Comment by Francois-du-Plessis** [comment] 2023-05-24 07:03
We are experiencing a similar issue after updating to one of the latest versions of the Agent 3.220.0 (as time of writing). This is a self-hosted agent and it seems like it is slow to start up. Starting a deployment takes about 1m to 2m just for the first logs to be displayed. The total time taken but tasks are less than 50 seconds but the agent is reporting that it took 2m30s

![image](https://github.com/microsoft/azure-pipelines-agent/assets/18027700/34005c13-1ea6-4ebf-8072-eed83f9e477b)

**Comment by gt97** [comment] 2023-05-24 07:06
I think it is an issue that has been solved in version 3.220.2.
I had the same issue using version 2.218.* and 3.220.0. The issue is solved with version 3.220.2.

**Comment by Francois-du-Plessis** [comment] 2023-05-24 09:58
Updated to 3.220.2 as suggested by @gt97. That solved the issue for use. Thanks!

**Comment by ussserrr** [comment] 2023-05-25 09:57
> I think it is an issue that has been solved in version 3.220.2. I had the same issue using version 2.218.* and 3.220.0. The issue is solved with version 3.220.2.

I can confirm v3.220.2 works much faster, thinking about how long it can keep up for this time... The bug looks very volatile since people run into it for about 3-4 years with random versions and setups...

**Comment by kirill-ivlev** [comment] 2023-08-31 14:57
Closing this one, since bug seems to be resolved.
Thanks for feedback!

**Closed by kirill-ivlev** 2023-08-31 14:57 UTC
Labels: question, Area: Agent, VM, performance

**Comment by vallgrenerik** [comment] 2023-09-14 13:38
Wow! Such a performance increase! Thanks for the fix, I can also confirm!
