### ISSUE TITLE
[Question]: VM has reported a failure when processing extension 'Microsoft.Azure.DevOps.Pipelines.Agent'. Error message: "The Extension failed to execute: 'ascii' codec can't decode byte 0xe2 in position 2677: ordinal not in range(128)"

### ISSUE THREAD

**Issue by AndriyDmytrenko** [microsoft/azure-pipelines-agent#4204] opened 2023-03-15 19:01 UTC
### Describe your question

Hello,

Using a Virtual Machine Scale Set for Azure DevOps Pipelines agent pool, getting the following error while provisioning the vm from the scale set:

Message
VM has reported a failure when processing extension 'Microsoft.Azure.DevOps.Pipelines.Agent'. Error message: "The Extension failed to execute: 'ascii' codec can't decode byte 0xe2 in position 3229: ordinal not in range(128)" More information on troubleshooting is available at https://aka.ms/vmextensionlinuxtroubleshoot

Already tried to re-create the VMSS.

### Versions

Azure DevOps 2.218.1 (I guess from the extension URL) for Linux

### Environment type (Please select at least one enviroment where you face this issue)

- [ ] Self-Hosted
- [ ] Microsoft Hosted
- [X] VMSS Pool
- [ ] Container

### Azure DevOps Server type

dev.azure.com (formerly visualstudio.com)

### Operation system

Ubuntu Server 22.04 LTS

### Version controll system

N/A

**Comment by ogliznutsa** [comment] 2023-03-16 09:04
Hi,

I'm getting the same error, it is build agent that cannot connect to Azure DevOps with https. Root of the problem is that the build agent is developed with .Net 3.1 which is not compatible with OpenSSL v3 which probably is installed in your VM operating system.

**Comment by sergey-koryshev** [comment] 2023-03-17 13:34
Hi @AndriyDmytrenko, could you please try to use Ubuntu 20.04 and come back with results?

**Comment by AndriyDmytrenko** [comment] 2023-03-17 14:35
> Hi @AndriyDmytrenko, could you please try to use Ubuntu 20.04 and come back with results?

Actually yes, already tried and it seems it's a workaround for now.
I can confirm everything works as expected with Ubuntu Server 20.04 LTS

**Comment by sergey-koryshev** [comment] 2023-03-23 08:12
@AndriyDmytrenko hi, thank you for confirmation. Please use `Ubuntu Server 20.04` until agent of version `3.x` is released.

I close the issue, please feel free to reactive it or create new one.

**Closed by sergey-koryshev** 2023-03-23 08:12 UTC
Labels: Area: Agent

**Comment by o-l-a-v** [comment] 2023-04-13 09:23
Got this error today. VMSS self hosted agent, Ubuntu 22.04. Agent 3.218.0 according to Azure DevOps.

The agent seem to work just fine though. Just got this error in the Azure portal, no error in Azure DevOps -> Agent pools -> `<pool_name>` -> Diagnostics.

**Comment by sergey-koryshev** [comment] 2023-04-25 17:52
@o-l-a-v, the error actually doesn't say anything specific about the issue. It's just internal python-script error, I filled issue to fix it: https://github.com/microsoft/vsts-azurevm-extension/issues/213
