### ISSUE TITLE
GIT LFS not working on agent 2.214.1 in release pipeline

### ISSUE THREAD

**Issue by PawPaw** [microsoft/azure-pipelines-agent#4115] opened 2023-01-13 07:11 UTC
## Agent Version and Platform
2.214.1

OS of the machine running the agent? Linux - 

Agent Pool: "Azure Pipelines", Agent specification: "ubuntu-20.04"

## Azure DevOps Type and Version
dev.azure.com

## What's not working?
After upgrade from agent version 2.213.2 to 2.214.1 my release pipeline refuses to checkout artifact files from GIT LFS. Configuration of pipeline is unchanged. 

Settings are
![image](https://user-images.githubusercontent.com/1478345/212258236-10355684-741b-41bd-a75b-ab9741d8e1a0.png)

There are no errors in log,

Workaround: I had to add new bash task to my pipeline, where I manually run command "git-lfs pull" in checked out repository on agent.

**Comment by Roman-Shchukin** [comment] 2023-01-13 08:53
Hi @PawPaw  thanks for reporting! We will get to the task as soon as possible.

**Comment by Roman-Shchukin** [comment] 2023-01-13 15:09
Hi @PawPaw, I can't reproduce this problem, could you tell me the steps to reproduce it?

**Comment by PawPaw** [comment] 2023-01-16 07:02
Hi @Roman-Shchukin 

- Create new Release Pipeline
- Add Azure Repo that contains some larger file (e.g. >1MB),  stored in LFS as artifact for the pipeline. Settings of the artifact are shown in first comment.
- Create new stage, which uses artifact with azure repo. Stage is running on Azure Pipelines agent ubuntu-2004
- Add task, that will use file stored in LFS. Simple 'ls -la' can be used.
- Run pipeline

On agent should be checked out file from LFS. If you used ls -la command, you will see that file will be present on agent, but its size will be much smaller than it shoud be. Something about 200B (file contains only reference to LFS, not real content of the file).

Here is part of init script to show what versions and what agent is used:
```
2023-01-16T06:32:55.8328443Z Agent name: 'Azure Pipelines 2'
2023-01-16T06:32:55.8328904Z Agent machine name: 'fv-az84-912'
2023-01-16T06:32:55.8329197Z Current agent version: '2.214.1'
2023-01-16T06:32:55.8365513Z ##[group]Operating System
2023-01-16T06:32:55.8365776Z Ubuntu
2023-01-16T06:32:55.8365917Z 20.04.5
2023-01-16T06:32:55.8366109Z LTS
2023-01-16T06:32:55.8366260Z ##[endgroup]
2023-01-16T06:32:55.8366426Z ##[group]Runner Image
2023-01-16T06:32:55.8366674Z Image: ubuntu-20.04
2023-01-16T06:32:55.8366858Z Version: 20230109.1
2023-01-16T06:32:55.8367314Z Included Software: https://github.com/actions/runner-images/blob/ubuntu20/20230109.1/images/linux/Ubuntu2004-Readme.md
2023-01-16T06:32:55.8367782Z Image Release: https://github.com/actions/runner-images/releases/tag/ubuntu20%2F20230109.1
2023-01-16T06:32:55.8368123Z ##[endgroup]
2023-01-16T06:32:55.8368307Z ##[group]Runner Image Provisioner
2023-01-16T06:32:55.8368661Z 2.0.98.1
2023-01-16T06:32:55.8368811Z ##[endgroup]
2023-01-16T06:32:55.8369739Z Current image version: '20230109.1'
2023-01-16T06:32:55.8371731Z Agent running as: 'vsts'
2023-01-16T06:32:55.8380754Z Prepare release directory.
```

**Comment by PawPaw** [comment] 2023-01-16 10:56
The issue is maybe related to image, not to agent. I realized I am using agent on local machine (old CentOS) in version 2.211.1. I updated it to 2.214.1 and LFS is working.

**Comment by Roman-Shchukin** [comment] 2023-01-16 11:35
@PawPaw great! I have reproduced the issue only with empty .gitattributes file.

@Mortaelth could you please confirm that you have still had the issue with LFS?

**Comment by Roman-Shchukin** [comment] 2023-01-27 09:42
Hi @PawPaw closing this, feel free to ask any other questions or let us know if it's still relevant for you.

**Closed by Roman-Shchukin** 2023-01-27 09:42 UTC
Labels: bug, Area: Agent
