### ISSUE TITLE
"No usable version of libssl" on RHEL 9

### ISSUE THREAD

**Issue by palladia** [microsoft/azure-pipelines-agent#3974] opened 2022-09-26 19:20 UTC
Using v2.210.1 on a RHEL 9 VM, I get following error when executing config.sh:

Enter personal access token > ****************************************************
No usable version of libssl was found
./config.sh: line 86: 61342 Aborted                 (core dumped) ./bin/Agent.Listener configure "$@"

**Comment by DenisRumyantsev** [comment] 2022-09-27 05:03
Hi, @palladia, thanks for reporting the issue, we will investigate it

**Comment by palladia** [comment] 2022-10-21 16:10
Could you provide an estimate on when .NET 6 support will be available?  If it's not soon, could you provide specific packages that must be installed for RHEL 9 to work?

**Comment by sergey-koryshev** [comment] 2022-10-26 08:21
@palladia you can use these packages: https://github.com/microsoft/azure-pipelines-agent/releases/tag/v3.212.0

**Comment by sergey-koryshev** [comment] 2022-11-04 08:50
@palladia can you please confirm that the package works correctly on your RHEL 9 environment?

**Comment by BrunoBlanes** [comment] 2022-11-04 23:44
@sergey-koryshev can confirm it does solve the problem for me on CentOS Stream 9.

**Comment by palladia** [comment] 2022-11-09 20:07
Sorry for the late response.  V3.212.0 does work with RHEL 9.  Thanks.

**Comment by sergey-koryshev** [comment] 2022-11-10 08:17
@BrunoBlanes, @palladia okay, thank you for confirmation. I'm closing the issue as mitigated. Feel free to reopen it or create a new one.

**Closed by sergey-koryshev** 2022-11-10 08:17 UTC
Labels: Area: Agent

**Comment by joergho** [comment] 2022-12-20 14:48
I also confirm, that the issue *was* fixed with [v3.312.0](https://vstsagentpackage.azureedge.net/agent/2.212.0/vsts-agent-linux-x64-2.212.0.tar.gz).
However, with [v3.313.2](https://vstsagentpackage.azureedge.net/agent/2.213.2/vsts-agent-linux-x64-2.213.2.tar.gz) (the version which is detected as latest using [1]) on Ubuntu 22.04.1 LTS, I am seeing the same issue again.

[1] https://learn.microsoft.com/en-us/azure/devops/pipelines/agents/docker?view=azure-devops#linux

**Comment by Javierkaiser** [comment] 2023-01-31 17:10
I also confirm that the issue is fixed using v3.212.0 on Fedora 37.

**Comment by azpoul** [comment] 2023-03-28 08:49
> 

Same issue for us. Ubuntu 22.04
