### ISSUE TITLE
Azure DevOps - Self-Hosted Agents - Residual Artifacts Causing Subsequent Pipeline Execution Failures

### ISSUE THREAD

**Issue by AErmie** [microsoft/azure-pipelines-agent#3233] opened 2021-02-02 02:20 UTC
Here's an interesting and perplexing issue... 

I’m using Azure DevOps Server (on-premises), in connection with using Self-Hosted Agents. 

When executing a pipeline that creates several directories (ie. mkdir ABC), and also creates/stores files in these directories, on the very first time the pipeline is executed, everything works without issue.

However, on all subsequent pipeline execution attempts, the very first step (ie. Checkout 'repoName') fails. We've attempted to add the following 'cleaning' commands to the execution, but those didn't resolve the issue. 

``` YAML
-job: Job
workspace:
   clean: all
steps:
- checkout: self
   submodules: true
   clean: true
```

Digging deeper into the debugging... we see the following error reoccurring: 

`##[error]One or more errors occurred. (One or more errors occurred. (Access to the path '/data/TFSBuilds/01/299/s/terraform/super-linter.report/super-linter-TERRAFORM_TERRASCAN.tap' is denied.)) (One or more errors occurred. (Access to the path '/data/TFSBuilds/01/299/s/terraform/super-linter.report/super-linter-JSON.tap' is denied.)) (Access to the path '/data/TFSBuilds/01/299/s/terraform/super-linter.report/super-linter-TERRAFORM_TERRASCAN.tap' is denied.) (Access to the path '/data/TFSBuilds/01/299/s/terraform/super-linter.report/super-linter-JSON.tap' is denied.)`

Note: The referenced 'super-linter.report/super-linter-TERRAFORM_TERRASCAN.tap' and 'super-linter.report/super-linter-TERRAFORM_TERRASCAN.tap' are the folders/files that get created within this pipeline. 

This affects all subsequent steps/tasks within the pipeline because they now reference/use existing files versus re-generating them on each independent pipeline execution. What we would appreciate the insight into, is how self-hosted agents are managed and configured, in particular around residual artifacts that may be left behind from pipeline execution. 

NOTE: This issue does not occur when executing pipelines using Azure DevOps online, as each Agent machine is ephemeral and thrown away at the end of the execution. 

Appreciate any thoughts/insights.

**Comment by anatolybolshakov** [comment] 2021-02-03 09:14
Hi @AErmie could you please share full agent logs containing this error?

**Comment by AErmie** [comment] 2021-02-08 15:06
Hey @anatolybolshakov, sorry for the delay (I missed your message). Here are the logs. 
[logs_93296.zip](https://github.com/microsoft/azure-pipelines-agent/files/5944509/logs_93296.zip)

**Comment by vladislav-ryzhov** [comment] 2021-04-19 12:34
Hi @AErmie.
Unfortunately, we were unable to reproduce your issue. Could you please provide more details about this issue?
There is one command in your YML file "docker exec superLinter chown -R "$(id -u):$(id -g)" /tmp/lint --verbose" 
It looks like these two lines from GitHub Super-Linter Code Scan logs(screenshot №1) are the result of this command. Could this be the cause of your problem? Could docker have changed something in the access rules?

Please feel free to share any information about this issue with us.

![image](https://user-images.githubusercontent.com/79705997/115234312-8f979200-a121-11eb-80af-2d1add97d16c.png)

**Comment by vladislav-ryzhov** [comment] 2021-04-19 12:50
Hi @AErmie.
Unfortunately, we were unable to reproduce your issue. Could you tell us more clearly about your issue?
There is one command in your YML file "docker exec superLinter chown -R "$(id -u):$(id -g)" /tmp/lint --verbose" 
It looks like these two lines from GitHub Super-Linter Code Scan logs(screenshot №1) are the result of this command. Could this be the cause of your problem? Could docker have changed something in the access rules?
![image](https://user-images.githubusercontent.com/79705997/115238966-efdd0280-a126-11eb-9bdb-6fe7f81b6a9b.png)

**Comment by AErmie** [comment] 2021-04-26 22:35
Hi @vladislav-ryzhov 
The extra commands (namely: chown -R "$(id -u):$(id -g)") were required so that the temporary files and directories created by running the Super-Linter are run under 'root'. This causes issues with self-hosted agents, as the Agent account is not root, and therefore cannot delete/clean up any residual files/folders leftover from a previous pipeline run.

**Comment by vladislav-ryzhov** [comment] 2021-04-30 16:20
Hi  @AErmie .
We tried to run superLinter under the usual user by using this command: --user 1000:1000, but we got this issue 
![image](https://user-images.githubusercontent.com/79705997/116721497-0a945e80-a9e6-11eb-9616-f990646314d4.png)
It looks like this plugin cannot work without "root" but git checkout fails then. 
So, if you want to use agent under "root" you should configure your agent as a service by this command: sudo ./svc.sh install **root** (you should use root)
More info you can find [here](https://docs.microsoft.com/en-us/azure/devops/pipelines/agents/v2-linux?view=azure-devops#run-as-a-systemd-service).

**Comment by vladislav-ryzhov** [comment] 2021-05-05 14:47
@AErmie Let me close this one since this is external issue. Please feel free to ask any further questions.

**Closed by vladislav-ryzhov** 2021-05-05 14:47 UTC
Labels: Area: ABTT, Area: Agent, bug
