### ISSUE TITLE
env:BUILD_SOURCEBRANCHNAME variable is populated wrong when the branch name contains slash ('/'), e.g.: feature/my-new-feature

### ISSUE THREAD

**Issue by PaulGiletich** [Microsoft/azure-pipelines-agent#1631] opened 2018-06-19 20:11 UTC
## Have you tried trouble shooting?
Yes

## Agent Version and Platform
Version of your agent? 2.102.0/2.100.1/...
Hosted agent
OS of the machine running the agent? OSX/Windows/Linux/...
Windows
## VSTS Type and Version
VisualStudio.com

If VisualStudio.com, what is your account name? http://account.visualstudio.com
slb1-swt
## What's not working?

env:BUILD_SOURCEBRANCHNAME envionment variable is populated wrong when the branch name contains slash ('/'), ex: feature/my-new-feature

Repro steps: 
1. create a branch named "feature/my-feature"
2. run a build from this branch with PowerShell script: "echo $env:BUILD_SOURCEBRANCHNAME

Expected result: 
"feature/my-feature"

Actual result: 
"my-feature"

## Agent and Worker's Diagnostic Logs
N/A

**Comment by Ryanman** [comment] 2018-06-27 16:40
Not part of the team, but if you view the [build variables](https://docs.microsoft.com/en-us/vsts/pipelines/build/variables?view=vsts&tabs=batch) link you can see you don't want to use Build.SourceBranchName. You want to use Build.SourceBranch and remove the "ref/" part of the SourceBranch. This is so people can use branch folders and get the actual name.

**Comment by TingluoHuang** [comment] 2018-07-16 15:00
@PaulGiletich the variable is set on the service side before it sends to the agent, i would suggest you post this issue to https://developercommunity.visualstudio.com/spaces/21/index.html
from what i know, the current behavior is "by design", since we can't change existing variable easily (people may rely on this weird variable), what we can do is add a new variable to have the right information, like `BUILD_SOURCEBRANCHFULLNAME`

**Comment by moswald** [comment] 2018-11-14 17:16
Closing. There is a recommended alternative.

**Closed by moswald** 2018-11-14 17:16 UTC
Labels: Area: Build

**Comment by harouny** [comment] 2019-01-07 22:09
What is the recommended alternative?

I want to add branch name like (feature/123) to  build name. Me adding a custom variable in tasks is too late.

**Comment by harouny** [comment] 2019-01-07 23:12
@moswald thanks for responding. Unfortunately I think its a bit confusing to add ```refs/heads/feature/abc``` to my build name since developers named the branch ```feature/abc``` at the start. 

However, I can understand why the team might be reluctant to add an extra ```Build.SourceBranchFullName``` or something similar to have the name without those git added prefixes. I still can't find the right solution though.

**Comment by moswald** [comment] 2019-01-07 23:20
@harouny When you say "build name", do you mean the build number? [You can use the `updatebuildnumber` command in a powershell script](https://github.com/Microsoft/azure-pipelines-tasks/blob/master/docs/authoring/commands.md), and using powershell you should be able to easily strip the leading `refs/heads/`.

**Comment by harouny** [comment] 2019-01-07 23:22
@moswald Yes build number. Thanks for the workaround!

**Comment by worldspawn** [comment] 2020-07-15 03:06
@moswald this is not even remotely acceptable. We need hacks and scripts to get the branch name. Just the basic branch name. This should not be a thing, this a straight up bug, watching you fumble and argue for why it is somehow ok is just depressing. What are you guys doing?? This is a commercial service we pay for! Its not ok for it have stupid massive problems like this 3 year old issue! You have lost the plot. The hell with this product.
