### ISSUE TITLE
[BUG]: steps.download stopped working

### ISSUE THREAD

**Issue by kauemendes** [microsoft/azure-pipelines-agent#4270] opened 2023-05-11 07:45 UTC
### What happened?

Pipelines that need to download build artifacts automatically invoke the steps.download task, this process is practically transparent, with no need to manually download it. It turns out that after the last update the task steps download does not fail, however it does not download the build pipeline artifact from a previous stage.

The conditions are exactly the same as they were and have always worked, the only difference in the change is the update of the Azure DevOps agents.

As we are working with agents via scalesets and images created from the https://github.com/actions/runner-images repository, the agents update automatically, so what I can say is that version 3.220.1 is not working, but 3.220.0 worked. 

Log output with previous agent version 3.220.0:

```
Starting: Download Artifact
==============================================================================
Task         : Download build artifacts
Description  : Download files that were saved as artifacts of a completed build
Version      : 1.220.0
Author       : Microsoft Corporation
Help         : https://docs.microsoft.com/azure/devops/pipelines/tasks/utility/download-build-artifacts
==============================================================================
Download from the specified build: #407470
Download artifact to: C:\a\1/
Pattern: **
Minimatch patterns: [**]
Applying include pattern against original list.
2 matches
2 final results
Start downloading FCS artifact- 1.0.407.470
Using default max parallelism.
Max dedup parallelism: 192
Downloading: C:\a\1/1.0.407.470/1.0.407.470.zip
Downloading artifact finished.
```

Log output with the current agent version 3.220.1:

```
Starting: Download Artifact
==============================================================================
Task         : Download build artifacts
Description  : Download files that were saved as artifacts of a completed build
Version      : 1.220.0
Author       : Microsoft Corporation
Help         : https://docs.microsoft.com/azure/devops/pipelines/tasks/utility/download-build-artifacts
==============================================================================
Download from the specified build: #412133
Download artifact to: C:\a\1/
Pattern: **
Minimatch patterns: [**]
Applying include pattern against original list.
1 matches
1 final results
Start downloading FCS artifact- 1.0.412.133
Downloading artifact finished.
Finishing: Download Artifact
```

As you can see, even though it says that the file was downloaded in this most current log, it does not inform which directory the zip was downloaded to, as it was not in the previous one, and when extracting, the extracting task cannot find the file where it was supposed to be .

Log of extract zip file: 
```
2023-05-10T17:00:07.0565073Z ##[section]Starting: Extract files 
2023-05-10T17:00:07.0651047Z ==============================================================================
2023-05-10T17:00:07.0651152Z Task         : Extract files
2023-05-10T17:00:07.0651207Z Description  : Extract a variety of archive and compression files such as .7z, .rar, .tar.gz, and .zip
2023-05-10T17:00:07.0651359Z Version      : 1.213.0
2023-05-10T17:00:07.0651442Z Author       : Microsoft Corporation
2023-05-10T17:00:07.0651537Z Help         : https://docs.microsoft.com/azure/devops/pipelines/tasks/utility/extract-files
2023-05-10T17:00:07.0651779Z ==============================================================================
2023-05-10T17:00:07.3761251Z Error: Specified archive: C:\a\1\1.0.412.133\1.0.412.133.zip can not be extracted because it can not be accessed: Error: ENOENT: no such file or directory, stat 'C:\a\1\1.0.412.133\1.0.412.133.zip'
2023-05-10T17:00:07.3761934Z     at Object.statSync (node:fs:1583:3)
2023-05-10T17:00:07.3762386Z     at Object.stats (C:\a\_tasks\ExtractFiles_5e1e3830-fbfb-11e5-aab1-090c92bc4988\1.213.0\node_modules\azure-pipelines-task-lib\task.js:558:15)
2023-05-10T17:00:07.3763033Z     at findFiles (C:\a\_tasks\ExtractFiles_5e1e3830-fbfb-11e5-aab1-090c92bc4988\1.213.0\extractfilestask.js:61:32)
2023-05-10T17:00:07.3763535Z     at doWork (C:\a\_tasks\ExtractFiles_5e1e3830-fbfb-11e5-aab1-090c92bc4988\1.213.0\extractfilestask.js:301:21)
2023-05-10T17:00:07.3764063Z     at Object.<anonymous> (C:\a\_tasks\ExtractFiles_5e1e3830-fbfb-11e5-aab1-090c92bc4988\1.213.0\extractfilestask.js:328:1)
2023-05-10T17:00:07.3764525Z     at Module._compile (node:internal/modules/cjs/loader:1196:14)
2023-05-10T17:00:07.3764926Z     at Object.Module._extensions..js (node:internal/modules/cjs/loader:1250:10)
2023-05-10T17:00:07.3765317Z     at Module.load (node:internal/modules/cjs/loader:1074:32)
2023-05-10T17:00:07.3765686Z     at Function.Module._load (node:internal/modules/cjs/loader:909:12)
2023-05-10T17:00:07.3766100Z     at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:81:12) {
2023-05-10T17:00:07.3767369Z   errno: -4058,
2023-05-10T17:00:07.3767610Z   syscall: 'stat',
2023-05-10T17:00:07.3767838Z   code: 'ENOENT',
2023-05-10T17:00:07.3768106Z   path: 'C:\\a\\1\\1.0.412.133\\1.0.412.133.zip'
2023-05-10T17:00:07.3768347Z }
2023-05-10T17:00:07.3803865Z ##[error]Specified archive: C:\a\1\1.0.412.133\1.0.412.133.zip can not be extracted because it can not be accessed: Error: ENOENT: no such file or directory, stat 'C:\a\1\1.0.412.133\1.0.412.133.zip'
    at Object.statSync (node:fs:1583:3)
    at Object.stats (C:\a\_tasks\ExtractFiles_5e1e3830-fbfb-11e5-aab1-090c92bc4988\1.213.0\node_modules\azure-pipelines-task-lib\task.js:558:15)
    at findFiles (C:\a\_tasks\ExtractFiles_5e1e3830-fbfb-11e5-aab1-090c92bc4988\1.213.0\extractfilestask.js:61:32)
    at doWork (C:\a\_tasks\ExtractFiles_5e1e3830-fbfb-11e5-aab1-090c92bc4988\1.213.0\extractfilestask.js:301:21)
    at Object.<anonymous> (C:\a\_tasks\ExtractFiles_5e1e3830-fbfb-11e5-aab1-090c92bc4988\1.213.0\extractfilestask.js:328:1)
    at Module._compile (node:internal/modules/cjs/loader:1196:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1250:10)
    at Module.load (node:internal/modules/cjs/loader:1074:32)
    at Function.Module._load (node:internal/modules/cjs/loader:909:12)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:81:12) {
  errno: -4058,
  syscall: 'stat',
  code: 'ENOENT',
  path: 'C:\\a\\1\\1.0.412.133\\1.0.412.133.zip'
}
2023-05-10T17:00:07.3837147Z ##[section]Finishing: Extract files 
```

### Versions

3.220.1

### Environment type (Please select at least one enviroment where you face this issue)

- [X] Self-Hosted
- [ ] Microsoft Hosted
- [ ] VMSS Pool
- [ ] Container

### Azure DevOps Server type

dev.azure.com (formerly visualstudio.com)

### Operation system

Ubuntu 20.04 and Windows 2022

### Version controll system

3.220.1

### Relevant log output

```shell
Starting: Download Artifact
==============================================================================
Task         : Download build artifacts
Description  : Download files that were saved as artifacts of a completed build
Version      : 1.220.0
Author       : Microsoft Corporation
Help         : https://docs.microsoft.com/azure/devops/pipelines/tasks/utility/download-build-artifacts
==============================================================================
Download from the specified build: #407470
Download artifact to: C:\a\1/
Pattern: **
Minimatch patterns: [**]
Applying include pattern against original list.
2 matches
2 final results
Start downloading FCS artifact- 1.0.407.470
Using default max parallelism.
Max dedup parallelism: 192
Downloading: C:\a\1/1.0.407.470/1.0.407.470.zip
Downloading artifact finished.

Starting: Download Artifact
==============================================================================
Task         : Download build artifacts
Description  : Download files that were saved as artifacts of a completed build
Version      : 1.220.0
Author       : Microsoft Corporation
Help         : https://docs.microsoft.com/azure/devops/pipelines/tasks/utility/download-build-artifacts
==============================================================================
Download from the specified build: #412133
Download artifact to: C:\a\1/
Pattern: **
Minimatch patterns: [**]
Applying include pattern against original list.
1 matches
1 final results
Start downloading FCS artifact- 1.0.412.133
Downloading artifact finished.
Finishing: Download Artifact

2023-05-10T17:00:07.0565073Z ##[section]Starting: Extract files 
2023-05-10T17:00:07.0651047Z ==============================================================================
2023-05-10T17:00:07.0651152Z Task         : Extract files
2023-05-10T17:00:07.0651207Z Description  : Extract a variety of archive and compression files such as .7z, .rar, .tar.gz, and .zip
2023-05-10T17:00:07.0651359Z Version      : 1.213.0
2023-05-10T17:00:07.0651442Z Author       : Microsoft Corporation
2023-05-10T17:00:07.0651537Z Help         : https://docs.microsoft.com/azure/devops/pipelines/tasks/utility/extract-files
2023-05-10T17:00:07.0651779Z ==============================================================================
2023-05-10T17:00:07.3761251Z Error: Specified archive: C:\a\1\1.0.412.133\1.0.412.133.zip can not be extracted because it can not be accessed: Error: ENOENT: no such file or directory, stat 'C:\a\1\1.0.412.133\1.0.412.133.zip'
2023-05-10T17:00:07.3761934Z     at Object.statSync (node:fs:1583:3)
2023-05-10T17:00:07.3762386Z     at Object.stats (C:\a\_tasks\ExtractFiles_5e1e3830-fbfb-11e5-aab1-090c92bc4988\1.213.0\node_modules\azure-pipelines-task-lib\task.js:558:15)
2023-05-10T17:00:07.3763033Z     at findFiles (C:\a\_tasks\ExtractFiles_5e1e3830-fbfb-11e5-aab1-090c92bc4988\1.213.0\extractfilestask.js:61:32)
2023-05-10T17:00:07.3763535Z     at doWork (C:\a\_tasks\ExtractFiles_5e1e3830-fbfb-11e5-aab1-090c92bc4988\1.213.0\extractfilestask.js:301:21)
2023-05-10T17:00:07.3764063Z     at Object.<anonymous> (C:\a\_tasks\ExtractFiles_5e1e3830-fbfb-11e5-aab1-090c92bc4988\1.213.0\extractfilestask.js:328:1)
2023-05-10T17:00:07.3764525Z     at Module._compile (node:internal/modules/cjs/loader:1196:14)
2023-05-10T17:00:07.3764926Z     at Object.Module._extensions..js (node:internal/modules/cjs/loader:1250:10)
2023-05-10T17:00:07.3765317Z     at Module.load (node:internal/modules/cjs/loader:1074:32)
2023-05-10T17:00:07.3765686Z     at Function.Module._load (node:internal/modules/cjs/loader:909:12)
2023-05-10T17:00:07.3766100Z     at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:81:12) {
2023-05-10T17:00:07.3767369Z   errno: -4058,
2023-05-10T17:00:07.3767610Z   syscall: 'stat',
2023-05-10T17:00:07.3767838Z   code: 'ENOENT',
2023-05-10T17:00:07.3768106Z   path: 'C:\\a\\1\\1.0.412.133\\1.0.412.133.zip'
2023-05-10T17:00:07.3768347Z }
2023-05-10T17:00:07.3803865Z ##[error]Specified archive: C:\a\1\1.0.412.133\1.0.412.133.zip can not be extracted because it can not be accessed: Error: ENOENT: no such file or directory, stat 'C:\a\1\1.0.412.133\1.0.412.133.zip'
    at Object.statSync (node:fs:1583:3)
    at Object.stats (C:\a\_tasks\ExtractFiles_5e1e3830-fbfb-11e5-aab1-090c92bc4988\1.213.0\node_modules\azure-pipelines-task-lib\task.js:558:15)
    at findFiles (C:\a\_tasks\ExtractFiles_5e1e3830-fbfb-11e5-aab1-090c92bc4988\1.213.0\extractfilestask.js:61:32)
    at doWork (C:\a\_tasks\ExtractFiles_5e1e3830-fbfb-11e5-aab1-090c92bc4988\1.213.0\extractfilestask.js:301:21)
    at Object.<anonymous> (C:\a\_tasks\ExtractFiles_5e1e3830-fbfb-11e5-aab1-090c92bc4988\1.213.0\extractfilestask.js:328:1)
    at Module._compile (node:internal/modules/cjs/loader:1196:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1250:10)
    at Module.load (node:internal/modules/cjs/loader:1074:32)
    at Function.Module._load (node:internal/modules/cjs/loader:909:12)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:81:12) {
  errno: -4058,
  syscall: 'stat',
  code: 'ENOENT',
  path: 'C:\\a\\1\\1.0.412.133\\1.0.412.133.zip'
}
2023-05-10T17:00:07.3837147Z ##[section]Finishing: Extract files
```

**Comment by kraduk** [comment] 2023-05-11 10:43
we are seeing this issue downloading artifacts with the DownloadPipelineArtifact@2. Nothing changed in the multiple pipelines it just failed on the agent update

**Comment by tomgreen82** [comment] 2023-05-12 08:48
We are seeing the same issue on both a Microsoft Hosted agent using the latest ubuntu image and a self-hosted machine on a windows server, only change I can see from previous runs is the Agent version increased from 3.220.0 and 3.220.1. Downgrading the self-hosted machine back to the previous version resolved that however we cannot control the agent version on the Microsoft hosted agent.

**Comment by ekhaydarov** [comment] 2023-05-12 13:38
Is it not possible to select the agent version in the yaml? That should be an option, to let users be able to fix issues quickly in case of bug like this being rolled out.

**Comment by oliviergareau** [comment] 2023-05-12 17:26
Someone opened the same issue yesterday in microsoft/azure-pipelines-tasks and has yet to hear from Microsoft. The OP noticed that this behavior only happens with artifacts that have `.` in their name.

https://github.com/microsoft/azure-pipelines-tasks/issues/18272

Yesterday I also raised the issue in Azure DevOps community

https://developercommunity.visualstudio.com/t/Azure-DevOps-YAML-pipeline-with-a-deploy/10361263

This issue is pretty significant since it breaks all my artifact downloads. I hope Microsoft acknowledges it soon!

**Comment by tomgreen82** [comment] 2023-05-12 19:19
@ekhaydarov you can specify an agent version in the demands for a pool in yaml (https://learn.microsoft.com/en-us/azure/devops/pipelines/yaml-schema/pool?view=azure-pipelines). But when i attempted this as a potential work around i received this error.

```
##[error]No agent found in pool Azure Pipelines which satisfies the following demand: Agent.Version. All demands: Agent.Version -equals 3.220.0, Agent.Version -gtVersion 2.163.1
```

So it seems only possible if you have an agent available on that specific version already and I've yet to find a way to change the default behaviour of Microsoft hosted agents which is to always use the latest agent version. 

This suggests the only option is to log a Github issue or switch to a self-hosted agent (https://learn.microsoft.com/en-us/azure/devops/pipelines/agents/hosted?view=azure-devops&tabs=yaml#what-can-i-do-if-software-i-need-is-removed-or-replaced-with-a-newer-version)

**Comment by LiliaSabitova** [comment] 2023-05-16 10:59
Hi @kauemendes thank you for reporting this.
We've defined the root cause and we're working on fixing it.
Closing this as a duplicate:
https://github.com/microsoft/azure-pipelines-agent/issues/4268 - I will post updates here.

**Closed by LiliaSabitova** 2023-05-16 10:59 UTC
Labels: bug, Area: Agent, triage
