### ISSUE TITLE
variable VSTS_AGENT_CHANNEL_TIMEOUT not works

### ISSUE THREAD

**Issue by superduperfajnylogin** [microsoft/azure-pipelines-agent#4127] opened 2023-01-24 11:55 UTC
variable VSTS_AGENT_CHANNEL_TIMEOUT not works. Implemented in pipeline and in agent capabilities.
Task canceled after 30seconds of inactivity on stdout

```
2023-01-24T11:43:22.2848953Z 6d401a2882c7: Layer already exists
2023-01-24T11:43:22.3394948Z 3da8d274863e: Layer already exists
2023-01-24T11:43:22.3902253Z 9162ee2a1464: Layer already exists
2023-01-24T11:43:22.4400890Z d541eb3ab671: Layer already exists
2023-01-24T11:43:22.4887015Z 72a234e9025f: Layer already exists
2023-01-24T11:43:22.5435011Z 7e963e684504: Layer already exists
2023-01-24T11:43:22.6022429Z 579f2f220e9d: Layer already exists
2023-01-24T11:43:22.6515052Z 3484e444e9cf: Layer already exists
2023-01-24T11:43:22.7036681Z 95a1c56e8ba5: Layer already exists
2023-01-24T11:43:22.7530828Z 67a4178b7d47: Layer already exists
2023-01-24T11:43:52.8144953Z Put "***/v2/dev/****/manifests/la***": dial tcp 13.73.149.68:443: i/o timeout
2023-01-24T11:43:52.8189085Z ##[error]Put "***/v2/dev/****/manifests/la***": dial tcp 13.73.149.68:443: i/o timeout
2023-01-24T11:43:52.8210921Z ##[error]The process '/usr/bin/docker' failed with exit code 1
2023-01-24T11:43:52.8237411Z ##[section]Finishing: publicapi push image
```

last 4 lines is generated by azure-devops-self-hosted-agent, no application (in this case task Docker@2)

agent v2.214.1

**Comment by superduperfajnylogin** [comment] 2023-01-25 09:04
```
grep IPC -R _diag/*
_diag/Agent_20230124-100235-utc.log:[2023-01-24 10:02:37Z INFO JobDispatcher] Set agent/worker IPC timeout to 300 seconds.
_diag/Agent_20230124-110620-utc.log:[2023-01-24 11:06:22Z INFO JobDispatcher] Set agent/worker IPC timeout to 300 seconds.
```

```
grep VSTS_AGENT_CHANNEL_TIMEOUT -R -A 2 _diag/*

_diag/Worker_20230125-090020-utc.log:    "VSTS_AGENT_CHANNEL_TIMEOUT": {
_diag/Worker_20230125-090020-utc.log-      "value": "300"
_diag/Worker_20230125-090020-utc.log-    },
--
_diag/Agent_20230124-100228-utc.log:[2023-01-24 10:02:30Z INFO EnvironmentCapabilitiesProvider] Adding 'VSTS_AGENT_CHANNEL_TIMEOUT': '300'
_diag/Agent_20230124-100228-utc.log-[2023-01-24 10:02:30Z INFO CapabilitiesBuilder] Which: 'android'
_diag/Agent_20230124-100228-utc.log-[2023-01-24 10:02:30Z INFO CapabilitiesBuilder] Not found.
--
_diag/pages/a07cd5a6-a673-4f28-b02f-bbe6de1b53f0_1.log:2023-01-25T09:00:22.6110030Z    Knob: AgentChannelTimeout = 300 Source: ${VSTS_AGENT_CHANNEL_TIMEOUT} 
_diag/pages/a07cd5a6-a673-4f28-b02f-bbe6de1b53f0_1.log-2023-01-25T09:00:22.6111852Z Finished checking job knob settings.
_diag/pages/a07cd5a6-a673-4f28-b02f-bbe6de1b53f0_1.log-2023-01-25T09:00:22.7731760Z Start tracking orphan processes.
--
```

**Comment by Roman-Shchukin** [comment] 2023-01-30 16:17
Hi @superduperfajnylogin. According to the logs, issue is related to Docker@2 task. Timeout message comes from Docker.  VSTS_AGENT_CHANNEL_TIMEOUT is responsible for the timeout of requests from Agent to Worker.  I would suggest to open a ticket on Docker@2 task in https://github.com/microsoft/azure-pipelines-tasks to get right eyes on it.

**Comment by superduperfajnylogin** [comment] 2023-01-30 16:51
@Roman-Shchukin no. That happens on every tasks. I have read code of Docker@2 plugin and it hasn't an any timeout parameter. In this case VSTS_AGENT_CHANNEL_TIMEOUT just not works that like should. 
There were few others issues with that same cause, but were closed by "inactivity"

**Comment by ismayilov-ismayil** [comment] 2023-02-15 07:25
Hi @superduperfajnylogin, thank you for the feedback. 
First of all, I want to mention that this "timeout" (VSTS_AGENT_CHANNEL_TIMEOUT) is for jobRequest sending from Listener to Worker, but not monitor task itself execution time.  The task timeout can be controlled by pipeline "timeout" parameter as shown [here](https://learn.microsoft.com/en-us/azure/devops/pipelines/process/phases?tabs=yaml&view=azure-devops#timeouts)

Anyway, I couldn't reproduce the issue, if you can help to reproduce issue we can go ahead. 
You can test it with simple pipeline yaml as shown below:
```  
- task: PowerShell@2
    inputs:
      targetType: 'inline'
      script: |
        Start-Sleep -Seconds 60
```

**Comment by ismayilov-ismayil** [comment] 2023-02-22 17:11
Hi @superduperfajnylogin, closing this one as external - feel free to ask any other questions or let us know if it's still relevant for you.

**Closed by ismayilov-ismayil** 2023-02-22 17:11 UTC
Labels: bug, Area: Agent
