### ISSUE TITLE
Agent 2.213.0 won't start (Azure Devops Server / Self Hosted agents on Windows)

### ISSUE THREAD

**Issue by actionthomas** [microsoft/azure-pipelines-agent#4036] opened 2022-11-07 11:24 UTC
After an upgrade to 2.213.0 on my Azure Devops Server 2020.1.1 installation, all my agents refuse to start anymore.
No file is created in their _diag folders.
Here is the error message I get in the Windows Application event log:
`
Description: A .NET Core application failed.
Application: Agent.Listener.exe
Path: E:\agent\bin\Agent.Listener.exe
Message: Error:
  An assembly specified in the application dependencies manifest (Agent.Listener.deps.json) was not found:
    package: 'BuildXL.Utilities', version: '0.1.0-20220517.1.1'
    path: 'runtimes/win-x64/native/x64/BuildXLNatives.pdb'
`

**Comment by DmitriiBobreshev** [comment] 2022-11-07 13:09
Hi @actionthomas! Thank you for reporting, we will check the issue and fix it

**Comment by DmitriiBobreshev** [comment] 2022-11-09 09:11
Hi @actionthomas we just released [agent 2.213.1](https://github.com/microsoft/azure-pipelines-agent/releases/tag/v2.213.1) where the problem is solved, could you please check that everything is fine now?

**Comment by actionthomas** [comment] 2022-11-09 10:26
Hi @DmitriiBobreshev 
Version 2.213.1 works in my environment, problem solved!

**Comment by DmitriiBobreshev** [comment] 2022-11-09 10:32
@actionthomas, thank's for participating! In this case, I'm closing the issue now, please feel free to reopen/create a new issue if you'll have some questions

**Closed by DmitriiBobreshev** 2022-11-09 10:32 UTC
Labels: bug, Area: Agent
