### ISSUE TITLE
Android build fails with NDK version error

### ISSUE THREAD

**Issue by casvel** [microsoft/azure-pipelines-agent#3220] opened 2021-01-21 02:31 UTC
## Agent Version and Platform
Version of your agent? 2.181.0

OS of the machine running the agent? Windows

## Azure DevOps Type and Version
dev.azure.com 

If dev.azure.com, what is your organization name? 
https://onedrive.visualstudio.com

## What's not working?
Build started failing with error:
> No version of NDK matched the requested version 22.0.7026061. Versions available locally: 21.3.6528147, 21.3.6528147

We were using the same NDK version for a little while and build was working fine until today. Was there any change in the agent that caused this issue? Is there another agent we can use that was the required NDK version?

## Agent and Worker's Diagnostic Logs
Not sure how to access the agent's folders to get the logs, but this is the log of the failed task
```
2021-01-21T01:39:25.7431928Z ##[section]Starting: Build armeabi-v7a's AAR
2021-01-21T01:39:25.7555615Z ==============================================================================
2021-01-21T01:39:25.7555923Z Task         : PowerShell
2021-01-21T01:39:25.7556162Z Description  : Run a PowerShell script on Linux, macOS, or Windows
2021-01-21T01:39:25.7556393Z Version      : 2.179.1
2021-01-21T01:39:25.7556629Z Author       : Microsoft Corporation
2021-01-21T01:39:25.7556911Z Help         : https://docs.microsoft.com/azure/devops/pipelines/tasks/utility/powershell
2021-01-21T01:39:25.7557272Z ==============================================================================
2021-01-21T01:39:27.4276665Z Generating script.
2021-01-21T01:39:27.5802462Z ========================== Starting Command Output ===========================
2021-01-21T01:39:27.6135783Z ##[command]"C:\windows\System32\WindowsPowerShell\v1.0\powershell.exe" -NoLogo -NoProfile -NonInteractive -ExecutionPolicy Unrestricted -Command ". 'D:\a\_temp\07571e73-65f3-47f0-a4ad-afc6d5a40548.ps1'"
2021-01-21T01:39:27.8962051Z D:\a\1\s\QtLiteAndroid-5-13-0\5.13.0
2021-01-21T01:39:37.8744901Z Downloading https://services.gradle.org/distributions/gradle-6.5-all.zip
2021-01-21T01:39:48.1594080Z .............10%..............20%..............30%..............40%..............50%..............60%..............70%..............80%..............90%..............100%
2021-01-21T01:40:40.2042752Z 
2021-01-21T01:40:40.2043203Z Welcome to Gradle 6.5!
2021-01-21T01:40:40.2043350Z 
2021-01-21T01:40:40.2045251Z Here are the highlights of this release:
2021-01-21T01:40:40.2048834Z  - Experimental file-system watching
2021-01-21T01:40:40.2049082Z  - Improved version ordering
2021-01-21T01:40:40.2049329Z  - New samples
2021-01-21T01:40:40.2049444Z 
2021-01-21T01:40:40.2049669Z For more details see https://docs.gradle.org/6.5/release-notes.html
2021-01-21T01:40:40.2049878Z 
2021-01-21T01:40:40.6079434Z Starting a Gradle Daemon (subsequent builds will be faster)
2021-01-21T01:40:49.3171316Z Configuration on demand is an incubating feature.
2021-01-21T01:41:19.1984480Z 
2021-01-21T01:41:19.1985136Z > Configure project :onedrivecore
2021-01-21T01:41:19.1985555Z WARNING: Support for ANDROID_NDK_HOME is deprecated and will be removed in the future. Use android.ndkVersion in build.gradle instead.
2021-01-21T01:41:19.1986116Z Support for ANDROID_NDK_HOME is deprecated and will be removed in the future. Use android.ndkVersion in build.gradle instead.
2021-01-21T01:41:19.2959836Z 
2021-01-21T01:41:19.2961169Z FAILURE: Build failed with an exception.
2021-01-21T01:41:19.2961519Z 
2021-01-21T01:41:19.2961827Z * What went wrong:
2021-01-21T01:41:19.2962201Z A problem occurred configuring project ':onedrivecore'.
2021-01-21T01:41:19.2962832Z > No version of NDK matched the requested version 22.0.7026061. Versions available locally: 21.3.6528147, 21.3.6528147
2021-01-21T01:41:19.2963258Z 
2021-01-21T01:41:19.2963591Z * Try:
2021-01-21T01:41:19.2969858Z Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.
2021-01-21T01:41:19.2970407Z 
2021-01-21T01:41:19.2970723Z * Get more help at https://help.gradle.org
2021-01-21T01:41:19.2970997Z 
2021-01-21T01:41:19.2971280Z BUILD FAILED in 1m 45s
2021-01-21T01:41:19.8587892Z ##[error]PowerShell exited with code '1'.
2021-01-21T01:41:24.9800772Z ##[section]Finishing: Build armeabi-v7a's AAR
```

**Comment by alexander-smolyakov** [comment] 2021-01-21 08:05
Hi @casvel, this issue related to the recent update of Windows images. 
Closing as duplicate of https://github.com/actions/virtual-environments/issues/2481

**Closed by alexander-smolyakov** 2021-01-21 08:05 UTC
