### ISSUE TITLE
Azure Devops Agent Log4J CVE Upgrade?

### ISSUE THREAD

**Issue by venkatesh-1986p** [microsoft/azure-pipelines-agent#3678] opened 2021-12-21 19:06 UTC
When we will get the log4j upgraded self hosted agent?
 
Log4J version should be 2.17.0

**Comment by alexander-smolyakov** [comment] 2021-12-22 05:05
Duplicate of #3658.

Please track progress and information about `log4j` in the following ticket:
- #3658

Closing it.

**Closed by alexander-smolyakov** 2021-12-22 05:05 UTC
Labels: Area: Agent, triage
