### ISSUE TITLE
Installing .net 6 is required for 5.0 projects and when installing this version the build agent on the same machine fails to build due to error

### ISSUE THREAD

**Issue by marcpopMSFT** [microsoft/azure-pipelines-agent#3532] opened 2021-07-22 18:26 UTC
This was copied from https://developercommunity.visualstudio.com/t/Installing-net-6-is-required-for-50-pr/1474894

When I have the latest version of the preview 2022 I cannot use the build agent on my machine for devops. I recieve the error below in the pipeline. If I on the other hand uninstall .net 6.0 the pipeline runs smoothly. The installer tells me I still have 5.0 installed but the project with .net 5.0 version cannot be opened and visual studio suggests that I should install some packages. After installation I end up in the same situation where the build agent pipeline fails meanwhile the project can be opened again.

"

##[error]Error: The process ‘C:\Program Files\dotnet\dotnet.exe’ failed with exit code 1

##[warning].NET 5 has some compatibility issues with older Nuget versions(<=5.7), so if you are using an older Nuget version(and not dotnet cli) to restore, then the dotnet cli commands (e.g. dotnet build) which rely on such restored packages might fail. To mitigate such error, you can either: (1) - Use dotnet cli to restore, (2) - Use Nuget version 5.8 to restore, (3) - Use global.json using an older sdk version(<=3) to build

Info: Azure Pipelines hosted agents have been updated and now contain .Net 5.x SDK/Runtime along with the older .Net Core version which are currently lts. Unless you have locked down a SDK version for your project(s), 5.x SDK might be picked up which might have breaking behavior as compared to previous versions. You can learn more about the breaking changes here: https://docs.microsoft.com/en-us/dotnet/core/tools/ and https://docs.microsoft.com/en-us/dotnet/core/compatibility/ . To learn about more such changes and troubleshoot, refer here: https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/build/dotnet-core-cli?view=azure-devops#troubleshooting

##[error]Dotnet command failed with non-zero exit code on the following projects : …

**Comment by tatyana-kostromskaya** [comment] 2021-09-15 08:34
Hello, @FahaoTang could you please provide error logs or repro steps for your issue?

**Comment by FahaoTang** [comment] 2021-09-17 01:28
> Hello, @FahaoTang could you please provide error logs or repro steps for your issue?

The steps to reproduce:

- Create a solution in VS2019
- Add an .NET 5 based website project
- Add an .NET 5 based (.NET worker) Azure Functions project using Blob trigger
- Submit the code to a Azure DevOps repo
- Create a standard build plan in Azure DevOps using .NET Core website template.
- Add task to use .NET SDK 3.1.x which is unfortunately required by .NET 5 based Azure V3 functions.
- Then run the build pipeline.
This has been working really well for me all the time since early this year and from last week the error started to occur.

I eventually resolved the issue by separate Azure Functions build into another pipeline and my website build pipeline only build the website project. It's working but the pipeline time has increased from 6-7 mins to almost 20 mins.

**Comment by EzzhevNikita** [comment] 2021-10-01 14:14
Hello @FahaoTang,
I have investigated this issue. And it looks like not related to build agent. Most likely it's related to installing of Visual Studio 2022 preview and .NET 6 preview or RC version. Update of some SDKs, components or tools installed on machine can require update of other software to keep compatibility between them.
I see in description of occurred error that root cause is non-compatible version of NuGet manager. Actual version of .NET require NuGet manager version 5.8 or newer.
Please try to update version of NuGet manager by one of following ways:
- command `nuget update -self` - in case NuGet manager was installed manually (https://docs.microsoft.com/en-us/nuget/install-nuget-client-tools)
- by modifying of installed Visual Studio instance, tab "Individual components", section "Code tools" (https://docs.microsoft.com/en-us/visualstudio/install/modify-visual-studio)

**Comment by FahaoTang** [comment] 2021-10-02 23:07
> Hello @FahaoTang, I have investigated this issue. And it looks like not related to build agent. Most likely it's related to installing of Visual Studio 2022 preview and .NET 6 preview or RC version. Update of some SDKs, components or tools installed on machine can require update of other software to keep compatibility between them. I see in description of occurred error that root cause is non-compatible version of NuGet manager. Actual version of .NET require NuGet manager version 5.8 or newer. Please try to update version of NuGet manager by one of following ways:
> 
> * command `nuget update -self` - in case NuGet manager was installed manually (https://docs.microsoft.com/en-us/nuget/install-nuget-client-tools)
> * by modifying of installed Visual Studio instance, tab "Individual components", section "Code tools" (https://docs.microsoft.com/en-us/visualstudio/install/modify-visual-studio)

Thanks for the suggestions.

**Comment by EzzhevNikita** [comment] 2021-10-04 07:58
@FahaoTang, please notify us about the results, and let us know if you need additional help.

**Comment by FahaoTang** [comment] 2021-10-04 08:29
> @FahaoTang, please notify us about the results, and let us know if you need additional help.

Hello, I am using Azure DevOps to build and the agent I used is windows-2022 with NuGet 5.11.0.10 already. 
https://github.com/actions/virtual-environments/blob/main/images/win/Windows2022-Readme.md

Note: my previous error was not caused by different dependent SDKs; it was because Node.js issue (times out I guess) when building in that agent. After I commented out the node.js actions in Publish step, my build has always been successful.  Apologies my original comment may have caused confusion.

**Comment by EzzhevNikita** [comment] 2021-10-04 10:13
@FahaoTang, thank you for this info.
Could you please confirm that your pipelines aren't affected by issue described in first message now? Please let us know if the ticket can be closed in this case.
If no, please share us details about environment used to repro this issue, YAML of affected pipeline and logs of failed run (with enabled "Enable system diagnostics").

**Comment by FahaoTang** [comment] 2021-10-04 10:31
I didn't raise the original issue thus would not be able to confirm that. I can confirm my previous issue was resolved (but not related to the solution as mine was mainly Node.js issue in my publish task).

**Comment by EzzhevNikita** [comment] 2021-10-04 10:57
This issue is not related to agent itself, most likely this is environment-specific. And there is no new repro.
So the ticket is closed.

**Closed by EzzhevNikita** 2021-10-04 10:57 UTC
Labels: bug, question, Area: Agent

**Comment by askshaik** [comment] 2022-09-09 15:20
I am also getting the same error and I followed the above-suggested step but error is still prevailing



For switch syntax, type "MSBuild -help"
##[error]Error: The process '/usr/bin/dotnet' failed with exit code 1
##[warning].NET 5 has some compatibility issues with older Nuget versions(<=5.7), so if you are using an older Nuget version(and not dotnet cli) to restore, then the dotnet cli commands (e.g. dotnet build) which rely on such restored packages might fail. To mitigate such error, you can either: (1) - Use dotnet cli to restore, (2) - Use Nuget version 5.8 to restore, (3) - Use global.json using an older sdk version(<=3) to build
Info: Azure Pipelines hosted agents have been updated and now contain .Net 5.x SDK/Runtime along with the older .Net Core version which are currently lts. Unless you have locked down a SDK version for your project(s), 5.x SDK might be picked up which might have breaking behavior as compared to previous versions. You can learn more about the breaking changes here: https://docs.microsoft.com/en-us/dotnet/core/tools/ and https://docs.microsoft.com/en-us/dotnet/core/compatibility/ . To learn about more such changes and troubleshoot, refer here: https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/build/dotnet-core-cli?view=azure-devops#troubleshooting
##[error]Dotnet command failed with non-zero exit code on the following projects : /home/vsts/work/1/s/Sempra.ADF.AzureFunctions/Sempra.ADF.AzureFunctions.csproj
Finishing: DotNetCoreCLI
