### ISSUE TITLE
[Question]: Error publishing pipeline artifact

### ISSUE THREAD

**Issue by Grubiopa** [microsoft/azure-pipelines-agent#4374] opened 2023-07-28 11:35 UTC
### Describe your question

This morning i start receiving this error:

Same commit and same pipeline as yesterday (yesterday works)
==============================================================================
Task         : Publish Pipeline Artifacts
Description  : Publish (upload) a file or directory as a named artifact for the current run
Version      : 1.199.0
Author       : Microsoft Corporation
Help         : https://docs.microsoft.com/azure/devops/pipelines/tasks/utility/publish-pipeline-artifact
==============================================================================
Artifact name input: drop
Uploading pipeline artifact from N:\Build\Windows0204\_work\1\a for build #3984402
Using default max parallelism.
Max dedup parallelism: 192
ApplicationInsightsTelemetrySender will correlate events with X-TFS-Session 9bd53c2a-4078-47e3-b565-18d2a3aabc24
DedupManifestArtifactClient will correlate http requests with X-TFS-Session 9bd53c2a-4078-47e3-b565-18d2a3aabc24
2 files processed.
Processed 2 files from N:\Build\Windows0204\_work\1\a successfully.
Uploading 2 files from directory N:\Build\Windows0204\_work\1\a.
Uploaded 0 out of 91,359,099 bytes.
....
ArtifactHttpRetryMessageHandler.SendAsync: https://vsblobprodsu6weu.vsblob.visualstudio.com/A42bbdafe-661d-444a-88fc-7b393527fdf0/_apis/dedup/nodes/E7625EB52744670B460F70B25F4590BAC8F823F481ED8EB2D10C16301B25D5FD02 attempt 1/6 failed with TimeoutException: 'The HTTP request timed out after 00:01:40.'
-----

ArtifactHttpRetryMessageHandler.SendAsync: https://vsblobprodsu6weu.vsblob.visualstudio.com/A42bbdafe-661d-444a-88fc-7b393527fdf0/_apis/dedup/nodes/E7625EB52744670B460F70B25F4590BAC8F823F481ED8EB2D10C16301B25D5FD02 attempt 6/6 throwing TimeoutException with AttemptCount 6, LastBackoff 70466ms
Upload failure. System.TimeoutException: The HTTP request timed out after 00:01:40.
 ---> System.Threading.Tasks.TaskCanceledException: The operation was canceled.
 ---> System.IO.IOException: Unable to read data from the transport connection: The I/O operation has been aborted because of either a thread exit or an application request..
 ---> System.Net.Sockets.SocketException (995): The I/O operation has been aborted because of either a thread exit or an application request.
   --- End of inner exception stack trace ---
   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.ThrowException(SocketError error, CancellationToken cancellationToken)
   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.System.Threading.Tasks.Sources.IValueTaskSource<System.Int32>.GetResult(Int16 token)
   at System.Net.Security.SslStream.EnsureFullTlsFrameAsync[TIOAdapter](TIOAdapter adapter)
   at System.Net.Security.SslStream.ReadAsyncInternal[TIOAdapter](TIOAdapter adapter, Memory`1 buffer)
   at System.Net.Http.HttpConnection.InitialFillAsync(Boolean async)
   at System.Net.Http.HttpConnection.SendAsyncCore(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   --- End of inner exception stack trace ---
   at System.Net.Http.HttpConnection.SendAsyncCore(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.AuthenticationHelper.SendWithNtAuthAsync(HttpRequestMessage request, Uri authUri, Boolean async, ICredentials credentials, Boolean isProxyAuth, HttpConnection connection, HttpConnectionPool connectionPool, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.SendWithVersionDetectionAndRetryAsync(HttpRequestMessage request, Boolean async, Boolean doRequestAuth, CancellationToken cancellationToken)
   at System.Net.Http.AuthenticationHelper.SendWithAuthAsync(HttpRequestMessage request, Uri authUri, Boolean async, ICredentials credentials, Boolean preAuthenticate, Boolean isProxyAuth, Boolean doRequestAuth, HttpConnectionPool pool, CancellationToken cancellationToken)
   at System.Net.Http.DecompressionHandler.SendAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)

### Versions

Agent name: 'Windows0204'
Agent machine name: 'Windows02'
Current agent version: '3.220.5'
Current image version: '1.0.23'
Agent running as: 'Windows02$'

### Environment type (Please select at least one enviroment where you face this issue)

- [X] Self-Hosted
- [ ] Microsoft Hosted
- [ ] VMSS Pool
- [ ] Container

### Azure DevOps Server type

dev.azure.com (formerly visualstudio.com)

**Comment by LiliaSabitova** [comment] 2023-07-31 10:48
Hi @Grubiopa, thank you for reporting this.
But the issue is not related to Agent, thus I'm closing the issue.
Please create an issue at [azure-pipelines-tasks](https://github.com/microsoft/azure-pipelines-tasks/issues) repo.

**Closed by LiliaSabitova** 2023-07-31 10:48 UTC
Labels: Area: Agent
