### ISSUE TITLE
Cannot configure negotiate auth with vsts agent 2.182.1

### ISSUE THREAD

**Issue by Vinzz** [microsoft/azure-pipelines-agent#3448] opened 2021-06-23 14:33 UTC
## Agent Version and Platform
Version of your agent? 2.182.1

OS of the machine running the agent? OSX

## Azure DevOps Type and Version
Azure DevOps Server on prem

If on-premises, which release? 2020.1

## What's not working?
Starting with this agent's version (we tried also 2.187.1), it seems that negotiate authentication method does not work

error is the following:

```
VS30063: You are not authorized to access <on prem url>
Échec de la connexion. Réessayez ou appuyez sur Ctrl+C pour quitter
```

PAT authent is OK though

Is that something you are aware of?

## Agent and Worker's Diagnostic Logs
Logs are located in the agent's `_diag` folder. The agent logs are prefixed with `Agent_` and the worker logs are prefixed with `Worker_`. All sensitive information should already be masked out, but please double-check before pasting here.

**Comment by anatolybolshakov** [comment] 2021-06-23 15:49
Hi @Vinzz could you please share your agent logs containing this error? You can also send them to my email - v-anbols@microsoft.com

**Comment by Vinzz** [comment] 2021-06-24 09:13
I just sent you an email with the logs

Oddly, the error is 401, but it works flawlessly with the same credentials in 2.181.2

Thanks

**Comment by anatolybolshakov** [comment] 2021-06-24 16:28
@Vinzz thanks! Does the 2.182.1 work for you with the negotiation authentication method on the same machine?

**Comment by Vinzz** [comment] 2021-06-25 08:08
@anatolybolshakov it used to work since years with the negotiate method (agents are configured with Ansible, so a mistake in typing is out of the way, I just made it interactively to provide quick logs), and was OK up to **2.181.2**

Starting with _2.182.1_, negotiate seems impossible on Mac (it still works on Windows though)

**Comment by anatolybolshakov** [comment] 2021-06-30 17:13
@Vinzz could you please try to set up AZP_AGENT_USE_LEGACY_HTTP environment variable as 'true' before agent configuration?

**Comment by Vinzz** [comment] 2021-07-02 08:47
yes I'll try that right away

**Comment by Vinzz** [comment] 2021-07-02 14:00
Well, that's no better I'm affraid

I'll send you the logs

`$ cat .env
AZP_AGENT_DOWNGRADE_DISABLED=true
AZP_AGENT_USE_LEGACY_HTTP=true
LANG=C.UTF-8`

`Enter server URL > https://myserver/tfs
Enter authentication type (press enter for PAT) > Negotiate
Enter user name > myserviceaccount
Enter password > ********************
Error reported in diagnostic logs. Please examine the log for more details.
    - /Users/forgemac/agenttestnego/_diag/Agent_20210702-135741-utc.log
VS30063: You are not authorized to access https://almnet-ng.orangeapplicationsforbusiness.com.
Failed to connect.  Try again or ctrl-c to quit`

**Comment by anatolybolshakov** [comment] 2021-07-02 14:46
@Vinzz could you please double-check that agent is picking up variable? You can check it by reviewing agent capabilities in DevOps - there should be AZP_AGENT_USE_LEGACY_HTTP with 'true' value.

**Comment by anatolybolshakov** [comment] 2021-07-09 15:36
@Vinzz do you have any updates?

**Comment by leonfibal** [comment] 2021-07-12 10:44
Hi,

It seems that I have the same problem. I try to run agent as environment resource and it does not work. Logs;

```
[2021-07-12 10:29:00Z INFO MessageListener] Loading Credentials
[2021-07-12 10:29:00Z INFO ConfigurationStore] HasCredentials()
[2021-07-12 10:29:00Z INFO ConfigurationStore] stored True
[2021-07-12 10:29:00Z INFO CredentialManager] GetCredentialProvider
[2021-07-12 10:29:00Z INFO CredentialManager] Creating type OAuth
[2021-07-12 10:29:00Z INFO CredentialManager] Creating credential type: OAuth
[2021-07-12 10:29:00Z INFO HostContext] Well known directory 'Bin': '/home/az_devops_agent/agent/bin'
[2021-07-12 10:29:00Z INFO HostContext] Well known directory 'Root': '/home/az_devops_agent/agent'
[2021-07-12 10:29:00Z INFO HostContext] Well known config file 'RSACredentials': '/home/az_devops_agent/agent/.credentials_rsaparams'
[2021-07-12 10:29:00Z INFO RSAFileKeyManager] Loading RSA key parameters from file /home/az_devops_agent/agent/.credentials_rsaparams
[2021-07-12 10:29:00Z INFO Terminal] WRITE LINE: Connecting to the server.
[2021-07-12 10:29:00Z INFO MessageListener] Attempt to create session.
[2021-07-12 10:29:00Z INFO MessageListener] Connecting to the Agent Server...
[2021-07-12 10:29:00Z INFO AgentServer] Establish connection with 100 seconds timeout.
[2021-07-12 10:29:00Z INFO VisualStudioServices] Starting operation Location.GetConnectionData
[2021-07-12 10:29:00Z WARN VisualStudioServices] Authentication failed with status code 401.

**Comment by Vinzz** [comment] 2021-07-27 14:29
Hi, back from vacation and yes I just re-checked:

```
$ cat .env
AZP_AGENT_DOWNGRADE_DISABLED=true
AZP_AGENT_USE_LEGACY_HTTP=true
```

**Comment by anatolybolshakov** [comment] 2021-07-30 16:04
@leonfibal @Vinzz do you see AZP_AGENT_USE_LEGACY_HTTP variable as detected agent capability also in Azure DevOps UI?

**Comment by leonfibal** [comment] 2021-08-02 06:35
@anatolybolshakov I can't check it. Nothing happens when i click on machine in UI. Also nothing happens in console or network tabs in my browser.

**Comment by Vinzz** [comment] 2021-08-02 09:41
@anatolybolshakov I can't check neither, as the enrolling stops before anything can be seen on the ADS UI

**Comment by anatolybolshakov** [comment] 2021-08-02 12:12
Yes, we were able to reproduce it, but switching to http legacy handler (by setting up AZP_AGENT_USE_LEGACY_HTTP environment variable to 'true') resolves this issue. This handler was switched by default to new SocketHttpHandler in [2.177.1 agent release](https://github.com/microsoft/azure-pipelines-agent/releases/tag/v2.177.1). 
We are currently investigating the reasons of this issue for new http handler.

**Comment by Vinzz** [comment] 2021-08-02 13:07
OK I'll retry from scratch with this Env Var enabled

**Comment by anatolybolshakov** [comment] 2021-08-03 18:06
@Vinzz @leonfibal this also seems to be related to the issue https://github.com/dotnet/runtime/issues/25827.
In general we are planning to update net core version for agent, but it could take some time to complete migration - please let us know if switch to legacy http handler helps to resolve the issue.

**Comment by Vinzz** [comment] 2021-08-04 12:10
Hi @anatolybolshakov  I can confirm that with agent version 2.182.1 and MacOS 11 Negotiate can't be used
No sweat though, we'll migrate to PAT and roll on

**Comment by leonfibal** [comment] 2021-08-04 14:09
@anatolybolshakov env AZP_AGENT_USE_LEGACY_HTTP=true is present. I installed an agent with version 2.189.0 and the error still occurs:
```
[2021-08-04 13:49:38Z INFO AgentServer] Establish connection with 100 seconds timeout.
[2021-08-04 13:49:38Z INFO VisualStudioServices] Starting operation Location.GetConnectionData
[2021-08-04 13:49:38Z WARN VisualStudioServices] Authentication failed with status code 401.

**Comment by anatolybolshakov** [comment] 2021-08-04 18:36
@leonfibal could you please also check that there is a server url specified as <server address>/DefaultCollection - for the agent while connecting to AzureDevOps Server?

**Comment by leonfibal** [comment] 2021-08-05 06:43
The only server url I found in logs is:
```
"ServerUrl": "https://dev.azure.com/***/",

**Comment by anatolybolshakov** [comment] 2021-08-05 15:21
@leonfibal this is the url you specify while configuring the agent.

**Comment by leonfibal** [comment] 2021-08-06 06:39
@anatolybolshakov this is the same url I specify while configuring the agent

**Comment by anatolybolshakov** [comment] 2021-08-09 16:32
@leonfibal your case looks different from original - could you please share the full logs to check? You can send them to my email - v-anbols@microsoft.com

**Comment by anatolybolshakov** [comment] 2021-08-18 14:06
Hey everyone!
Let me close this one since it seems to be resolved.
@leonfibal please feel free to create separate one for us to proceed on it further if you still have the issue.

**Closed by anatolybolshakov** 2021-08-18 14:06 UTC
Labels: bug, Area: Agent

**Comment by victorsarmi** [comment] 2022-07-14 19:02
> env AZP_AGENT_USE_LEGACY_HTTP=true

how i do this? in powershell or windows 10?
