### ISSUE TITLE
Publish artifact fails on last chunk

### ISSUE THREAD

**Issue by la-urre** [Microsoft/azure-pipelines-agent#1854] opened 2018-09-28 02:17 UTC
Not sure it's the right project to report this one...

## Have you tried trouble shooting?
Activated System.Debug, but I don't get more traces than I already have. 
I can't access my build agent right now to extract the diag logs, I will add the traces as soon as I can.

## Agent Version and Platform
vsts-agent-linux-x64-2.140.0

Ubuntu 16.04

## VSTS Type and Version
dev.azure.com

## What's not working?
My artifact won't upload. It always fails on the last chunk to upload with an internal error. See traces:

> 2018-09-27T23:45:22.6334079Z Start uploading file 'my_file.tar.gz' to server, chunk '369'.
> 2018-09-27T23:45:22.6354101Z Chunk '369' attempt '1' of file 'my_file.tar.gz' fail to send request to server. Error: Microsoft.VisualStudio.Services.WebApi.VssServiceResponseException: TF400898: An Internal Error Occurred. Activity Id: 12c64c76-cb45-445f-aa8d-fcb5ddccbee6. ---> System.IO.InvalidDataException: TF400898: An Internal Error Occurred. Activity Id: 12c64c76-cb45-445f-aa8d-fcb5ddccbee6.
>    --- End of inner exception stack trace ---
>    at Microsoft.VisualStudio.Services.WebApi.VssHttpClientBase.<HandleResponseAsync>d__53.MoveNext()
> --- End of stack trace from previous location where exception was thrown ---
>    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
>    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
>    at Microsoft.VisualStudio.Services.WebApi.VssHttpClientBase.<SendAsync>d__51.MoveNext()
> --- End of stack trace from previous location where exception was thrown ---
>    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
>    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
>    at Microsoft.VisualStudio.Services.FileContainer.Client.FileContainerHttpClient.<UploadFileAsync>d__16.MoveNext().
> 2018-09-27T23:45:22.6374007Z Backoff 9.76 seconds before attempt '2' chunk '369' of file 'my_file.tar.gz'.
> 2018-09-27T23:45:22.6389557Z Attempt '2' for uploading chunk '369' of file 'my_file.tar.gz'.
> 2018-09-27T23:45:22.6405163Z Generate new HttpRequest for uploading file 'my_file.tar.gz', chunk '369' of '369'.
> 2018-09-27T23:45:22.6420605Z Start uploading file 'my_file.tar.gz' to server, chunk '369'.
> 2018-09-27T23:45:22.6440247Z Chunk '369' attempt '2' of file 'my_file.tar.gz' fail to send request to server. Error: Microsoft.VisualStudio.Services.WebApi.VssServiceResponseException: TF400898: An Internal Error Occurred. Activity Id: 9ff7537a-5b52-46a7-b6cc-8728634230c6. ---> System.IO.InvalidDataException: TF400898: An Internal Error Occurred. Activity Id: 9ff7537a-5b52-46a7-b6cc-8728634230c6.
>    --- End of inner exception stack trace ---
>    at Microsoft.VisualStudio.Services.WebApi.VssHttpClientBase.<HandleResponseAsync>d__53.MoveNext()
> --- End of stack trace from previous location where exception was thrown ---
>    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
>    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
>    at Microsoft.VisualStudio.Services.WebApi.VssHttpClientBase.<SendAsync>d__51.MoveNext()
> --- End of stack trace from previous location where exception was thrown ---
>    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
>    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
>    at Microsoft.VisualStudio.Services.FileContainer.Client.FileContainerHttpClient.<UploadFileAsync>d__16.MoveNext().
> 2018-09-27T23:45:22.6460411Z Backoff 8.523 seconds before attempt '3' chunk '369' of file 'my_file.tar.gz'.
> 2018-09-27T23:45:22.6475990Z Attempt '3' for uploading chunk '369' of file 'my_file.tar.gz'.
> 2018-09-27T23:45:22.6491513Z Generate new HttpRequest for uploading file 'my_file.tar.gz', chunk '369' of '369'.
> 2018-09-27T23:45:22.6507248Z Start uploading file 'my_file.tar.gz' to server, chunk '369'.
> 2018-09-27T23:45:22.6522710Z 1 files failed to upload, retry these files after a minute.

## Agent and Worker's Diagnostic Logs
Can't access this at the moment, will provide the details soon

I think the internal error tells that something unexpected happened

Any thoughts on this ?

**Comment by laurre** [comment] 2018-10-01 12:50
Thanks for your response,

Where did you get that correspondance from ? Is there a page where I can find those codes meanings ? 

Please find attached the full log of the publish build artifact part of a new build attempt, it seems that this ActivityId changes over time. I also attached a yaml description of my build (even if i used the graphical UI to maintain it). And I also attached the file found in _diag. 

We recently migrated from VSTS to Azure DevOps, and this build was previously working well. 
I assume the problem lies in MS services or the agent, and I would be glad to help
[my_build.yaml.txt](https://github.com/Microsoft/azure-pipelines-agent/files/2433967/my_build.yaml.txt)
[publish_artifact.log](https://github.com/Microsoft/azure-pipelines-agent/files/2433968/publish_artifact.log)
[Worker_20181001-114014-utc.log](https://github.com/Microsoft/azure-pipelines-agent/files/2433969/Worker_20181001-114014-utc.log)

**Comment by TingluoHuang** [comment] 2018-10-01 14:53
@laurre can you try `tar zxvf my_artifact_folder/my_artifact.tar.gz` before the publish build artifact step? i want to make sure the file is not corrupted.
How frequently you are hitting this error, every build or once a while?

BTW, i got those error message from our backend telemetry, it's a server side exception.

**Comment by laurre** [comment] 2018-10-02 03:39
I get this error every build.

I managed to extract my tar.gz artifact, so the file is not corrupted. 

In the logs i sent in the previous message, the stack trace shows "HTTP Status: ServiceUnavailable" at some point (in Worker_20181001-114014-utc.log). Could you have a problem on the server side ?

Also I can find different ActivityIds in publish_artifact.log, like :

_f1f4e4cf-8a91-4cd7-b52e-ed31ac2f6828_
_01e91f8f-2c70-4a96-8ab4-46c4c6f42115_
_a61d4be2-34d7-49a0-88e2-cc1b8551ac4d_

Could you tell me if those ids mean something particular ?

Thanks

**Comment by TingluoHuang** [comment] 2018-10-02 12:14
@laurre do you mind share the tar.gz file with me? i want see whether i can repro the bug locally.

**Comment by TingluoHuang** [comment] 2018-10-08 18:26
@laurre ping... any chance you can share the repro tar.gz?

**Comment by laurre** [comment] 2018-10-09 10:56
I am sorry, but I can't disclose the tar.gz file. First of all it is ~1.5Gb, so not very handy to send, plus we do have sensitive data that we don't want to share.

Are there limits on the size of artefacts that we can push ?

I am just back on that topic today, so let me try to reproduce the problem with a smaller random archive.

**Comment by laurre** [comment] 2018-10-09 12:46
The very first error is : 'TF400898: An Internal Error Occurred. Activity Id: c091798a-1de1-41ad-94e2-dd77d63a7fb4.'

Could you please check what this ActivityId represent ?

**Comment by TingluoHuang** [comment] 2018-10-09 13:32
@laurre same error: `The magic number in GZip header is not correct. Make sure you are passing in a GZip stream.`

**Comment by laurre** [comment] 2018-10-09 14:00
I did `hexdump -C -n 10 ` on my file, and I got:

1f 8b 08 00 e7 a5 bc 5b 00 03

Seems normal to me...

**Comment by laurre** [comment] 2018-10-09 14:11
If I relaunch the build, i get a new message: "'TF400898: An Internal Error Occurred. Activity Id: 980833fb-51fe-4b34-b8b2-fbc73b8074a3."

Is it normal that the ActivityId changes everytime ?

**Comment by laurre** [comment] 2018-10-09 14:18
When reading the logs, I can see:

Begin chunking upload file 'galaxy-update/axiom2-update-1.0.34-SNAPSHOT.tar.gz', chunk size '4194304 Bytes', total chunks '370'. 

4194304 * 370 => 1551892480

When I check the size of my tar.gz file, I get 1564851948.

So the number of chunks seem too few, it should be 374 chunks...

How can that happen ?

**Comment by TingluoHuang** [comment] 2018-10-09 15:02
@laurre you will get new activity id on every single REST call to VSTS service.

interesting on the size/chunks, i will check the code on that part.

**Comment by TingluoHuang** [comment] 2018-10-09 15:08
`1551892480` is the size after gzip the original file.

**Comment by laurre** [comment] 2018-10-09 15:15
Ok so, what I want to upload is a tar.gz file (let's say this is my binary). So the agent will GZip this tar.gz file to upload it ? Am I able to see this file somewhere, to check if it is well-formed ?

**Comment by TingluoHuang** [comment] 2018-10-09 15:16
@laurre it suppose be a file in your %TEMP% dir, i think you can find it base on file size.

**Comment by laurre** [comment] 2018-10-09 16:06
I checked the temp folder all along the build but there was nothing but the
generated sh file calling my build script.

In all the traces i see, it's like the archive been pushed is my artefact
and not this artefact zipped in another archive

I don't know where to look for next

**Comment by TingluoHuang** [comment] 2018-10-09 16:09
@laurre the stream that goes on the wired is gzipped, which folder did you check, maybe try `/tmp` as well.

**Comment by laurre** [comment] 2018-10-10 07:42
Hey again!

In `/tmp`, i was able to find a `tmp6w2dsc.tmp` file, of size 1551817154 (which leads to 370 chunks as expected). The header of the file is the following:

1f 8b 08 00 00 00 00 00  00 03

It seems that the timestamp is not set. How is this file built ? How is the timestamp evaluated ? Is the error about the GZip error caused by this timestamp ?

When using the tar command (as for my artifact), the timestamp was correctly inserted (see comment above).

Waiting for your feedback

**Comment by laurre** [comment] 2018-10-11 09:36
Hi @TingluoHuang ! Do you have any idea about my previous post ?

This morning I noticed I was using a 'Publish build artifact' task, and i discovered a 'Publish pipeline artifact'. I tried to switch to that one, it seems better, except that once the build is completed, I can't download the artifact as I get a 404 error (maybe another issue somewhere else ?).

It's been 2 weeks that I am stuck with the artifact publication, and it is starting to become really annoying. It costs me time and energy each time I need to manually build my artifact, and it is error-prone...

**Comment by TingluoHuang** [comment] 2018-10-11 14:17
`1f 8b` is the magic header for gzip, are you upload some size file to the service? the file is created through standard dotnet api.

**Comment by TingluoHuang** [comment] 2018-10-11 14:29
@laurre do you have any proxy/firewall between your agent and the service.

**Comment by TingluoHuang** [comment] 2018-10-12 01:50
are you able to upload file to service at all? like a smaller file.

**Comment by laurre** [comment] 2018-10-12 07:48
Yes I tried with a smaller artifact without any problem...

**Comment by laurre** [comment] 2018-10-18 14:38
Ok

I still don't understand how the GZip error can happen. Is it only related to the magic number ? Because from what I can see it is correct. So the only reason I can see is if the beginning of the file is not transmitted correctly. 

In parellel i tried to upload the artifact with the 'Publish pipeline artifact' task, but i also have another problem, which is described here: 

https://developercommunity.visualstudio.com/content/problem/354982/404-error-when-trying-to-download-an-artifact.html

Let me check if I can send you the archive.

**Comment by TingluoHuang** [comment] 2018-10-22 19:31
The GZip is correct on your box, however, after transfer to the service through Internet, the service think it didn't get the first chunk it want. There is nothing wrong with you archive, some bug in Client/Internet/Service is causing the weird behavior.

If you are comfortable with sharing the archive with me, i will work with Microsoft Customer Support team to provide you instruction of uploading the content.

BTW, do you might share your ISP information with me? we had one case before that ISP is doing weird stuff that affect artifact upload.

**Comment by bryanmacfarlane** [comment] 2019-02-15 00:28
Closing as info not sent.  We can re-open with the requested info

**Closed by bryanmacfarlane** 2019-02-15 00:28 UTC
