### ISSUE TITLE
Having issue with registering a OnPrem server as a target in Deployment Group?

### ISSUE THREAD

**Issue by sanathkatakam** [microsoft/azure-pipelines-agent#3319] opened 2021-03-11 11:47 UTC
I have created a new deployment group on my Azure DevOps and then copied the PowerShell script with PAT and executed it on my OnPrem server. With out any errors it started connecting to the server but the problem is it is stuck at that point itself for a long time.

I have waited for almost 2 hrs however the PowerShell terminal still shows that connecting to server, below is the screenshot
![MicrosoftTeams-image](https://user-images.githubusercontent.com/45826815/110782532-47b55d80-828d-11eb-8b32-3f0e4b79e312.png)

and when I check my targets in the deployment group it shows the server but it's offline

**Comment by anatolybolshakov** [comment] 2021-03-11 13:48
Hi @sanathkatakam could you please share agent/worker logs? You can send them to my email: v-anbols@microsoft.com

**Comment by sanathkatakam** [comment] 2021-03-12 06:30
> Hi @sanathkatakam could you please share agent/worker logs? You can send them to my email: [v-anbols@microsoft.com](mailto:v-anbols@microsoft.com)

I just mailed you the logs @anatolybolshakov

**Comment by anatolybolshakov** [comment] 2021-03-17 08:56
@sanathkatakam I tried to reproduce this issue also, but with no luck - from agent logs I see that agent is waiting for response to 'Enter deployment group tags for agent'.
Could you please try to disable 'Insert Mode' and 'QuickEdit Mode' for Powershell - to double-check that powershell output hasn't been paused by clicking within a console?
You can find it Powershell context menu -> Properties -> Options like below:

![image](https://user-images.githubusercontent.com/8779682/111440817-c68c1980-8717-11eb-971e-2cfeca7225d0.png)

**Comment by sanathkatakam** [comment] 2021-03-17 11:24
@anatolybolshakov I have tried disabling 'Insert Mode' and 'QuickEdit Mode' for Powershell. but no change it still says 'connecting to the server'. and From the logs it seems that agent is waiting for an input regarding ‘Enter replace? (Y/N)’ but I don't see it on the terminal
![MicrosoftTeams-image copy](https://user-images.githubusercontent.com/45826815/111458660-b7b95d00-873f-11eb-90fb-2d3b0a81e3fa.png)

**Comment by anatolybolshakov** [comment] 2021-03-23 13:08
@sanathkatakam I still can't reproduce the issue... Looks like agent is waiting for input according to logs, but it doesn't show it in terminal.
Could you please try to run it via cmd?

**Comment by sanathkatakam** [comment] 2021-03-24 08:23
@anatolybolshakov We are connecting to our OnPrem environment using a Secure VPN. Only if we are logged into this VPN, then we are able to connect to the server.
Do you think this VPN might be the one, which is causing this problem?

**Comment by anatolybolshakov** [comment] 2021-03-30 08:25
@sanathkatakam I don't think it's related to VPN... At the moment it looks like some terminal issue

**Comment by sanathkatakam** [comment] 2021-03-31 10:22
@anatolybolshakov I have tried running it via cmd, but no luck

The cmd gets crashed and closes automatically, showing a pop up on right bottom of the screen saying that "Malware Detected"

**Comment by anatolybolshakov** [comment] 2021-04-01 10:04
@sanathkatakam this doesn't seem to be related to agent - do you have some antivirus enabled in your system? What is the origin of the popup?

**Comment by sanathkatakam** [comment] 2021-04-07 05:58
Yes, there is an antivirus running on this server. The running antivirus is only the origin of the pop up.

**Comment by anatolybolshakov** [comment] 2021-04-07 11:21
@sanathkatakam did you try to disable it?

**Comment by anatolybolshakov** [comment] 2021-04-13 17:21
@sanathkatakam this issue seems to be related to antivirus blocking agent - please make sure that there is an exception for agent process.
Let me close this at the moment since it doesn't seem to be related to the agent itself - please let us know if you have any futher questions.

**Closed by anatolybolshakov** 2021-04-13 17:21 UTC
Labels: Area: ABTT, Area: Agent, question
