### ISSUE TITLE
Inline Powershell script errors when running more than one Git command per script on hosted agent

### ISSUE THREAD

**Issue by MIchaelMainer** [microsoft/azure-pipelines-agent#2860] opened 2020-03-17 01:19 UTC
## Agent Version and Platform

Pool: Azure Pipelines
Image: windows-latest
Agent: Hosted Agent

Agent name: 'Azure Pipelines 2'
Agent machine name: 'fv-az123'
Current agent version: '2.165.2'
Current image version: '20200308.0'

## Azure DevOps Type and Version
dev.azure.com 

https://o365exchange.visualstudio.com/

## What's not working?
When I use the hosted agent, my inline scripts that use Git would fail on the second git command. When I would run this on my private agent I use for debugging, I would not see this issue. When I move the git commands to separate script tasks, they succeeded.

For example, if I ran the following inline script

```powershell
git checkout master | Write-Host
git checkout -b newBranchName | Write-Host
```
I'd get the following error message:

git.exe : Switched to a new branch 'newBranchName'
At D:\a\_temp\e8531e1f-537f-44fb-bc3c-c68a036cdb50.ps1:13 char:1
+ git checkout -b newBranchName | Write-Host
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (Switched to a n...ebuild/2578287':String) [], RemoteException
    + FullyQualifiedErrorId : NativeCommandError
 
##[error]PowerShell exited with code '1'.

**Comment by chenbojian** [comment] 2020-04-30 09:41
I am getting the similar issue. The [issue](https://github.com/microsoft/azure-pipelines-image-generation/issues/1436) said that it is a powershell 5.1.17763 bug. I also created a UserVoice [ticket](https://windowsserver.uservoice.com/forums/301869-powershell/suggestions/40295509-powershell-5-1-17763-1007-on-windows-2019-stops-wi)

I did some investigation on this issue and get some findings. I would like to share here.

1. The issue can be easily reproduced with [this].(https://gist.github.com/chenbojian/6fcb3a8c3bbe42cc2851a1eefe9f4324) pipeline snippet.
2. I created a branch with 2 failed tests to represent the issue. The tests shows the issue is not only happen for powershell.exe, but also for pwsh.exe (different behaviour). Please find the code [here](https://github.com/chenbojian/azure-pipelines-agent/blob/issue-2860/src/Test/L0/ProcessInvokerL0.cs#L372-L474).

I tried with Rider to run my tests, in debug mode if i change the `StartInfo.CreateNoWindow = false`, the test can pass.
In visual studio 2019, no matter what I changed, I will get a failed result.

**Comment by DK-Dennis** [comment] 2020-05-15 08:08
Not an inline script, but same issue here.
It seems that 'local' git commands work, but the first command after those, which involves origin, fails with the same error msg.

**Comment by miketimofeev** [comment] 2020-07-02 11:07
We're facing the same here https://github.com/actions/virtual-environments/issues/1151#issuecomment-652930819

**Comment by fniko** [comment] 2020-11-30 14:29
We are solving this issue adding the following on the top of every ps1 script which is doing any git operation
`$env:GIT_REDIRECT_STDERR = '2>&1'`

**Comment by tomaustin700** [comment] 2021-02-26 13:36
This still seems to be an issue, wasted a few hours today trying to figure out what was going on until I arrived here. Workaround by @fniko does work but this is less than ideal.

**Comment by vladislav-ryzhov** [comment] 2021-03-30 12:40
Hello @MIchaelMainer , @tomaustin700 !

Unfortunately, this issue doesn't apply to our area. But you can check your PowerShell task options and if failOnStderr input is set to true, you can change it to false and try. This input allows you to control the interpretation of the stderr output.
If you still have this issue after that change you can use workaround by @fniko and read more about it [here](https://github.com/git/git/blob/b2f55717c7f9b335b7ac2e3358b0498116b94a5d/Documentation/git.txt#L712-L723) .

**Comment by vladislav-ryzhov** [comment] 2021-03-30 12:41
Let me close this one since this is external issue. Please feel free to ask any further questions.

**Closed by vladislav-ryzhov** 2021-03-30 12:41 UTC
Labels: bug
