### ISSUE TITLE
Agent (v2.211.1) fails to connect to Azure DevOps

### ISSUE THREAD

**Issue by AdFizaine** [microsoft/azure-pipelines-agent#4035] opened 2022-11-07 08:50 UTC
## Agent Version and Platform
Agent version : v2.211.1
System : Debian 9
Node version : v16.18.0
Dotnet version : v3.1.424

## Azure DevOps Type and Version
dev.azure.com (cloud)

## What's not working?
After having run the shell "bin/installdependancies.sh", and having tried to configure without root, the connexion to Azure failed.

The PAT defined in the configuration is correct and has the correct rights for install agent.

![image](https://user-images.githubusercontent.com/117632077/200260715-6a1ff40b-a8dc-4fd8-8d8b-0fccc388add1.png)

![image](https://user-images.githubusercontent.com/117632077/200261360-1e232b62-06ba-4858-95e6-fd5138a5b3a6.png)

Once the config is done (with root rights), I can't start the "run.sh" :

![image](https://user-images.githubusercontent.com/117632077/200262169-d2135232-4dc9-47cc-a105-53242a4469d9.png)

I noticed that when I run shell as admin, it does not set the root rights on agent folders. 
However, when I do it from my CLI I can set the root rights.

**Comment by DmitriiBobreshev** [comment] 2022-11-07 10:51
Hi @AdFizaine, thank's for reporting, as I see on the first screen you didn't finish the config, after credentials should begin the pool configuration(see screen)
![image](https://user-images.githubusercontent.com/106314398/200288833-a97523dc-02ab-41fb-a3aa-3014e5acf6db.png)
Did you somehow send sigterm signal?

Also, the agent could not be configured under root rights, except in cases when you set variable [AGENT_ALLOW_RUNASROOT](https://github.dev/microsoft/azure-pipelines-agent/blob/master/src/Misc/layoutroot/config.sh#L6), but in the configuration of this case works as expected:
![image](https://user-images.githubusercontent.com/106314398/200291654-11016ab5-1dd9-4e5c-8ee3-fc8b54aa7c0d.png)

and in both cases, the agent should create configuration files (.agent and .credentials) with correct user permissions
![image](https://user-images.githubusercontent.com/106314398/200291905-bad5b09f-64c2-426e-86e2-109bc870e79b.png)

Could you please check if these files exist in your case and have the correct permissions?
Also, the agent doesn't set permissions on its files, except when the agent creates/modifies them. it is assumed that the agent will be configured under the appropriate user.

**Comment by AdFizaine** [comment] 2022-11-07 12:40
Hi @DmitriiBobreshev , I canceled the configuration because I was stuck after having entered my PAT.

Here you have my files and folders : 
![image](https://user-images.githubusercontent.com/117632077/200311461-c3e2db48-aa53-4a23-9e1d-689ca29577f6.png)

The file ".agent" is missing in my case.

**Comment by DmitriiBobreshev** [comment] 2022-11-07 13:28
@AdFizaine the file ".agent" contains information about server name, pool and creating [after](https://github.dev/microsoft/azure-pipelines-agent/blob/releases/2.211.1/src/Agent.Listener/Configuration/ConfigurationManager.cs#L456) ".credential" file. in your case probably something happened between these steps, could you please reconfigure the agent and attach the log file from the _diag folder if possible?

**Comment by AdFizaine** [comment] 2022-11-07 13:43
Here is my last log file :
[Agent_20221107-133740-utc.log](https://github.com/microsoft/azure-pipelines-agent/files/9952102/Agent_20221107-133740-utc.log)

**Comment by DmitriiBobreshev** [comment] 2022-11-07 15:03
Thank you for providing the log file. As I can see the process exited without any logs or smth. It possibly could be an error with directory access or smth. 
To be sure that this is the problem with the agent, could you please make a clean install from a non-root user?
Here is the one-line script to install the agent and run the config, if you don't mind, could you please run it and configure the agent?

`mkdir ~/azagent;cd ~/azagent;curl -fkSL -o vstsagent.tar.gz https://vstsagentpackage.azureedge.net/agent/2.211.1/vsts-agent-linux-x64-2.211.1.tar.gz;tar -zxvf vstsagent.tar.gz; ./config.sh`
 The script will create "azagent" folder in the user home directory, unpack it and run the config command.

**Comment by AdFizaine** [comment] 2022-11-07 15:21
I tried to make a clean install with a non-root user.

Here is my folders with rights : 
![image](https://user-images.githubusercontent.com/117632077/200346792-98df94eb-7702-4d94-a976-463e2a5d3e8d.png)

And here is my log file :
[Agent_20221107-151538-utc.log](https://github.com/microsoft/azure-pipelines-agent/files/9953000/Agent_20221107-151538-utc.log)

**Comment by DmitriiBobreshev** [comment] 2022-11-07 16:48
@AdFizaine, thank you for the fast response. Checked you steps on Debian 9 VM, everything sems fine, but in your case seems like first connection to server runs well, but after that second connection won't happen. Are you using some NAT/firewall? Maybe in this case something block the connection.

Also, you mentioned that under the root user, could you please explain it in more detailed how you partly managed to сonfigure an agent and successfully save credentials, and if it's possible attach log file with root config command.

**Comment by AdFizaine** [comment] 2022-11-08 15:49
I successfully configured the agent (v2.211.1) with a root user, and run it.

But when I start my pipelines below, the job do nothing.

Here is my pipeline :
[pipelinetest.txt](https://github.com/microsoft/azure-pipelines-agent/files/9962857/pipelinetest.txt)

Here is my CLI :
![image](https://user-images.githubusercontent.com/117632077/200610278-855db4fb-4889-4ecc-9b30-8dc06226a846.png)

And here is my Azure Interface :
![image](https://user-images.githubusercontent.com/117632077/200610526-e327f761-7f8d-413b-92ba-3bb28730e8f5.png)

**Comment by DmitriiBobreshev** [comment] 2022-11-08 16:43
@AdFizaine, the problem is the same as with configuring the agent, looks like dotnet 3.1 hanging with your set up for some reason, we're trying to find the reason, but could you try [pre-release version](https://github.com/microsoft/azure-pipelines-agent/releases/tag/v3.212.0) to make sure that the updating dotnet to 6 version will resolve the problem?

**Comment by DmitriiBobreshev** [comment] 2022-11-09 09:15
You're welcome, So in total it's the problem with .net 3.1, we continue investigating this. Thanks for participating! I'm closing the issue now. Please feel free to reopen it/create new tickets if you'll have some questions.

**Closed by DmitriiBobreshev** 2022-11-09 09:15 UTC
Labels: help wanted, question, Area: Agent
