### ISSUE TITLE
[BUG]: Network issues

### ISSUE THREAD

**Issue by devneutz** [microsoft/azure-pipelines-agent#4328] opened 2023-06-22 11:44 UTC
### What happened?

Since last week we are experience heavy delays when downloading secrets from key vaults or docker images from public repositories. Specifically we are encountering timeouts and connection resets on ms-hosted agents. The OS doesn't matter, it happens on all of them.

Testing access to the key vault via REST API using Postman showed an average response time of 23ms, whereas in the pipeline it takes up to multiple minutes.

### Versions

Agent version 3.220.5 / Ubuntu 2004, 2204 as well as windows-latest

### Environment type (Please select at least one enviroment where you face this issue)

- [ ] Self-Hosted
- [X] Microsoft Hosted
- [ ] VMSS Pool
- [ ] Container

### Azure DevOps Server type

dev.azure.com (formerly visualstudio.com)

### Relevant log output

```shell
##[debug]Encountered a retriable error:ECONNRESET. Message: read ECONNRESET.
```

**Comment by vmapetr** [comment] 2023-06-22 13:24
Hi @devneutz !
This actually looks like an ongoing Azure network outage is affecting your organization.
I tried to reproduce it by pulling some public docker images from ubuntu-latest, and Windows-latest with hosted agent 3.220.5, and everything works as expected.
I suggest you open a ticket on https://developercommunity.visualstudio.com/AzureDevOps, they can provide more context about the current outage.

**Comment by devneutz** [comment] 2023-06-22 13:42
Hi @vmapetr, thanks for your timely response! Apparently there was a network outage last week in our region but according to the official statements, it should be resolved.

I already tried opening a support request within the devcommunity as well as with our Azure support plan. Unfortunately they are unable to provide more context for days now.

Since you can't reproduce it though I guess it's not depending on the agent image.

**Comment by vmapetr** [comment] 2023-06-22 15:11
@devneutz Unfortunately, we also cannot provide any information about the outage status, since this is outside of our area.
I will close this ticket for now, but please feel free to reopen it in case if you have additional questions.

**Closed by vmapetr** 2023-06-22 15:11 UTC
Labels: bug, Area: Agent
