### ISSUE TITLE
System.NullReferenceException: Object reference not set to an instance of an object.    at Microsoft.VisualStudio.Services.Agent.Worker.JobRunner.UpdateMetadata(JobMetadataMessage message)

### ISSUE THREAD

**Issue by jessehouwing** [microsoft/azure-pipelines-agent#3596] opened 2021-11-02 17:57 UTC
## Agent Version and Platform
Version of your agent? 2.194.0

OS of the machine running the agent? Windows

## Azure DevOps Type and Version
dev.azure.com (formerly visualstudio.com) 

If dev.azure.com, what is your organization name? https://dev.azure.com/xpirit

## What's not working?
Please include error messages and screenshots.

![image](https://user-images.githubusercontent.com/4173387/139919760-d9681354-6aae-40fd-8ca6-48b2b80e463c.png)

## Agent and Worker's Diagnostic Logs

```
##[error]System.NullReferenceException: Object reference not set to an instance of an object.
   at Microsoft.VisualStudio.Services.Agent.Worker.JobRunner.UpdateMetadata(JobMetadataMessage message)
   at Microsoft.VisualStudio.Services.Agent.Worker.Worker.RunAsync(String pipeIn, String pipeOut)
   at Microsoft.VisualStudio.Services.Agent.Worker.Program.MainAsync(IHostContext context, String[] args)
Error reported in diagnostic logs. Please examine the log for more details.
    - C:\agents\2.194.0\_diag\Worker_20211102-172047-utc.log
```
[logs_17129.zip](https://github.com/microsoft/azure-pipelines-agent/files/7463014/logs_17129.zip)

**Comment by kuleshovilya** [comment] 2021-11-15 14:35
Hello @jessehouwing 
We are looking into the hosted agent logs at the minute, could you please answer couple of questions for us to understand the issue:
- Is this reoccurring error? 
- Can this error be reproduced?

**Comment by kuleshovilya** [comment] 2021-11-18 10:34
@jessehouwing Any update?

**Comment by jessehouwing** [comment] 2021-11-27 08:59
It happened once so far, so it's not a very common bug.

**Comment by kuleshovilya** [comment] 2021-12-02 14:11
@jessehouwing Thank you for answering. We went through the code and it seems like an issue with fetching info from the portal, but since this is handled from the agent side, we can't do much about it. We'll keep in mind that issue though, in case it will become more frequent. I'll be closing the ticket for now.

**Closed by kuleshovilya** 2021-12-02 14:11 UTC
Labels: bug, Area: Agent

**Comment by Ppkd2021** [comment] 2023-03-06 10:47
We are also facing above issue when we are trying to configure the agent on the Windows VM.

Error Message
**[2023-03-06 05:33:25Z INFO EnvironmentVMResourceConfigProvider] Environment virtual machine resource with name: 'csorcdbt24us', id: '31' has been added successfully.
[2023-03-06 05:33:25Z INFO CommandSettings] Flag 'unattended': 'True'
[2023-03-06 05:33:25Z ERR  Agent] System.NullReferenceException: Object reference not set to an instance of an object.
   at Microsoft.VisualStudio.Services.Agent.Listener.Configuration.EnvironmentVMResourceConfigProvider.AddAgentAsync(AgentSettings agentSettings, TaskAgent agent, CommandSettings command)
   at Microsoft.VisualStudio.Services.Agent.Listener.Configuration.ConfigurationManager.ConfigureAsync(CommandSettings command)
   at Microsoft.VisualStudio.Services.Agent.Listener.Agent.ExecuteCommand(CommandSettings command)
[2023-03-06 05:33:25Z ERR  Terminal] WRITE ERROR: Object reference not set to an instance of an object.**

We are running the below powershell script to automate this task which sometimes configure the agent properly and sometimes it is throwing the above error.

[CmdletBinding(PositionalBinding = $false)]
Param
(
    [Parameter(Mandatory = $true,HelpMessage="Name of the Environment")]
	[String]$EnvName,
    [Parameter(Mandatory = $false,HelpMessage="Name of the Environment")]
	[String]$agentName = $env:COMPUTERNAME,
    [Parameter(Mandatory = $false,HelpMessage="Path where agent should be installed")]
	[String]$agentInstallPath = "$env:SystemDrive\azagent",
    [Parameter(Mandatory = $false,HelpMessage="ADO url to the Organization")]
	[String]$baseUrl = $env:SYSTEM_TEAMFOUNDATIONCOLLECTIONURI, 
    [Parameter(Mandatory = $false,HelpMessage="PAT")]
	[String]$connectionToken = $env:SYSTEM_ACCESSTOKEN,
    [Parameter(Mandatory = $false,HelpMessage="Name of the project")]
	[String]$projectName = $env:SYSTEM_TEAMPROJECT,
    [Parameter(Mandatory = $true,HelpMessage="Environment resource Username")]
	[String]$EnvUser,
    [Parameter(Mandatory = $true,HelpMessage="Environment resource Password")]
	[String]$EnvPassword,
    [Parameter(Mandatory = $true,HelpMessage="Tags to the Environment resource")]
	[String]$tags

    
)

If(-NOT (Test-Path $agentInstallPath)){
    mkdir $agentInstallPath
}
Set-Location $agentInstallPath
                
for($i=1; $i -lt 100; $i++){
    $destFolder="A"+$i.ToString()
    if(-NOT (Test-Path ($destFolder))){
        mkdir $destFolder
        set-location $destFolder
        $agentName += $i
        break
    }
}
try
{
    $agentZip="$PWD\agent.zip"
    $DefaultProxy=[System.Net.WebRequest]::DefaultWebProxy
    $securityProtocol=@()
    $securityProtocol+=[Net.ServicePointManager]::SecurityProtocol
    $securityProtocol+=[Net.SecurityProtocolType]::Tls12
    [Net.ServicePointManager]::SecurityProtocol=$securityProtocol
    $WebClient=New-Object Net.WebClient
    $Uri='https://vstsagentpackage.azureedge.net/agent/2.211.1/vsts-agent-win-x64-2.211.1.zip'
    if($DefaultProxy -and (-not $DefaultProxy.IsBypassed($Uri))){$WebClient.Proxy= New-Object Net.WebProxy($DefaultProxy.GetProxy($Uri).OriginalString, $True)}
    $WebClient.DownloadFile($Uri, $agentZip)
    Add-Type -AssemblyName System.IO.Compression.FileSystem
    [System.IO.Compression.ZipFile]::ExtractToDirectory( $agentZip, "$PWD")

    .\config.cmd --unattended --environment --environmentname $EnvName --agent $agentName --acceptTeeEula --runasservice --windowsLogonAccount $EnvUser --windowsLogonPassword """$EnvPassword""" --work '_work' --url $baseUrl --projectname $projectName --auth PAT --token $connectionToken --addvirtualmachineresourcetags --virtualmachineresourcetags $tags
}
catch
{
    Write-Error "Error: $_" -ErrorAction Stop
}
