### ISSUE TITLE
Azure Pipeline installation failing with "The Extension failed to execute: Agent Configuration failed with error - Failed to Lock Service Database for"

### ISSUE THREAD

**Issue by elangelo** [microsoft/azure-pipelines-agent#3063] opened 2020-07-31 07:46 UTC
## Having issue with YAML?
no

## Having issue with Tasks?
no

## Having issue with software on Hosted Agent?
no

## Having generic issue with Azure-Pipelines/VSTS/TFS?
no

## Have you tried troubleshooting?
yes

## Agent Version and Platform
Version of your agent? 2.172.2 , Windows 2019

OS of the machine running the agent? Windows

## Azure DevOps Type and Version
dev.azure.com

If dev.azure.com, what is your organization name? https://dev.azure.com/marketingops or https://{organization}.visualstudio.com

## What's not working?
Installation of the deployment group agent is frequently failing
We regularly reinstall our CI servers  to keep up to date and get rid of any collected cruft. We install them in groups of 8 and recently this started to become very unreliable. Most of the time only 5 to 7 out of 8 would install succesfully. The failing agent always logs something of a lock failing

![image](https://user-images.githubusercontent.com/1935881/89012233-231a0000-d312-11ea-9960-5412c66480b0.png)

## Agent and Worker's Diagnostic Logs
Relevant installation log (authored to remove any sensitive information)
```[2020-07-31T07:11:32] Settings handler status to 'transitioning' (C:\Packages\Plugins\Microsoft.VisualStudio.Services.TeamServicesAgent\1.27.0.1\Status\0.status)

[2020-07-31T07:11:34] Reading config settings from file...
[2020-07-31T07:11:34] Reading handler settings from C:\Packages\Plugins\Microsoft.VisualStudio.Services.TeamServicesAgent\1.27.0.1\RuntimeSettings\0.settings
[2020-07-31T07:11:34] Found protected settings on Azure VM. Decrypting with certificate.
[2020-07-31T07:11:34] Read config settings from file. Now extracting inputs and doing basic validations.
[2020-07-31T07:11:34] Is Deployment Agent
[2020-07-31T07:11:35] Azure DevOps Organization Url: https://dev.azure.com/******
[2020-07-31T07:11:35] Team Project: ****
[2020-07-31T07:11:35] Deployment Group: ****-***-range-dg
[2020-07-31T07:11:35] Agent name from input settings: 
[2020-07-31T07:11:35] Tags: 
Name                           Value                                                                                   
----                           -----                                                                                   
Environment                    ***                                                                                     
Purpose                        ***
ReleaseId                      ***                                                                                    
Region                         ***                                                                                  
Stage                          ***                                                                                    
AppTier                        ***                                                                                     



[2020-07-31T07:11:35] Done reading config settings from file...
[2020-07-31T07:11:35] [Agent Settings Helper]: Check if any existing agent is running from C:\AzurePiplinesAgent_Extension
[2020-07-31T07:11:35] [Agent Settings Helper]: 		 Agent setting file path C:\AzurePiplinesAgent_Extension\.agent
[2020-07-31T07:11:35] [Agent Settings Helper]: 		 Agent setting file exist: False
[2020-07-31T07:11:35] [Agent Settings Helper]: Check if any existing agent is running from C:\VSTSAgent
[2020-07-31T07:11:35] [Agent Settings Helper]: 		 Agent setting file path C:\VSTSAgent\.agent
[2020-07-31T07:11:35] [Agent Settings Helper]: 		 Agent setting file exist: False
[2020-07-31T07:11:35] reading last sequence number LASTSEQNUM file C:\Packages\Plugins\Microsoft.VisualStudio.Services.TeamServicesAgent\1.27.0.1\bin\..\LASTSEQNUM
[2020-07-31T07:11:35] Sequence Number: 0
[2020-07-31T07:11:35] Testing whether disabled markup file exists: C:\AzurePiplinesAgent_Extension\EXTENSIONDISABLED
[2020-07-31T07:11:35] Disabled version settings file does not exist in the agent directory. Will continue with enable.
[2020-07-31T07:11:35] Disabled settings absent, continue with enable.
[2020-07-31T07:11:35] Get deployment group url - https://dev.azure.com/***/***/_apis/distributedtask/deploymentgroups?name=*****&api-version=5.0-preview.1
[2020-07-31T07:11:35] Get deploymentgroup retried 1 times
[2020-07-31T07:11:35] Validated that the deployment group "***-ci-***-range-dg" exists
[2020-07-31T07:11:35] Patch deployment group url - https://dev.azure.com/***/***/_apis/distributedtask/deploymentgroups/***?api-version=5.0-preview.1
[2020-07-31T07:11:35] Patch deploymentgroup retried 1 times
[2020-07-31T07:11:35] Validated that the user has "Manage" permissions on the deployment group ***-ci-***-range-dg
[2020-07-31T07:11:35] Done validating inputs...

[2020-07-31T07:11:35] [Agent Settings Helper]: Check if any existing agent is running from C:\AzurePiplinesAgent_Extension
[2020-07-31T07:11:35] [Agent Settings Helper]: 		 Agent setting file path C:\AzurePiplinesAgent_Extension\.agent
[2020-07-31T07:11:35] [Agent Settings Helper]: 		 Agent setting file exist: False
[2020-07-31T07:11:35] configuredAgentExists: False
[2020-07-31T07:11:35] agentConfigurationRequired: True

[2020-07-31T07:11:35] Invoking script to download and extract Deployment agent package...
[2020-07-31T07:11:35] Working folder for AzureDevOps agent: C:\AzurePiplinesAgent_Extension
[2020-07-31T07:11:35] Working folder does not exist. Creating it...
[2020-07-31T07:11:35] [Download]: Starting the DownloadDeploymentAgent script
[2020-07-31T07:11:35] [Download]: Get the url for downloading the agent
[2020-07-31T07:11:35] [Download]: 		 Get Agent PackageData using https://dev.azure.com/***/_apis/distributedtask/packages/agent/win-x64?top=1&api-version=3.0-preview.2
[2020-07-31T07:11:35] [Download]: 		 Invoke-rest call for packageData
[2020-07-31T07:11:35] Get packagedata retried 1 times
[2020-07-31T07:11:35] [Download]: Deployment Agent download url - https://vstsagentpackage.azureedge.net/agent/2.172.2/vsts-agent-win-x64-2.172.2.zip
[2020-07-31T07:11:35] [Download]: Get the target zip file path
[2020-07-31T07:11:35] [Download]: 		 Deployment agent will be downloaded at - C:\AzurePiplinesAgent_Extension\agent.zip
[2020-07-31T07:11:35] [Download]: Downloading deploymentAgent
[2020-07-31T07:11:35] [Download]: 		 Start DeploymentAgent download
[2020-07-31T07:11:36] retried 1 times
[2020-07-31T07:11:36] [Download]: 		 DeploymentAgent download done
[2020-07-31T07:11:36] [Download]: Done with DownloadDeploymentAgent script
[2020-07-31T07:12:00] C:\AzurePiplinesAgent_Extension\agent.zip is extracted to C:\AzurePiplinesAgent_Extension
[2020-07-31T07:12:00] Agent package downloaded and extracted

[2020-07-31T07:12:00] Configuring agent...
[2020-07-31T07:12:00] Agent name not provided as input
[2020-07-31T07:12:00] List targets url - https://dev.azure.com/***/***/_apis/distributedtask/deploymentgroups/***/targets?name=l17***988l8-DG&api-version=5.0-preview.1
[2020-07-31T07:12:00] List targets retried 1 times
[2020-07-31T07:12:00] Deployment group does not contain the target
[2020-07-31T07:12:00] Agent name: l17***988l8-DG
[2020-07-31T07:12:20] [Configuration]: ConfigProcess exit code: 
[2020-07-31T07:12:20] [Configuration]: 
  ___                      ______ _            _ _
 / _ \                     | ___ (_)          | (_)
/ /_\ \_____   _ _ __ ___  | |_/ /_ _ __   ___| |_ _ __   ___  ___
|  _  |_  / | | | '__/ _ \ |  __/| | '_ \ / _ \ | | '_ \ / _ \/ __|
| | | |/ /| |_| | | |  __/ | |   | | |_) |  __/ | | | | |  __/\__ \
\_| |_/___|\__,_|_|  \___| \_|   |_| .__/ \___|_|_|_| |_|\___||___/
                                   | |
        agent v2.172.2             |_|          (commit 1117823)


>> Connect:

Connecting to server ...

>> Register Agent:

Scanning for tool capabilities.
Connecting to the server.
Successfully added the agent
Testing agent connection.
2020-07-31 07:12:15Z: Settings Saved.
Granting file permissions to '***'.
Service vstsagent.***.***-***-ci-***-range-dg.***-DG successfully installed
Error reported in diagnostic logs. Please examine the log for more details.
    - C:\AzurePiplinesAgent_Extension\_diag\Agent_20200731-071204-utc.log

[2020-07-31T07:12:20] [Configuration]: Failed to Lock Service Database for Write

[2020-07-31T07:12:20] Error occured during Agent configuration
[2020-07-31T07:12:20] System.Management.Automation.RuntimeException: Agent Configuration failed with error - Failed to Lock Service Database for Write

[2020-07-31T07:12:20] [ERROR] Agent Configuration failed with error - Failed to Lock Service Database for Write

[2020-07-31T07:12:20] {
    "Exception":  {
                      "ErrorRecord":  {
                                          "Exception":  "System.Management.Automation.ParentContainsErrorRecordException: Agent Configuration failed with error - Failed to Lock Service Database for Write\r\n",
                                          "TargetObject":  null,
                                          "CategoryInfo":  "NotSpecified: (:) [], ParentContainsErrorRecordException",
                                          "FullyQualifiedErrorId":  "RuntimeException",
                                          "ErrorDetails":  null,
                                          "InvocationInfo":  null,
                                          "ScriptStackTrace":  null,
                                          "PipelineIterationInfo":  ""
                                      },
                      "WasThrownFromThrowStatement":  true,
                      "Message":  "Agent Configuration failed with error - Failed to Lock Service Database for Write\r\n",
                      "Data":  {

                               },
                      "InnerException":  null,
                      "TargetSite":  null,
                      "StackTrace":  null,
                      "HelpLink":  null,
                      "Source":  null,
                      "HResult":  -2146233087
                  },
    "TargetObject":  "Agent Configuration failed with error - Failed to Lock Service Database for Write\r\n",
    "CategoryInfo":  {
                         "Category":  14,
                         "Activity":  "",
                         "Reason":  "RuntimeException",
                         "TargetName":  "Agent Configuration failed with error - Failed to Lock Service Database for Write\r\n",
                         "TargetType":  "String"
                     },
    "FullyQualifiedErrorId":  "Agent Configuration failed with error - Failed to Lock Service Database for Write\r\n",
    "ErrorDetails":  null,
    "InvocationInfo":  {
                           "MyCommand":  null,
                           "BoundParameters":  {

                                               },
                           "UnboundArguments":  [

                                                ],
                           "ScriptLineNumber":  91,
                           "OffsetInLine":  9,
                           "HistoryId":  -1,
                           "ScriptName":  "C:\\Packages\\Plugins\\Microsoft.VisualStudio.Services.TeamServicesAgent\\1.27.0.1\\bin\\AgentConfigurationManager.ps1",
                           "Line":  "        throw \"Agent Configuration failed with error - $stderr\"\r\n",
                           "PositionMessage":  "At C:\\Packages\\Plugins\\Microsoft.VisualStudio.Services.TeamServicesAgent\\1.27.0.1\\bin\\AgentConfigurationManager.ps1:91 char:9\r\n+         throw \"Agent Configuration failed with error - $stderr\"\r\n+         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~",
                           "PSScriptRoot":  "C:\\Packages\\Plugins\\Microsoft.VisualStudio.Services.TeamServicesAgent\\1.27.0.1\\bin",
                           "PSCommandPath":  "C:\\Packages\\Plugins\\Microsoft.VisualStudio.Services.TeamServicesAgent\\1.27.0.1\\bin\\AgentConfigurationManager.ps1",
                           "InvocationName":  "",
                           "PipelineLength":  0,
                           "PipelinePosition":  0,
                           "ExpectingInput":  false,
                           "CommandOrigin":  1,
                           "DisplayScriptPosition":  null
                       },
    "ScriptStackTrace":  "at ConfigureAgent, C:\\Packages\\Plugins\\Microsoft.VisualStudio.Services.TeamServicesAgent\\1.27.0.1\\bin\\AgentConfigurationManager.ps1: line 91\r\nat Register-Agent, C:\\Packages\\Plugins\\Microsoft.VisualStudio.Services.TeamServicesAgent\\1.27.0.1\\bin\\enable.ps1: line 137\r\nat ConfigureAgentIfRequired, C:\\Packages\\Plugins\\Microsoft.VisualStudio.Services.TeamServicesAgent\\1.27.0.1\\bin\\enable.ps1: line 425\r\nat Enable, C:\\Packages\\Plugins\\Microsoft.VisualStudio.Services.TeamServicesAgent\\1.27.0.1\\bin\\enable.ps1: line 464\r\nat \u003cScriptBlock\u003e, C:\\Packages\\Plugins\\Microsoft.VisualStudio.Services.TeamServicesAgent\\1.27.0.1\\bin\\enable.ps1: line 481\r\nat \u003cScriptBlock\u003e, \u003cNo file\u003e: line 1",
    "PipelineIterationInfo":  [

                              ]
}
[2020-07-31T07:12:20] Settings handler status to 'error' (C:\Packages\Plugins\Microsoft.VisualStudio.Services.TeamServicesAgent\1.27.0.1\Status\0.status)
```

**Comment by melchiorAAB** [comment] 2021-02-22 07:54
Hello, any news/update on this issue? We have the same issue and googling it pointed to this page. Same issue that trying to install the DevOps Agent on a new VM crashes randomly (about 2 out of 10 times). Using the latest (v2.182.1) version of the Agent software.

**Comment by anatolybolshakov** [comment] 2021-02-24 13:47
Hi @elangelo @melchiorAAB do you run agent configuration in parallel for several agents on the same machine? 
Agent is trying to lock Service Database for SCManager, so it could probably be related to this.

**Comment by melchiorAAB** [comment] 2021-02-24 15:25
Hi @anatolybolshakov thanks for the reply. I am running 1 Agent per VM so nothing in parallel.

**Comment by anatolybolshakov** [comment] 2021-03-09 18:54
@melchiorAAB do you configure the agents manually by running the script from deployments group ui on every vm or is there some automation you use?

**Comment by anatolybolshakov** [comment] 2021-03-11 09:22
@melchiorAAB could you please share your script to take a look? I can't reproduce it by running it manually

**Comment by anatolybolshakov** [comment] 2021-03-23 11:52
Hi @melchiorAAB do you have any updates?

**Comment by anatolybolshakov** [comment] 2021-03-30 08:28
Hi @melchiorAAB I'm closing it at the moment since it's still not reproducible for us and some more info required for further investigation - please let us know if it's still actual for you, and if you are able to provide it.

**Closed by anatolybolshakov** 2021-03-30 08:28 UTC
Labels: Area: ABTT, Area: Agent, bug

**Comment by lonevvolf** [comment] 2021-10-05 12:06
@melchiorbc Were you ever able to resolve this?  We are instantiating VMs using an Azure Scale Set, and following the guide from MS to setup Azure DevOps agents on it.  We also see this type of error regularly - it prevents us from using our own scale set to run agents.

**Comment by melchiorbc** [comment] 2021-10-06 08:39
@lonevvolf the only thing we did lately is to manually delete the Azure DevOps Deployment Group and created a new one, after which the issue did not occur anymore. But since also Microsoft had already updated the version of the Deployment Agent software I do not know if it was the Deployment Group or a new version of the Agent software which did resolve the issue for us.
At least it did not fail for a long time now for us,

**Comment by pb185235** [comment] 2024-05-21 11:19
I am using the actions-runner version 2.316.1 but still getting the error saying "Failed to Lock Service Database for Write" while trying to register an Azure VM as github runner. Please suggest how do we fix it? I am trying to register VM as github runner through "az vm run-command" and using config.cmd.
