### ISSUE TITLE
Maintenance job fails to start "object or with var..."

### ISSUE THREAD

**Issue by FEnander** [microsoft/azure-pipelines-agent#3382] opened 2021-04-22 20:39 UTC
## Have you tried troubleshooting?
Yes did not find anything to help me understand/troubleshoot this problem

## Agent Version and Platform
2.185.1

OS of the machine running the agent? Windows 10

## Azure DevOps Type and Version
dev.azure.com 

https://icdev.visualstudio.com

## What's not working?
Three machines in the pool. Each machine has two agents. In total six agents running in the Default pool.
The scheduled Maintenance job fails to start. 

Error in maintenance log:
"Issues: 
   Object reference not set to an instance of an object."

## Agent and Worker's Diagnostic Logs
I don't know of any other logs that could help with this problem. Since I guess the logs in the different agent directories are agent specific.

**Comment by FEnander** [comment] 2021-04-22 20:40
[MaintenanceSummary.txt](https://github.com/microsoft/azure-pipelines-agent/files/6361102/MaintenanceSummary.txt)

**Comment by andy-mishechkin** [comment] 2021-04-23 09:03
Hello, @FEnander 
Did you mean scheduled job, which defined in pipeline or somewhere else ? May you provide the yaml or other definition of this job ?
Also you can find agent logs in the `\youagent\_diag` directory - may you provide agent and worker log of any of your agents, which correspond of error time ?

Thank you!

**Comment by anatolybolshakov** [comment] 2021-04-23 09:16
Hi @FEnander this is known issue related to DevOps side regression - which has already been fixed and is rolling out currently - please see developer community ticket for more info/status update - https://developercommunity.visualstudio.com/t/maintenance-job-fails:-Object-reference-/1400422
Let me close this one since it's already resolved and not related to the agent.

**Closed by anatolybolshakov** 2021-04-23 09:16 UTC
Labels: question
