### ISSUE TITLE
git lfs exit code 2 - build agent distributed with on-prem TFS 16.131.27701.1

### ISSUE THREAD

**Issue by jmkaleta** [Microsoft/azure-pipelines-agent#2079] opened 2019-01-31 14:17 UTC
## Have you tried troubleshooting?
Yes

## Agent Version and Platform
Version of your agent: `2.144.0`
Version of git: `git version 2.17.1.windows.2`
Version of git-lfs: `git-lfs/2.5.2 (GitHub; windows amd64; go 1.10.3; git 8e3c5c93)`

Running on Windows Server 2016

## Azure DevOps Type and Version
on-premise Microsoft Visual Studio Team Foundation Server Version 16.131.27701.1

## What's not working?
Issue has been reported to developercommunity:
https://developercommunity.visualstudio.com/content/problem/360087/question-whether-git-lfs-exit-code-2-has-been-fixe.html

The same kind of bug was reported here: https://github.com/Microsoft/azure-pipelines-agent/issues/1548 but the solution is not working in our case.

 ```
git -c http.https://...snip...extraheader="AUTHORIZATION: bearer ********" lfs fetch origin <sha1> 
fetch: Fetching reference <sha1>
fatal: could not read Username for 'http://tfs-fs.<domain>.com:8080': terminal prompts disabled
Downloading LFS objects:   0% (0/1), 0 B | 0 B/s 
batch response: Git credentials for https://...snip.../_git/snip.git/info/lfs not found.
Downloading LFS objects:   0% (0/229), 0 B | 0 B/s 
error: failed to fetch some objects from 'http://tfs-fs.<domain>.com:8080/...snip.../lfs'
git lfs logs last 
No logs to show
Git lfs fetch failed with exit code: 2. Git lfs logs returned with exit code: 0.
```

The issue also appears when using the newest versions of build agent `2.146.0` and git-lfs `git-lfs/2.6.1 (GitHub; windows amd64; go 1.11.1; git dc072c3e)`

At this moment we are using an workaround described in the link to created issue on developers community but we would not like to stick to this solution for a longer period of time.

## Agent and Worker's Diagnostic Logs
Above

## Questions
- How to further diagnose this issue?
- Is the fix going to be incorporated in the next releases?

**Comment by jmkaleta** [comment] 2019-01-31 14:52
@TingluoHuang
I made a mistake when I was shortening the log. The command is:
`git -c http.http://tfs-fs.<domain>.com:8080.extraheader="AUTHORIZATION: bearer ***" lfs fetch origin <sha1>`

I have also compared this command between the working solution with patch that we are using and the new build agent without the patch. In the working solution the command is: 
`git -c http.extraheader="AUTHORIZATION: bearer ********" lfs fetch origin refs/...`

So maybe this is the case with the https/https or not but as far as i know the command is set by build agent, tfs inner life. Those may be change or set?

**Comment by TingluoHuang** [comment] 2019-01-31 16:00
@jmkaleta what patch you are talking about? you build the agent from source code?
`http.http://tfs-fs.<domain>.com:8080.extraheader` is for security reason, so we only send token to server that match the url.

**Comment by jmkaleta** [comment] 2019-01-31 16:21
@TingluoHuang it's not exactly a patch rather a workaround that we implemented some time ago for the original problem: We took the agent binaries from:
https://github.com/Microsoft/vsts-agent/releases/download/v2.120.2/vsts-agent-win7-x64-2.120.2.zip with patched Agent.Worker.dll from https://github.com/Microsoft/vsts-agent/files/1249845/Agent.Worker.zip
The same approach is being done for each new build agent and it solves the issue.

**Comment by jmkaleta** [comment] 2019-02-04 11:55
@TingluoHuang, do you have any idea for a fix other than we are using? That would be nice to move to the newer versions of agents.

**Comment by dpurge** [comment] 2019-02-05 18:05
We are working with @jmkaleta in the same team and after some testing today, we think we understand what is happening. The comment from @TingluoHuang has pointed us in the right direction.

You need to know that in our environment TFS is accessible by two different domain names. I will call them `tfsname1` and `tfsname2`.

We wanted to replicate the error from command line. We have retrieved the value of $env:SYSTEM_ACCESSTOKEN and assigned it to a variable $ACCESSTOKEN.

Then we have tried to clone the repository, like so:
`git -c http.http://tfsname1.domain.com:8080.extraheader="AUTHORIZATION: bearer ${ACCESSTOKEN}" clone http://tfsname1.domain.com:8080/tfs/CollectionName/ProjectName/_git/RepoName RepoName`

This has successfully fetched data from git, but when it started to checkout files, it displayed prompt for credentials. When we have canceled the prompt, we got the error.

It looked like a failure during lfs smudge, so we have checked the contents of `.git/config` (edited):

```
[remote "origin"]
	url = http://tfsname1.domain.com:8080/tfs/CollectionName/ProjectName/_git/RepoName
[lfs "http://tfsname2:8080/tfs/CollectionName/ProjectName/_git/RepoName/info/lfs/objects/"]
	access = ntlm
```
Note that the URL of origin and the LFS url do not match. To confirm that this is likely to be the git-lfs missing credentials for the second name, we have tried to specify the same access token for both urls, like so:

`git -c http.http://tfsname1.domain.com:8080.extraheader="AUTHORIZATION: bearer ${ACCESSTOKEN}" -c http.http://tfsname2:8080.extraheader="AUTHORIZATION: bearer ${ACCESSTOKEN}" clone http://tfsname1.domain.com:8080/tfs/CollectionName/ProjectName/_git/RepoName RepoName`

This was successful. We've also tried some lfs commands inside the cloned repo, and everything worked fine.

Our test does not correspond 1-to-1 to what build agent is doing, but we find it very likely that the root cause of our issue is that `git-lfs` is using different domain name than what has been provided to  `git clone`.

We are not that familiar with inner workings of git-lfs yet, and we wonder how we can fix this for the build agent? We will continue to investigate, but any tips from you would be most welcome :-)

Could you confirm that if we have a server that can be accessed with two names, and developers use both names to add files to LFS, build agent would not be able to check out LFS-controlled files?

Locally it would not be a problem, as developer could save credentials in the credential store for both names.

I find it likely that there will be other people who will stumble onto this too, having the solution in the issue tracker would help them too.

Any comment from your side will be most appreciated :-)

**Comment by dpurge** [comment] 2019-02-05 18:45
We'll do this tomorrow morning, schedule the build and let you know whether this solves the problem. Thank you for the suggestion :-)

**Comment by dpurge** [comment] 2019-02-06 11:01
I've run the test by adding the `.lfsconfig` file in a branch and set `lfs.url` to the name matching the server url, but it did not have any effect.

I looked up the contents of `$(Build.SourcesDirectory)` after the build has already failed, and it did not yet contain checked out files, only the `.git` directory. Which means that `git-lfs` was called even before file checkout, therefore `.lfsconfig` could not affect its workings.

I have tried to confirm locally whether this setting would work by specifying the `-c lfs.url=...` on command line, and tried some variants of that setting, but it failed in all cases.

The only way that worked is providing authorization header for the alternative server name.

If we could configure additional git parameters in the "Get sources" phase and could reference build variables in these parameters, we could add the extra authorization header.

Or maybe build agent could have a configuration option to use default credentials (ie. build agent account) when git prompts for missing credentials.

Would you see one of the above as acceptable feature request? Personally I'd prefer "additional git parameters" :-)

At the moment the only workaround that comes to my mind is to add missing credentials to the credential store with DSC.

**Comment by TingluoHuang** [comment] 2019-02-07 13:30
@dpurge you can also don't use the built-in git-lfs download option, add a script task to download git-lfs object yourself.

**Comment by dpurge** [comment] 2019-02-07 19:52
We would like to avoid having to change all the build definitions and later maintain that added complexity. We plan to do some more research to understand how exactly `git-lfs` finds out the alternative name of the server - probably by reading its source code or running it under debugger. One thing we have not tried yet is configuring the build agent to use that alternative name that `git-lfs` prefers. We will find some solution, as we cannot use an outdated version of build agent forever. We do not spend 100% of our time on that, so it takes time.

**Comment by jmkaleta** [comment] 2019-02-08 12:17
As @dpurge wrote in a previous comment the tests were performed with a changed sever url for build agent witch is prefered by git-lfs and it works fine for git as well as git-lfs.
This approach solves our issue. Also It seems that having two different servers is not working without adding script step.

**Closed** 2019-02-15 00:26 UTC
