### ISSUE TITLE
git version does not match the agent documentation

### ISSUE THREAD

**Issue by asottile** [microsoft/azure-pipelines-agent#3932] opened 2022-08-07 16:04 UTC
details here: https://github.com/actions/virtual-environments/issues/6010

**Comment by LiliaSabitova** [comment] 2022-08-08 14:13
Hi @asottile!
In virtual environment there is a pre-installed git version 2.37.
But we also ship git with Agent to ensure performance. And its current version is 2.36.1.
That is done by design.

**Comment by asottile** [comment] 2022-08-08 14:57
the version that's on PATH should match the documentation is all I'm asking for

**Comment by LiliaSabitova** [comment] 2022-08-09 14:37
HI @asottile, the [documentation to which you're referring to](https://github.com/actions/runner-images/pull/5957) contains the version of git in the OS image and it's correct.
Agent runs with it's own version of git which is shipped along with Agent. So in your run, agent uses the version which is shipped with Agent itself.

**Comment by asottile** [comment] 2022-08-09 14:38
my tests should use what's documented in the documentation -- otherwise what's the point in documenting that version

**Comment by asottile** [comment] 2022-08-09 14:40
put yourself in the customer's shoes -- all the docs point to git 2.37 and I know that a bug is fixed in 2.37 and yet my tests are showing 2.36 behaviour.  the docs should match reality not some implementation detail that's never communicated

I think the actual bug is that the agent's tools are prepended to the PATH so they override what's documented.

**Comment by LiliaSabitova** [comment] 2022-08-09 15:28
When **agent** clones repo - it uses it's **own git** version, which is shipped with agent.
But **on the virtual machine** itself - the 37 version is installed. [This documentation](https://github.com/actions/runner-images/pull/5957) specifies only the version which is installed on the VM. It's not about the Аgent.

[Here](https://github.com/microsoft/azure-pipelines-agent/releases/tag/v2.206.1) you can find the information about the Agent's latest release. And the git version, which is specified there - is  2.36.1.

So, when you just run "git version" you get the version of git installed in Agent.
You can use git installed on the VM referring it's location, i.e.:
![image](https://user-images.githubusercontent.com/107196662/183691121-c3d66624-1ad9-48c7-a845-3f3f3a3418cf.png)

Moreover, we plan to update git shipped with Agent in the nearest future.

**Comment by asottile** [comment] 2022-08-09 15:37
ok I'll try and put it in a simplified example that you can understand because I feel like you're talking past me and not listening.

here's:

```yaml
    - script: python3 -c "import shutil, subprocess; print(shutil.which('git')); subprocess.call(('git', '--version'))"
```

and the output:

```
git version 2.36.1.windows.1
C:\agents\2.206.1\externals\git\cmd\git.EXE
```

https://asottile.visualstudio.com/asottile/_build/results?buildId=14089&view=logs&j=94d9d3b4-8e3d-5cdc-d6c7-40ce0e4fea69&t=7ebc23c2-0370-58cc-84d2-d538462b0cd3

**Comment by asottile** [comment] 2022-08-09 15:40
and if you google "software versions azure pipelines" it drops you on this page: https://docs.microsoft.com/en-us/azure/devops/pipelines/agents/hosted?view=azure-devops&tabs=yaml

that page says the windows 2022 installed software is listed here https://github.com/actions/runner-images/blob/main/images/win/Windows2022-Readme.md

and that says that git is version 2.37.1.windows.1 https://github.com/actions/runner-images/blame/main/images/win/Windows2022-Readme.md#L68

however the default `git` when run in azure pipelines **does not match the documented version**

**Comment by LiliaSabitova** [comment] 2022-08-09 16:21
Got your point, @asottile
The fact is that Agent overrides the git installed on VM.
Please try the solution described [here](https://docs.microsoft.com/en-us/azure/devops/pipelines/repos/pipeline-options-for-git?view=azure-devops&tabs=yaml#prefer-git-from-path).

And we will consider updating the documentation in a way to make it more obvious.

**Comment by asottile** [comment] 2022-08-09 16:29
> The Windows agent comes with its own copy of Git. If you prefer to supply your own Git rather than use the included copy, set System.PreferGitFromPath to true. This setting is always true on non-Windows agents.

this should be the default -- anything else is confusing and surprising

**Comment by asottile** [comment] 2022-08-11 20:59
hmmm it's also inconsistent -- for `script` and `powershell` I get `2.36.1.windows.1` -- for `bash` I get `2.37.1.windows.1`

https://asottile.visualstudio.com/asottile/_build/results?buildId=14094&view=logs&j=94d9d3b4-8e3d-5cdc-d6c7-40ce0e4fea69&t=7ebc23c2-0370-58cc-84d2-d538462b0cd3

**Comment by JimSuplizio** [comment] 2022-09-13 18:59
I have a similar issue to @asottile because of the git versions. I'm also running into a similar problem because of the git version. I'm expecting the default git version to be [what's documented](https://github.com/actions/runner-images/blob/main/images/win/Windows2019-Readme.md) for the runner image which is supposed to be 2.37.3.windows.1. There were some default changes in git behavior with sparse-checkout that happened in 2.37.0 which we'd had to make changes to. As a result, I've had to add a git min version check into some code which only fails on Windows. Mac and Linux images both seem to be fine with their git versions being what's documented.

We shouldn't need to do any additional steps to have the versions that are documented be the default versions.

**Comment by asottile** [comment] 2023-03-13 03:03
I'm no longer blocked by this -- but I don't think the root cause has been addressed

**Comment by kirill-ivlev** [comment] 2023-08-01 09:47
To conclude everything in this thread:
1. Agent uses their own git (https://github.com/microsoft/azure-pipelines-agent/blob/5a8ed1f93ee0ca0057af1c98254248401b45e282/src/Misc/externals.sh#L15)
2. Version of git in the agent is not always matched git shipped with specific images
3. If you need to use a specific version inside your pipelines you can use any other external git installed on the system.

This behavior is expected, and the reason for this - is to avoid breaking changes in case some of such changes will be introduced in images.

Closing this one, since no further action is required.

**Closed by kirill-ivlev** 2023-08-01 09:47 UTC
Labels: Area: Agent

**Comment by asottile** [comment] 2023-08-01 12:43
I switched off azure pipelines entirely because of this

your conclusion is not correct did you read my comment above? it's only sometimes as you describe depending on which script type you use

and worst of all it doesn't match the documented versions
