### ISSUE TITLE
Auto Logon private agents encounter Access Denied when updating themselves (Auto logon configuration did grant runas user permission)

### ISSUE THREAD

**Issue by mqlkmd** [Microsoft/azure-pipelines-agent#1795] opened 2018-08-29 08:58 UTC
## Agent Version and Platform
Version of your agent? 2.133.3

OS of the machine running the agent? Windows

## VSTS Type and Version
VisualStudio.com

If VisualStudio.com, what is your account name? http://kmddk.visualstudio.com

## What's not working?
On august 27th at 14:33 UTC+2 our 20 private agents in a pool were suddenly cancelling active jobs and tried to update themselves. 
However, that failed for all of them with an access denied for the “config.cmd” file.
The agents are on version 2.133.3 and tried to update to 2.138.4.

I don’t know why they suddenly tried to update the entire pool  while we we actively using them?

Afterwards, I tried to manually force an Agent Update for another pool and they failed with the same Access Denied exception.

## Agent and Worker's Diagnostic Logs
[2018-08-27 14:32:35Z INFO MessageListener] Message '909' received from session 'a1b0a260-e8fd-4bff-9af9-528265e448b3'.
[2018-08-27 14:32:35Z INFO Agent] Refresh message received, kick-off selfupdate background process.
[2018-08-27 14:32:35Z INFO SelfUpdater] Version '2.138.4' of 'agent' package available in server.
[2018-08-27 14:32:35Z INFO SelfUpdater] Current running agent version is 2.133.3
[2018-08-27 14:32:35Z INFO SelfUpdater] An update is available.
[2018-08-27 14:32:35Z INFO Terminal] WRITE LINE: Agent update in progress, do not shutdown agent.
[2018-08-27 14:32:35Z INFO Terminal] WRITE LINE: Downloading 2.138.4 agent
[2018-08-27 14:32:35Z INFO SelfUpdater] Save latest agent into C:\Dev01\_work\_update\agent.zip.
[2018-08-27 14:33:12Z INFO SelfUpdater] Finished getting latest agent package at: C:\Dev01\_work\_update.
[2018-08-27 14:33:12Z INFO HostContext] Well known directory 'Bin': 'C:\Dev01\bin'
[2018-08-27 14:33:12Z INFO HostContext] Well known directory 'Root': 'C:\Dev01'
[2018-08-27 14:33:12Z INFO SelfUpdater] Copy C:\Dev01\_work\_update\bin to C:\Dev01\bin.2.138.4.
[2018-08-27 14:33:13Z INFO HostContext] Well known directory 'Bin': 'C:\Dev01\bin'
[2018-08-27 14:33:13Z INFO HostContext] Well known directory 'Root': 'C:\Dev01'
[2018-08-27 14:33:13Z INFO SelfUpdater] Copy C:\Dev01\_work\_update\externals to C:\Dev01\externals.2.138.4.
[2018-08-27 14:33:13Z INFO SelfUpdater] Copy any remaining .sh/.cmd files into agent root.
[2018-08-27 14:33:13Z INFO HostContext] Well known directory 'Bin': 'C:\Dev01\bin'
[2018-08-27 14:33:13Z INFO HostContext] Well known directory 'Root': 'C:\Dev01'
[2018-08-27 14:33:13Z INFO JobDispatcher] Shutting down JobDispatcher. Make sure all WorkerDispatcher has finished.
[2018-08-27 14:33:13Z INFO JobDispatcher] Ensure WorkerDispather for job 92831fee-08ec-4bb2-955a-7c0be8aec0ea run to finish, cancel any running job.
[2018-08-27 14:33:13Z INFO JobDispatcher] Send job cancellation message to worker for job 92831fee-08ec-4bb2-955a-7c0be8aec0ea.
[2018-08-27 14:33:15Z INFO ProcessInvoker] Finished process with exit code 103, and elapsed time 00:10:51.2942279.
[2018-08-27 14:33:15Z INFO JobDispatcher] finish job request for job 92831fee-08ec-4bb2-955a-7c0be8aec0ea with result: Canceled
[2018-08-27 14:33:15Z INFO Terminal] WRITE LINE: 2018-08-27 14:33:15Z: Job Release completed with result: Canceled
[2018-08-27 14:33:15Z INFO JobDispatcher] Stop renew job request for job 92831fee-08ec-4bb2-955a-7c0be8aec0ea.
[2018-08-27 14:33:15Z INFO JobDispatcher] job renew has been canceled, stop renew job request 207681.
[2018-08-27 14:33:15Z INFO JobNotification] Entering JobCompleted Notification
[2018-08-27 14:33:15Z ERR  Terminal] WRITE ERROR: An error occurred: Access to the path 'C:\Dev01\config.cmd' is denied.
[2018-08-27 14:33:15Z ERR  AgentProcess] System.UnauthorizedAccessException: Access to the path 'C:\Dev01\config.cmd' is denied.
   at System.IO.Win32FileSystem.CopyFile(String sourceFullPath, String destFullPath, Boolean overwrite)
   at System.IO.File.InternalCopy(String sourceFileName, String destFileName, Boolean overwrite)
   at System.IO.FileInfo.CopyTo(String destFileName, Boolean overwrite)
   at Microsoft.VisualStudio.Services.Agent.Listener.SelfUpdater.<DownloadLatestAgent>d__10.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.VisualStudio.Services.Agent.Listener.SelfUpdater.<SelfUpdate>d__8.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.VisualStudio.Services.Agent.Listener.Agent.<RunAsync>d__8.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Microsoft.VisualStudio.Services.Agent.Listener.Agent.<RunAsync>d__8.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Microsoft.VisualStudio.Services.Agent.Listener.Agent.<RunAsync>d__8.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.VisualStudio.Services.Agent.Listener.Agent.<ExecuteCommand>d__5.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.VisualStudio.Services.Agent.Listener.Program.<MainAsync>d__1.MoveNext()

**Comment by TingluoHuang** [comment] 2018-08-30 18:47
@mqlkmd the agent update failure caused the running job cancellation, i will fix that part. can you help me check why the agent's run as user doesn't have permission to those file? is your agent running as service? which user it use and what permission that use has on those file?

**Comment by mqlkmd** [comment] 2018-08-31 06:31
The agent is running with an interactive user to support running ui tests.
We have used the DevTest Lab Artifact "VSTS Build Agent" to deploy and configure the agent. The user running the agent is a normal user member of the "Users" security group.
The "Users" security group has "read and execute" rights to the file.
![vstsagentpermission](https://user-images.githubusercontent.com/28260900/44896327-28bad580-acf8-11e8-8323-50932b09e14d.png)

**Comment by TingluoHuang** [comment] 2018-09-05 21:39
@mqlkmd i need to figure out what is the DevTest Lab Artifact doing, normally the agent's run as user should have all permission on the agent root folder and the agent working folder. looks like the permission is not set correctly.

**Comment by mqlkmd** [comment] 2018-09-06 07:08
@TingluoHuang thanks for looking into this. Let me know if you need log files or other info.

**Comment by TingluoHuang** [comment] 2018-09-06 13:49
@mqlkmd i think i know where the problem is, looks like when the agent is configured with auto logon, it did grant folder permission for the auto logon user.
Can you share any of your agent's log file to confirm your agent is running in auto logon mode?

**Comment by mqlkmd** [comment] 2018-09-06 14:05
@TingluoHuang , yes we are using auto logon, since we use devtest labs to auto shutdown/start the agents.
The log says:
[2018-08-27 14:58:34Z INFO Agent] Set agent startup type - AutoStartup
[2018-08-27 14:58:34Z INFO ConfigurationStore] IsAutoLogonConfigured: True
[2018-08-27 14:58:34Z INFO Agent] Autologon is configured on the machine, dumping all the autologon related registry settings

Do you need more info from the logs?

**Comment by TingluoHuang** [comment] 2018-09-06 14:08
@mqlkmd thanks. i need to figure out who should fix the problem, i will change the title of this issue, thanks for sharing this information

**Comment by TingluoHuang** [comment] 2019-04-08 14:18
the agent with fix has released, however since the permission setup is part of config flow, to fix existing agents you need to reconfig them with latest agent release. i am going to close this issue for now, please reopen if needed.

**Closed by TingluoHuang** 2019-04-08 14:18 UTC
Labels: Area: Core, Area: Test, bug
