### ISSUE TITLE
Azure doesn't respect .lfsconfig files

### ISSUE THREAD

**Issue by tannergooding** [microsoft/azure-pipelines-agent#2503] opened 2019-10-11 02:28 UTC
### Issue

Git LFS supports configuring an alternate `lfsurl` via the `.lfsconfig` file: https://github.com/git-lfs/git-lfs/wiki/Tutorial#lfs-url.

However, it appears as though Azure Pipelines ignores this file and instead force configures the `lfsurl` according to the LFS "default":
```
##[section]Starting: Checkout
==============================================================================
Task         : Get sources
Description  : Get sources from a repository. Supports Git, TfsVC, and SVN repositories.
Version      : 1.0.0
Author       : Microsoft
Help         : [More Information](https://go.microsoft.com/fwlink/?LinkId=798199)
==============================================================================
Syncing repository: terrafx/terrafx (GitHub)
Prepending Path environment variable with directory containing 'git.exe'.
##[command]git version
git version 2.21.0.windows.1
##[command]git lfs version
git-lfs/1.5.2 (GitHub; windows amd64; go 1.7.3; git 547a06aa)
##[command]git init "D:\a\1\s"
Initialized empty Git repository in D:/a/1/s/.git/
##[command]git remote add origin https://github.com/terrafx/terrafx
##[command]git config gc.auto 0
##[command]git config --get-all http.https://github.com/terrafx/terrafx.extraheader
##[command]git config --get-all http.proxy
##[command]git lfs install --local
Updated pre-push hook.
Git LFS initialized.
##[command]git config remote.origin.lfsurl https://github.com/terrafx/terrafx.git/info/lfs
##[command]git config remote.origin.lfspushurl https://github.com/terrafx/terrafx.git/info/lfs
##[command]git -c http.extraheader="AUTHORIZATION: basic ***" fetch --force --tags --prune --progress --no-recurse-submodules origin +refs/heads/*:refs/remotes/origin/* +refs/pull/48/merge:refs/remotes/pull/48/merge
```

### Expected Behavior

Azure Pipelines should respect the `.lfsconfig` file, if one exists, and use it for configuring the URL artifacts should be pulled from.

### Build Link

The TerraFX repo is public and an example CI failure can be seen here: https://dev.azure.com/tagoo/terrafx/_build/results?buildId=332

**Comment by tannergooding** [comment] 2019-10-11 03:18
It's also worth noting that the `git-lfs` version on the Microsoft hosted Windows agents is incredibly outdated: `git-lfs/1.5.2 (GitHub; windows amd64; go 1.7.3; git 547a06aa)`. The current version is `2.8.0` and is what both Linux and macOS agents are using.

**Comment by jtpetty** [comment] 2020-01-28 17:49
This issue appears to be a duplicate of #2598. Closing this issue and tracking it there.

**Closed by jtpetty** 2020-01-28 17:49 UTC
