### ISSUE TITLE
Binaries for 2.160.0 appear to have been modified since initial release

### ISSUE THREAD

**Issue by flcdrg** [microsoft/azure-pipelines-agent#2609] opened 2019-11-15 23:08 UTC
I maintain the [Chocolatey package for the Azure Pipelines Agent](https://chocolatey.org/packages/azure-pipelines-agent). I've had a [report from a user](2.16.0) that the binaries downloaded by 2.160.0 are now failing to match the checksums that were calculated when the package was first released (which would have been calculated from the files when they were first made available to download).

These checksums were validated automatically on the 9th of November, but now are different.

Here's the relevant lines that currently exist in the `chocolateyInstall.ps1` script:
```powershell
$url = 'https://vstsagentpackage.azureedge.net/agent/2.160.0/vsts-agent-win-x86-2.160.0.zip'
$url64 = 'https://vstsagentpackage.azureedge.net/agent/2.160.0/vsts-agent-win-x64-2.160.0.zip'
$checksum = 'e789ae8960350dd54b5e3ffd0df44f9e59c352c347e53858fff1dcf965d1f6c2'
$checksum64 = '341f90cd7a4f9bc1a84b783e4d48e510063657ba182f1bd4c0be868144cd7d52'
```

I've just manually downloaded the agent from https://vstsagentpackage.azureedge.net/agent/2.160.0/vsts-agent-win-x64-2.160.0.zip and can confirm the SHA256 hash is now `2784EBD56A7DE5ED769FDCB0027DBD8D3E6488773B59FFCFC69007A0B1B80421`

Why has the file been modified since it was first published?

**Comment by nycnewman** [comment] 2019-11-16 23:20
Seeing same issue on our VSTS agent builds. Choco is failing to install with wrong hash error.

**Comment by nycnewman** [comment] 2019-11-17 14:15
@flcdrg Note that there is a new version out 2.160.1 but agree that understanding change would be good.

**Comment by flcdrg** [comment] 2019-11-17 23:36
Yeah - though 2.160.1 is just a preview release

**Comment by nycnewman** [comment] 2019-11-18 13:59
Microsoft Team - is there an official location for the official has of your binaries? Can;t see this published anywhere so unclear with this change whether it is an official change or not.

**Comment by damccorm** [comment] 2019-11-18 16:30
Hey all, just investigated this on our end. Sorry for the red flag this may have caused - the issue was caused by an engineer on our end accidentally publishing a release before updating the agent version number from 2.160.0 to 2.160.1. This led to the storage blob getting updated, but it failed to publish to GitHub (because the version is the only unique ID used for GitHub publishes).

2.160.1 should be rolling out the rest of the way in the next couple of hours, sorry for any inconvenience here.

**Comment by nycnewman** [comment] 2019-11-18 16:32
Any chance you can revert released artifacts to correct version for consistency?

**Comment by damccorm** [comment] 2019-11-18 19:10
I will look into fixing that. Concerning the larger point, 2.160.1 has been fully released, that's the version I'd recommend using from now on.

**Comment by damccorm** [comment] 2020-01-28 14:38
Closing since this has been fixed

**Closed by damccorm** 2020-01-28 14:38 UTC
