### ISSUE TITLE
Ubuntu 19.04 no usable libssl

### ISSUE THREAD

**Issue by bigpod98** [microsoft/azure-pipelines-agent#2349] opened 2019-07-12 16:02 UTC
Hello

I want to install a self hosted agent onto a ubuntu 19.04(non lts) but after entering PAT i get error no usable libssl i installed everything that has libssl from 19.04 repos.

**Comment by flashdog** [comment] 2019-07-21 20:18
Hello,

I had the same problem after upgrading from unbuntu 18.xx to unbuntu 19.04.
The problem is in the dotnet SDK 2.1 and it is fixed in SDK 2.2.

I made a local clone for testing and upgrade from dotnet sdk2.1 to sdk2.2. That works for me.
Should I make a pull request?

**Comment by bigpod98** [comment] 2019-07-22 01:07
I dont realy know, maybe

**Comment by hiaws** [comment] 2019-08-01 11:01
I can confirm this issue. 

Installing 'libopenssl1_0_0' can fix this. However we're running SLES 15.1, on which openlibssl1_1 can only be installled if we enable legacy modules. (Currently we're not allowed to enable those modules)

**Comment by juliobbv** [comment] 2019-08-05 18:48
Hi @bigpod98, can you try out installing this (unofficial) package and try configuring the agent? Let me know if it works for you.

https://1drv.ms/u/s!AkcNSSfO5EWU203yB2etXzMwZOsU?e=byfT3H

This package was built against the latest LTS version of the .NET Core 2.1 SDK, which contains the fix to use OpenSSL 1.1 if the dependency is available. I'll open a PR to bump up the version upon confirmation.

**Comment by bigpod98** [comment] 2019-08-05 20:10
@juliobbv Configuration went without a problem installed in a ubuntu 19.04 after configuration it connected ok to my azure dev ops

**Comment by juliobbv** [comment] 2019-08-06 18:15
Hi @bigpod98,

I checked the official .NET Core 2.1 Linux OS documentation, which indicates they do not support Debian 10. We'll need to wait for the final version of .NET Core 3.0 to be released in order for us to start offering agent support.

In the meantime, you can run the agent [in any of the supported OS from this list.](https://github.com/microsoft/azure-pipelines-agent/blob/895826cee93db70a99264a01f116fbec6b499793/docs/start/envlinux.md)

**Closed by juliobbv** 2019-08-06 18:15 UTC
