### ISSUE TITLE
Automatic updates of pipelines agent fail (./bin/Agent.Listener: No such file or directory)

### ISSUE THREAD

**Issue by jimaxe** [microsoft/azure-pipelines-agent#3575] opened 2021-10-22 15:38 UTC
## Agent Version and Platform
2.193.0

## OS of the machine running the agent
Linux (Ubuntu 18.04)

## Azure DevOps Type and Version
dev.azure.com

## What's not working?
We are running a self-hosted agent in Docker on Linux that has been configured according to the instructions at [Run a self-hosted agent in Docker](https://docs.microsoft.com/en-us/azure/devops/pipelines/agents/docker?view=azure-devops). 

Spinning up a container from an image built locally with the latest version of the Azure Pipelines Agent always works. However, when an automatic update from Azure DevOps is triggered after a new version is available, the error message `./bin/Agent.Listener: No such file or directory.` is always logged, and the container exits.  Building a new image with the latest version locally and spinning up a container works fine. The issue has only been replicated through automatic updates of the Azure Pipelines Agent triggered via Azure DevOps. We have tested turning off automatic updates for pipeline agents, but Azure DevOps release pipelines sometimes require the latest version of the Azure Pipelines Agent to run. This has been an issue for over six months and has not been isolated to a single version of Azure Pipelines Agent.

Please find the logs below:
```
agent1_1  | 1. Configuring Azure Pipelines agent...
agent1_1  | 
agent1_1  |   ___                      ______ _            _ _
agent1_1  |  / _ \                     | ___ (_)          | (_)
agent1_1  | / /_\ \_____   _ _ __ ___  | |_/ /_ _ __   ___| |_ _ __   ___  ___
agent1_1  | |  _  |_  / | | | '__/ _ \ |  __/| | '_ \ / _ \ | | '_ \ / _ \/ __|
agent1_1  | | | | |/ /| |_| | | |  __/ | |   | | |_) |  __/ | | | | |  __/\__ \
agent1_1  | \_| |_/___|\__,_|_|  \___| \_|   |_| .__/ \___|_|_|_| |_|\___||___/
agent1_1  |                                    | |
agent1_1  |         agent v2.193.0             |_|          (commit ce84ce9)
agent1_1  | 
agent1_1  | 
agent1_1  | >> End User License Agreements:
agent1_1  | 
agent1_1  | Building sources from a TFVC repository requires accepting the Team Explorer Everywhere End User License Agreement. This step is not required for building sources from Git repositories.
agent1_1  | 
agent1_1  | A copy of the Team Explorer Everywhere license agreement can be found at:
agent1_1  |   /azp/externals/tee/license.html
agent1_1  | 
agent1_1  | 
agent1_1  | >> Connect:
agent1_1  | 
agent1_1  | Connecting to server ...
agent1_1  | 
agent1_1  | >> Register Agent:
agent1_1  | 
agent1_1  | Scanning for tool capabilities.
agent1_1  | Connecting to the server.
agent1_1  | Successfully replaced the agent
agent1_1  | Testing agent connection.
agent1_1  | 2021-10-22 15:02:03Z: Settings Saved.
agent1_1  | 2. Running Azure Pipelines agent...
agent1_1  | Scanning for tool capabilities.
agent1_1  | Connecting to the server.
agent1_1  | 2021-10-22 15:02:05Z: Listening for Jobs
agent1_1  | Agent update in progress, do not shutdown agent.
agent1_1  | Downloading 2.193.1 agent
agent1_1  | Waiting for current job finish running.
agent1_1  | Generate and execute update script.
agent1_1  | Agent will exit shortly for update, should back online within 10 seconds.
agent1_1  | Cleanup. Removing Azure Pipelines agent...
agent1_1  | Removing agent from the server
agent1_1  | Connecting to server ...
agent1_1  | Succeeded: Removing agent from the server
agent1_1  | Removing .credentials
agent1_1  | Succeeded: Removing .credentials
agent1_1  | Removing .agent
agent1_1  | Succeeded: Removing .agent
agent1_1  | 1. Configuring Azure Pipelines agent...
agent1_1  | ./config.sh: line 85: ./bin/Agent.Listener: No such file or directory
```
Any tips or suggestions would be much appreciated.

Thank you!

**Comment by alexander-smolyakov** [comment] 2021-12-07 12:29
It seems this issue is a duplicate of this one #3587. @jimaxe would you mind tracking the progress on this issue in the following ticket?
- #3587

I'm closing this issue since it is a duplicate. @jimaxe if you have any concerns about it, please feel free to let us know and we will reopen the ticket.

**Closed by alexander-smolyakov** 2021-12-07 12:29 UTC
Labels: bug, Area: Agent
