### ISSUE TITLE
[Bug] Unable to process command setvariable with isoutput true

### ISSUE THREAD

**Issue by jamesdoran** [microsoft/azure-pipelines-agent#3284] opened 2021-02-25 04:39 UTC
## Have you tried troubleshooting?
I've followed the instructions for using `setvariable` [here for 2017.3](https://docs.microsoft.com/en-us/azure/devops/pipelines/scripts/logging-commands?view=tfs-2017&tabs=powershell#setvariable-initialize-or-modify-the-value-of-a-variable).

## Agent Version and Platform
Agent: `2.122.1`
Platform: `Windows Server 2012 R2`

## Azure DevOps Type and Version
On-premises TFS `2017.3`

## What's not working?
I'm getting an `unable to process command` error when setting a variable.

To isolate the issue, I created a simple build with an inline script powershell task that runs:
``` powershell
Write-Host "##vso[task.setvariable variable=outputSauce;isoutput=true]canned goods"
``` 
This example was taken from [Microsoft Docs](https://docs.microsoft.com/en-us/azure/devops/pipelines/scripts/logging-commands?view=tfs-2017&tabs=powershell#setvariable-initialize-or-modify-the-value-of-a-variable) for `2017.3`.

### Error output
``` 
2021-02-25T04:17:58.7393396Z ##[error]Unable to process command '##vso[task.setvariable variable=outputSauce;isoutput=true]canned goods' successfully. Please reference documentation (http://go.microsoft.com/fwlink/?LinkId=817296)
2021-02-25T04:17:58.7393396Z ##[error]Value cannot be null.
Parameter name: RefName
```

Until this morning, we were running build agent `2.112.1` and the above worked fine. After the upgrade to `2.122.1` (the version that ships with TFS `2017.3`, we're now seeing this issue.

If I omit `;isoutput=true`, it works fine. According to the docs above, this option should be supported though. We're using `gitversion` which uses the same output format to share variables once the tool has been run, so I can't change the code without forking.

## Agent and Worker's Diagnostic Logs
Logs attached. Sensitive data replace with `---`
[WorkerLog.txt](https://github.com/microsoft/azure-pipelines-agent/files/6040505/WorkerLog.txt)
[AgentLog.txt](https://github.com/microsoft/azure-pipelines-agent/files/6040506/AgentLog.txt)

**Comment by anatolybolshakov** [comment] 2021-03-05 17:15
Hi @jamesdoran I can't reproduce it with last agent version - could you please try to use last agent version?

**Comment by jamesdoran** [comment] 2021-03-05 20:24
Hi @anatolybolshakov, thanks for getting back to me. This is the version that shipped with 2017.3. When I attempted to use the conditional build steps added in this version of TFS, the build agent automatically updated to this version: 2.122.1

when you say “the last agent version” are you talking about a manual installation? If so, so I get the latest version from [here](https://github.com/microsoft/azure-pipelines-agent/releases)? Are they backwards compatible with on premises 2017.3?

**Comment by jamesdoran** [comment] 2021-03-11 00:13
Thanks @anatolybolshakov. This morning I performed a successful manual upgrade to `2.183.1`.

Unfortunately the issue is still apparent...

```
******************************************************************************
Starting: Build
******************************************************************************
******************************************************************************
Starting: Initialize job
******************************************************************************
Agent name: '---'
Agent machine name: '---'
Current agent version: '2.183.1'
Agent running as: '---'
Prepare build directory.
Set build variables.
Download all required tasks.
Checking job knob settings.
   Knob: DisableAgentDowngrade = true Source: ${AZP_AGENT_DOWNGRADE_DISABLED} 
Finished checking job knob settings.
Plugin: 'Test Result Parser plugin' is running in background.
Plugin: 'Test File Publisher plugin' is running in background.
Start tracking orphan processes.
******************************************************************************
Finishing: Initialize job
******************************************************************************
******************************************************************************
Starting: Get sources
******************************************************************************
==============================================================================
Task         : Get sources
Description  : Get sources from a repository. Supports Git, TfsVC, and SVN repositories.
Version      : 1.0.0
Author       : Microsoft
Help         : [More Information](https://go.microsoft.com/fwlink/?LinkId=798199)
==============================================================================
-- Removed for brevity ---
******************************************************************************
Finishing: Get sources
******************************************************************************
******************************************************************************
Starting: test set variable
******************************************************************************
==============================================================================
Task         : PowerShell
Description  : Run a PowerShell script
Version      : 1.2.3
Author       : Microsoft Corporation
Help         : [More Information](https://go.microsoft.com/fwlink/?LinkID=613736)
==============================================================================
. 'C:\Users\---\AppData\Local\Temp\f344439e-a490-47d2-b2fe-a0ef1f9a19a4.ps1'
Unable to process command '##vso[task.setvariable variable=outputSauce;isoutput=true]canned goods' successfully. Please reference documentation (http://go.microsoft.com/fwlink/?LinkId=817296)
Value cannot be null. (Parameter 'RefName')
******************************************************************************
Finishing: test set variable
******************************************************************************
```

Any ideas on what I can check next please?

**Comment by jamesdoran** [comment] 2021-03-21 22:04
Just following this up to see if there's anything else I can provide to help diagnose this issue please?

**Comment by jamesdoran** [comment] 2021-07-26 06:06
Just checking in to ask if this is still on your radar and if there are any plans to fix? 

More than happy to provide more info if required.

**Comment by EzzhevNikita** [comment] 2021-12-15 10:09
Hey @jamesdoran, I've managed to reproduce this problem, and we have rechecked, TFS 2017.3 is not supporting the 'isoutput' property for setvariable command. We will update related docs to address this issue, thank you for the information about this problem.

**Comment by jamesdoran** [comment] 2021-12-18 00:53
That's excellent you've been able to reproduce. Thanks for the update.

**Comment by golubev-ivan** [comment] 2021-12-20 08:09
Hi @jamesdoran, We've updated documentation related to the support of isoutput flag in different Azure DevOps Server versions, we removed information about output variables from TFS 2017 docs. Thank you again for the provided information. Let me close this since the docs have already been updated.

**Closed by golubev-ivan** 2021-12-20 08:09 UTC
Labels: bug, question, documentation, Area: ABTT, Area: Agent
