### ISSUE TITLE
Install fails on Ubuntu 22.04

### ISSUE THREAD

**Issue by rwb196884** [microsoft/azure-pipelines-agent#4107] opened 2023-01-03 11:10 UTC
```
imac51:~/azure-agent$ lsb_release -a
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 22.04.1 LTS
Release:        22.04
Codename:       jammy
imac51:~/azure-agent$ uname -a
Linux imac51 5.15.0-56-generic #62-Ubuntu SMP Tue Nov 22 19:54:14 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux
imac51:~/azure-agent$ ./config.sh

  ___                      ______ _            _ _
 / _ \                     | ___ (_)          | (_)
/ /_\ \_____   _ _ __ ___  | |_/ /_ _ __   ___| |_ _ __   ___  ___
|  _  |_  / | | | '__/ _ \ |  __/| | '_ \ / _ \ | | '_ \ / _ \/ __|
| | | |/ /| |_| | | |  __/ | |   | | |_) |  __/ | | | | |  __/\__ \
\_| |_/___|\__,_|_|  \___| \_|   |_| .__/ \___|_|_|_| |_|\___||___/
                                   | |
        agent v2.213.2             |_|          (commit 4f90e68)


>> End User License Agreements:

Building sources from a TFVC repository requires accepting the Team Explorer Everywhere End User License Agreement. This step is not required for building sources from Git repositories.

A copy of the Team Explorer Everywhere license agreement can be found at:
  /home/imac51/azure-agent/license.html

Enter (Y/N) Accept the Team Explorer Everywhere license agreement now? (press enter for N) > y

>> Connect:

Enter server URL > https://dev.azure.com/CompanyName
Enter authentication type (press enter for PAT) >
Enter personal access token > ****************************************************
No usable version of libssl was found
./config.sh: line 86:  6495 Aborted                 (core dumped) ./bin/Agent.Listener configure "$@"
imac51:~/azure-agent$
```
My ssh connection then goes dead.

Presumably I need to isntall a package? But what? 
`bin/installdependencies.sh` fails.

```
imac51:~/azure-agent/bin$ sudo ./installdependencies.sh
--------OS Information--------
PRETTY_NAME="Ubuntu 22.04.1 LTS"
NAME="Ubuntu"
VERSION_ID="22.04"
VERSION="22.04.1 LTS (Jammy Jellyfish)"
VERSION_CODENAME=jammy
ID=ubuntu
ID_LIKE=debian
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
UBUNTU_CODENAME=jammy
------------------------------
The current OS is Debian based
--------Debian Version--------
bookworm/sid
------------------------------
/usr/bin/apt
Hit:1 http://gb.archive.ubuntu.com/ubuntu jammy InRelease
Hit:2 http://gb.archive.ubuntu.com/ubuntu jammy-updates InRelease
Hit:3 http://gb.archive.ubuntu.com/ubuntu jammy-backports InRelease
Hit:4 http://security.ubuntu.com/ubuntu jammy-security InRelease
Hit:5 https://packages.microsoft.com/ubuntu/22.10/prod kinetic InRelease
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
All packages are up-to-date.
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
E: Unable to locate package liblttng-ust0
'apt' failed with exit code '0'
Can't install dotnet core dependencies.
Please make sure that required repositories are connected for relevant package installer.
For issues with dependencies installation (like 'dependency was not found in repository' or 'problem retrieving the repository index file') - you can reach out to distribution owner for futher support.
You can manually install all required dependencies based on following documentation
https://docs.microsoft.com/dotnet/core/install/linux
imac51:~/azure-agent/bin$
```

**Comment by kirill-ivlev** [comment] 2023-01-03 14:14
Hi @rwb196884,
Thank you for reporting this issue.
Based on [official documentation ](https://learn.microsoft.com/en-us/azure/devops/pipelines/agents/v2-linux?view=azure-devops#check-prerequisites) ubuntu 22.04 is not yet supported.

We will upgrade the agent & installdependencies script in future releases of the agent.

**Comment by Kamforka** [comment] 2023-01-09 09:14
+1 for this upgrade!

**Comment by sesu-bio** [comment] 2023-01-16 13:00
+1
Our build machines are still running Ubuntu 18.04. Since the [end of standard support for 18.04 is in April](https://wiki.ubuntu.com/Releases), we would like to upgrade to the latest LTS which is 22.04.
I'm sure there will be a number of users running into this issue in the coming weeks.

**Comment by devgig** [comment] 2023-01-29 11:49
liblttng-ust0 has changed to liblttng-ust1.  Please let me know when ubuntu 22.04 LTS is supported

**Comment by MichelZ** [comment] 2023-02-02 12:28
Use this to install the required prereqs, then the agent install works:

```
wget -c http://security.ubuntu.com/ubuntu/pool/main/o/openssl/libssl1.1_1.1.1f-1ubuntu2.16_amd64.deb
apt install ./libssl1.1_1.1.1f-1ubuntu2.16_amd64.deb

wget -c http://security.ubuntu.com/ubuntu/pool/main/o/openssl/openssl_1.1.1f-1ubuntu2.16_amd64.deb
apt install ./openssl_1.1.1f-1ubuntu2.16_amd64.deb
```

**Comment by MichelZ** [comment] 2023-02-02 12:40
Also, this is a duplicate of #3834

**Comment by ismayilov-ismayil** [comment] 2023-03-01 22:15
Related PR: https://github.com/microsoft/azure-pipelines-agent/pull/4161

**Comment by kirill-ivlev** [comment] 2023-08-01 11:41
Starting [3.225.](https://github.com/microsoft/azure-pipelines-agent/releases/tag/v3.225.0)0 all scripts are capable with libssl.

Closing this issue

**Closed by kirill-ivlev** 2023-08-01 11:41 UTC
Labels: Area: Agent
