### ISSUE TITLE
ImportError: /lib/x86_64-linux-gnu/libm.so.6: version `GLIBC_2.29' not found

### ISSUE THREAD

**Issue by little-eyes** [microsoft/azure-pipelines-agent#3255] opened 2021-02-10 05:41 UTC
## Agent Version and Platform
Version of your agent? 2.181.1

OS of the machine running the agent? Linux

## Azure DevOps Type and Version
dev.azure.com

If on-premises, which release? 2015.0, 2017.1, 2019 RC2, etc.

If dev.azure.com, what is your organization name? https://dev.azure.com/microsoft

## What's not working?
When using a python:3.8 docker container to run the job, I got the following error. It starts to happen today.

```bash
Starting: CmdLine
==============================================================================
Task         : Command line
Description  : Run a command line script using Bash on Linux and macOS and cmd.exe on Windows
Version      : 2.178.0
Author       : Microsoft Corporation
Help         : https://docs.microsoft.com/azure/devops/pipelines/tasks/utility/command-line
==============================================================================
Generating script.
Script contents:
python -m pip install -U --use-deprecated=legacy-resolver pip==20.3.4 wheel pytest pytest-cov
========================== Starting Command Output ===========================
/bin/bash --noprofile --norc /__w/_temp/de49afd4-444f-4946-a638-0a7761676a42.sh
Traceback (most recent call last):
  File "/__t/Python/3.8.7/x64/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/__t/Python/3.8.7/x64/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/__t/Python/3.8.7/x64/lib/python3.8/site-packages/pip/__main__.py", line 21, in <module>
    from pip._internal.cli.main import main as _main
  File "/__t/Python/3.8.7/x64/lib/python3.8/site-packages/pip/_internal/cli/main.py", line 8, in <module>
    from pip._internal.cli.autocompletion import autocomplete
  File "/__t/Python/3.8.7/x64/lib/python3.8/site-packages/pip/_internal/cli/autocompletion.py", line 9, in <module>
    from pip._internal.cli.main_parser import create_main_parser
  File "/__t/Python/3.8.7/x64/lib/python3.8/site-packages/pip/_internal/cli/main_parser.py", line 7, in <module>
    from pip._internal.cli import cmdoptions
  File "/__t/Python/3.8.7/x64/lib/python3.8/site-packages/pip/_internal/cli/cmdoptions.py", line 22, in <module>
    from pip._internal.cli.progress_bars import BAR_TYPES
  File "/__t/Python/3.8.7/x64/lib/python3.8/site-packages/pip/_internal/cli/progress_bars.py", line 5, in <module>
    from pip._vendor.progress.bar import Bar, FillingCirclesBar, IncrementalBar
  File "/__t/Python/3.8.7/x64/lib/python3.8/site-packages/pip/_vendor/progress/__init__.py", line 18, in <module>
    from datetime import timedelta
  File "/__t/Python/3.8.7/x64/lib/python3.8/datetime.py", line 8, in <module>
    import math as _math
ImportError: /lib/x86_64-linux-gnu/libm.so.6: version `GLIBC_2.29' not found (required by /__t/Python/3.8.7/x64/lib/python3.8/lib-dynload/math.cpython-38-x86_64-linux-gnu.so)
##[error]Bash exited with code '1'.

```

I'm using the Azure Pipelines agent pool and running **ubuntu-latest** VMs.

```yaml
resources:
  containers:
  - container: python38
    image: python:3.8
```

The error happens when executing this yaml task:

```bash
- script: 'python -m pip install -U --use-deprecated=legacy-resolver pip wheel pytest pytest-cov'
```

**Comment by alexander-smolyakov** [comment] 2021-02-10 14:34
Hey @little-eyes, it seems this problem related to virtual images.
Closing as duplicate of https://github.com/actions/virtual-environments/issues/2634

**Closed by alexander-smolyakov** 2021-02-10 14:34 UTC
Labels: Area: ABTT, Area: Agent
