### ISSUE TITLE
Status page needs to be updated in a timely manner during pipeline outages

### ISSUE THREAD

**Issue by GFoley83** [microsoft/azure-pipelines-agent#4177] opened 2023-03-03 03:05 UTC
This issue is in reference to the recent global outage which is covered here on the Azure DevOps status page:
https://status.dev.azure.com/_event/371776903

The error went _completely_ undocumented during the entire outage as far as the status page was concerned. 

We had the DevOps team at our company trying to diagnose an issue for two hours which they of course couldn't fix. During this period the status page was:

* Never updated to acknowledge the outage
* Only updated under the event history tab _after_ the issue had been resolved

It seems the team responsible for the DevOps status page are more concern with the appearance that everything is ok and not acknowledging issues to save face, than they are with helping their customers. 

This is not ok and needs to be recognised.

**Comment by hamenu** [comment] 2023-03-05 22:08
> Never updated to acknowledge the outage

I did manage to see the outage in their Status page. Not sure how long after the outage started though:

![image](https://user-images.githubusercontent.com/123523199/222988579-23062f04-581d-4c9f-805a-f5419815d1a0.png)

It's still not new for Azure, either [DevOps](https://status.dev.azure.com/) or [Cloud](https://azure.status.microsoft/en-gb/status), to update their status page waaaay after all the engineers in the entire world have shouted about an outage in every single social media!

That's when they accept they have an outage and update their page!

**Comment by LiliaSabitova** [comment] 2023-03-07 15:57
Hello @GFoley83, thank you for reporting this.
But the issue is not related to Agent, thus I'm closing the issue.
Please re-open it at [Microsoft Developer Community](https://developercommunity.visualstudio.com/home).
It would be a right place to address this issue.

**Closed by LiliaSabitova** 2023-03-07 15:57 UTC
Labels: Area: Agent
