### ISSUE TITLE
Jobs failing since agents updated from 2.164.8 to 2.165.0

### ISSUE THREAD

**Issue by atedsimple** [microsoft/azure-pipelines-agent#2839] opened 2020-03-04 18:52 UTC
We have been running a pool of 15 agents running within a Docker Swarm environment for about 6 months and they have been working really well. Then all of a sudden we have started to get numerous build failures across several pipelines and the only thing that has changed is that all of the agents have updated themselves to 2.165.0 and the last time the pipeline worked it was running 2.164.8

I notice that there 2.165.1 in preview, will this address our issues?

**Comment by jtpetty** [comment] 2020-03-05 17:00
@atedsimple - We will need more information about the type of failure you are seeing in order to answer that question.

**Comment by atedsimple** [comment] 2020-03-05 17:12
This is an log for tests running on one our agent when it was on version 2.164.8

Version      : 2.164.0
Author       : Microsoft Corporation
Help         : https://docs.microsoft.com/azure/devops/pipelines/tasks/build/dotnet-core-cli
==============================================================================
C:\Windows\system32\chcp.com 65001
Active code page: 65001
"C:\Program Files\dotnet\dotnet.exe" test C:\azp\agent\_work\3\s\TeamsGovernance\DataAccess.TableStorage.Tests\DataAccess.TableStorage.Tests.csproj --logger trx --results-directory C:\azp\agent\_work\_temp -c Release --collect "Code coverage" --no-restore --no-build
Test run for C:\azp\agent\_work\3\s\TeamsGovernance\DataAccess.TableStorage.Tests\bin\Release\netcoreapp2.2\DataAccess.TableStorage.Tests.dll(.NETCoreApp,Version=v2.2)
Microsoft (R) Test Execution Command Line Tool Version 16.3.0
Copyright (c) Microsoft Corporation.  All rights reserved.

Starting test execution, please wait...

A total of 1 test files matched the specified pattern.
Microsoft (R) Coverage Collection Tool Version 16.0.30319.3002


Copyright (c) Microsoft Corporation.  All rights reserved.




  ! RuleRepoTestSpike
Results File: C:\azp\agent\_work\_temp\ContainerAdministrator_6F3B2BCEC02E_2020-02-26_16_58_24.trx

Attachments:
  C:\azp\agent\_work\_temp\457a2f79-5b09-4024-bb5b-2d16b68b1c98\ContainerAdministrator_6F3B2BCEC02E_2020-02-26.16_58_23.coverage
Test Run Successful.
Total tests: 1
    Skipped: 1
 Total time: 0.9147 Seconds
"C:\Program Files\dotnet\dotnet.exe" test C:\azp\agent\_work\3\s\TeamsGovernance\Graph.LargeTests\Graph.LargeTests.csproj --logger trx --results-directory C:\azp\agent\_work\_temp -c Release --collect "Code coverage" --no-restore --no-build
Test run for C:\azp\agent\_work\3\s\TeamsGovernance\Graph.LargeTests\bin\Release\netcoreapp2.2\Graph.LargeTests.dll(.NETCoreApp,Version=v2.2)
Microsoft (R) Test Execution Command Line Tool Version 16.3.0
Copyright (c) Microsoft Corporation.  All rights reserved.

Starting test execution, please wait...

A total of 1 test files matched the specified pattern.
No test is available in C:\azp\agent\_work\3\s\TeamsGovernance\Graph.LargeTests\bin\Release\netcoreapp2.2\Graph.LargeTests.dll. Make sure that test discoverer & executors are registered and platform & framework version settings are appropriate and try again.
Microsoft (R) Coverage Collection Tool Version 16.0.30319.3002


Copyright (c) Microsoft Corporation.  All rights reserved.




Results File: C:\azp\agent\_work\_temp\ContainerAdministrator_6F3B2BCEC02E_2020-02-26_16_58_26.trx

Attachments:
  C:\azp\agent\_work\_temp\ce643298-114e-4636-b371-c9a35a3e2f41\ContainerAdministrator_6F3B2BCEC02E_2020-02-26.16_58_25.coverage
"C:\Program Files\dotnet\dotnet.exe" test C:\azp\agent\_work\3\s\TeamsGovernance\Graph.SmallTests\Graph.SmallTests.csproj --logger trx --results-directory C:\azp\agent\_work\_temp -c Release --collect "Code coverage" --no-restore --no-build
Test run for C:\azp\agent\_work\3\s\TeamsGovernance\Graph.SmallTests\bin\Release\netcoreapp2.2\Graph.SmallTests.dll(.NETCoreApp,Version=v2.2)
Microsoft (R) Test Execution Command Line Tool Version 16.3.0
Copyright (c) Microsoft Corporation.  All rights reserved.

Starting test execution, please wait...

**Comment by atedsimple** [comment] 2020-03-05 17:15
And this is now the output on subsequent runs after the agent updgraded to version 2.165.0

Test Run Failed.
##[error]Error: The process 'C:\Program Files\dotnet\dotnet.exe' failed with exit code 1
"C:\Program Files\dotnet\dotnet.exe" test C:\azp\agent\_work\2\s\TeamsGovernance\Security.SmallTests\Security.SmallTests.csproj --logger trx --results-directory C:\azp\agent\_work\_temp -c Release --collect "Code coverage" --no-restore --no-build
Test run for C:\azp\agent\_work\2\s\TeamsGovernance\Security.SmallTests\bin\Release\netcoreapp2.1\Security.SmallTests.dll(.NETCoreApp,Version=v2.1)
Microsoft (R) Test Execution Command Line Tool Version 16.3.0
Copyright (c) Microsoft Corporation.  All rights reserved.

Starting test execution, please wait...

A total of 1 test files matched the specified pattern.
Data collector 'Code Coverage' message: Data collector caught an exception of type 'Microsoft.VisualStudio.Coverage.VanguardException': 'Running event not received from CodeCoverage.exe. Check eventlogs for failure reason.'. More details: ..
Results File: C:\azp\agent\_work\_temp\ContainerAdministrator_7FDC9554778E_2020-03-03_10_47_36.trx

Test Run Failed.
Total tests: 17
     Passed: 17
 Total time: 2.5502 Seconds
##[error]Error: The process 'C:\Program Files\dotnet\dotnet.exe' failed with exit code 1
"C:\Program Files\dotnet\dotnet.exe" test C:\azp\agent\_work\2\s\TeamsGovernance\TeamsGovernance.Tests\TeamsGovernance.Tests.csproj --logger trx --results-directory C:\azp\agent\_work\_temp -c Release --collect "Code coverage" --no-restore --no-build
Test run for C:\azp\agent\_work\2\s\TeamsGovernance\TeamsGovernance.Tests\bin\Release\netcoreapp2.2\TeamsGovernance.Tests.dll(.NETCoreApp,Version=v2.2)
Microsoft (R) Test Execution Command Line Tool Version 16.3.0
Copyright (c) Microsoft Corporation.  All rights reserved.

Starting test execution, please wait...

A total of 1 test files matched the specified pattern.
Data collector 'Code Coverage' message: Data collector caught an exception of type 'Microsoft.VisualStudio.Coverage.VanguardException': 'Running event not received from CodeCoverage.exe. Check eventlogs for failure reason.'. More details: ..
Results File: C:\azp\agent\_work\_temp\ContainerAdministrator_7FDC9554778E_2020-03-03_10_47_40.trx

Test Run Failed.
Total tests: 261
     Passed: 261
 Total time: 6.5787 Seconds
##[error]Error: The process 'C:\Program Files\dotnet\dotnet.exe' failed with exit code 1
Result Attachments will be stored in LogStore
Run Attachments will be stored in LogStore
No Result Found to Publish 'C:\azp\agent\_work\_temp\ContainerAdministrator_7FDC9554778E_2020-03-03_10_47_18.trx'.
Info: Azure Pipelines hosted agents have been updated to contain .Net Core 3.x SDK/Runtime along with 2.2 & 2.1. Unless you have locked down a SDK version for your project(s), 3.x SDK might be picked up which might have breaking behavior as compared to previous versions. 
Some commonly encountered changes are: 
If you're using `Publish` command with -o or --Output argument, you will see that the output folder is now being created at root directory rather than Project File's directory. To learn about more such changes and troubleshoot, refer here: https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/build/dotnet-core-cli?view=azure-devops#troubleshooting
##[error]Dotnet command failed with non-zero exit code on the following projects : C:\azp\agent\_work\2\s\TeamsGovernance\DataAccess.TableStorage.Tests\DataAccess.TableStorage.Tests.csproj,C:\azp\agent\_work\2\s\TeamsGovernance\Graph.LargeTests\Graph.LargeTests.csproj,C:\azp\agent\_work\2\s\TeamsGovernance\Graph.SmallTests\Graph.SmallTests.csproj,C:\azp\agent\_work\2\s\TeamsGovernance\Messaging.SmallTests\Messaging.SmallTests.csproj,C:\azp\agent\_work\2\s\TeamsGovernance\Security.SmallTests\Security.SmallTests.csproj,C:\azp\agent\_work\2\s\TeamsGovernance\TeamsGovernance.Tests\TeamsGovernance.Tests.csproj
Async Command Start: Publish test results
Publishing test results to test run '1055934'.
Publishing test results to test run '1055930'.
TestResults To Publish 1, Test run id:1055934
TestResults To Publish 27, Test run id:1055930
Test results publishing 1, remaining: 0. Test run id: 1055934
Test results publishing 27, remaining: 0. Test run id: 1055930
Publishing test results to test run '1055932'.
TestResults To Publish 159, Test run id:1055932
Test results publishing 159, remaining: 0. Test run id: 1055932
Publishing test results to test run '1055936'.
TestResults To Publish 218, Test run id:1055936
Test results publishing 218, remaining: 0. Test run id: 1055936
Publishing test results to test run '1055938'.
TestResults To Publish 17, Test run id:1055938
Test results publishing 17, remaining: 0. Test run id: 1055938
Published Test Run : https://dev.azure.com/modalitysystems/Teams%20Governance/_TestManagement/Runs?runId=1055938&_a=runCharts.
Published Test Run : https://dev.azure.com/modalitysystems/Teams%20Governance/_TestManagement/Runs?runId=1055930&_a=runCharts.

**Comment by jtpetty** [comment] 2020-03-05 19:32
I am assuming this is a hosted agent. It seems like the image for hosted agents was updated. I see this message in the log:

```
Info: Azure Pipelines hosted agents have been updated to contain .Net Core 3.x SDK/Runtime along with 2.2 & 2.1. Unless you have locked down a SDK version for your project(s), 3.x SDK might be picked up which might have breaking behavior as compared to previous versions.
Some commonly encountered changes are:
If you're using Publish command with -o or --Output argument, you will see that the output folder is now being created at root directory rather than Project File's directory. To learn about more such changes and troubleshoot, refer here: https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/build/dotnet-core-cli?view=azure-devops#troubleshooting
```

Is it possible that this is result of your issue?

**Comment by atedsimple** [comment] 2020-03-05 21:06
These are on prem agents running in docker containers that have worked perfectly for months and yes would appear to have gone wrong when the agents updated themselves. I tried starting a new container today and noticed that all the visual studio and vstest entries in capabilities are missing but  are definitely installed.

Get Outlook for Android<https://aka.ms/ghei36>


David Clifford
DevOps Engineer
UC/SIP: david.clifford@modalitysystems.com
Website: www.modalitysystems.com
This email is sent on behalf of Modality Systems Ltd, Churchill House, 26-30 Upper Marlborough Road, St Albans, Herts, AL1 3UU, a limited company registered in England and Wales (company registration number 06143649 / VAT registration number GB 199 8724 29). This email (and any attachments) may contain information that is legally privileged, confidential or exempt from disclosure. 
When addressed to our clients or vendors, any information contained in this email or any attachments is subject to the terms and conditions in any governing contract. If you are not the intended recipient, please note that any dissemination, distribution, or copying of this communication is strictly prohibited. 
If you receive this message in error, you should notify the sender immediately and delete this communication entirely. Whilst best efforts have been made to ensure this email does not contain any viruses, Modality Systems Ltd. cannot guarantee that attachments are virus-free, and does not accept any liability in respect of damage caused by viruses. Please note that we may intercept, monitor and store emails for the purposes of ensuring compliance with legislation, our policies and auditing.
________________________________

**Comment by jtpetty** [comment] 2020-03-09 13:32
@atedsimple - Can you send me the agent logs of working vs non-working agent? It would be especially helpful to have the difference in capabilities. If you do not want to share them publicly, you can email them to me at tommy.petty@microsoft.com

**Comment by atedsimple** [comment] 2020-03-09 16:49
Ok so I have fixed our issues but would be good to get more conext around how I fixed it.
To begin with we had 2 docker images running on:-

mcr.microsoft.com/dotnet/framework/sdk:4.8-windowsservercore-ltsc2016 
and
mcr.microsoft.com/dotnet/framework/sdk:4.8-windowsservercore-ltsc2019

These were working perfectly for 4 or 5 months, then all of a sudden they stopped and the only thing that I could see had changed was that all of the agents had auto updated to 2.165.0 but not sure that was the root cause of our issues.

I first tried rebuilding the image but noticed that nothing was installing. We use Chocolatey to install all of our build tools. On closer inspection of the logs I noticed that Chocolatey was unable to download. I was able to fix this by adding the following to my Dockerfile

[System.Net.ServicePointManager]::SecurityProtocol = [System.Net.ServicePointManager]::SecurityProtocol -bor 3072

Which sets .NET Framework to use TLS 1.2, maybe this was the cause of all our issues?

I also noticed that Microsofts docs on how to create a Docker On-Prem Agent have change so we are now using images:-

mcr.microsoft.com/windows/servercore:ltsc2016
and
mcr.microsoft.com/windows/servercore:ltsc2019

Which is great as the images are 10GB smaller

**Comment by jtpetty** [comment] 2020-03-10 16:45
@atedsimple - I wish I had a solid answer for you. I know with 2.165.0, we switched to compile that with .NET Core 3.1. That could have caused the issue you are seeing. I also know that on the Azure DevOps server side, we are pushing to only support TLS 2.1 and will soon require the change you made in order to connect to Azure DevOps, maybe Chocolatey is doing the same and the timing is coincidental. 

As I was typing this, I found this: https://chocolatey.org/blog/remove-support-for-old-tls-versions

I think this is the root cause of your issue and the agent update was a red herring in all of this.

I am going to close this issue since it appears this is not an agent issue.

**Closed by jtpetty** 2020-03-10 16:45 UTC

**Comment by Pushpendu112** [comment] 2021-07-01 11:59
I've been facing exactly similar issue with my pipeline. And the strange part is, it works for a old branch of code perfectly fine, but when I'm trying to point to latest branch of code, I get this error


C:\windows\system32\chcp.com 65001
Active code page: 65001
Info: .NET Core SDK/runtime 2.2 and 3.0 are now End of Life(EOL) and have been removed from all hosted agents. If you're using these SDK/runtimes on hosted agents, kindly upgrade to newer versions which are not EOL, or else use UseDotNet task to install the required version.
"C:\Program Files\dotnet\dotnet.exe" test I:\Agent-Win-R\_work\489\s\XXXX.Test\XXXXBusiness.Test.csproj "--collect:XPlat Code Coverage" --settings CodeCoverage.runsettings --logger trx
Test run for I:\Agent-Win-R\_work\489\s\XXXX.Business.Test\bin\Debug\netcoreapp3.1\XXXXWeb.Business.Test.dll(.NETCoreApp,Version=v3.1)
Microsoft (R) Test Execution Command Line Tool Version 16.5.0
Copyright (c) Microsoft Corporation.  All rights reserved.

Starting test execution, please wait...

A total of 1 test files matched the specified pattern.
Data collector 'Code Coverage' message: Data collector caught an exception of type 'Microsoft.VisualStudio.Coverage.VanguardException': 'Running event not received from CodeCoverage.exe. Check eventlogs for failure reason.'. More details: ..
Results File: I:\Agent-Win-R\_work\489\s\XXXX.Business.Test\TestResults\SVCGIDETFSProdBld01_MP-GIDE-522C_2021-07-01_04_12_42.trx

Attachments:
  I:\Agent-Win-R\_work\489\s\XXXX.Business.Test\TestResults\3839c24a-e17d-4d0d-9953-359388d5a940\coverage.cobertura.xml
Test Run Failed.
Total tests: 6
     Passed: 6


**and When I tried to point to old branch of code, below is the log that I received**

C:\windows\system32\chcp.com 65001
Active code page: 65001
Info: .NET Core SDK/runtime 2.2 and 3.0 are now End of Life(EOL) and have been removed from all hosted agents. If you're using these SDK/runtimes on hosted agents, kindly upgrade to newer versions which are not EOL, or else use UseDotNet task to install the required version.
"C:\Program Files\dotnet\dotnet.exe" test I:\Agent-Win-R\_work\489\s\XXXX.Business.Test\XXXX.Business.Test.csproj "--collect:XPlat Code Coverage" --settings CodeCoverage.runsettings --logger trx
Test run for I:\Agent-Win-R\_work\489\s\XXXX.Business.Test\bin\Debug\netcoreapp3.1\XXXXWeb.Business.Test.dll(.NETCoreApp,Version=v3.1)
Microsoft (R) Test Execution Command Line Tool Version 16.5.0
Copyright (c) Microsoft Corporation.  All rights reserved.

Starting test execution, please wait...

A total of 1 test files matched the specified pattern.
Microsoft (R) Coverage Collection Tool Version 16.0.30319.3002


Copyright (c) Microsoft Corporation.  All rights reserved.




Results File: I:\Agent-Win-R\_work\489\s\XXXX.Business.Test\TestResults\SVCGIDETFSProdBld01_MP-GIDE-522C_2021-07-01_04_18_04.trx

Attachments:
  I:\Agent-Win-R\_work\489\s\XXXX.Business.Test\TestResults\5f62864f-6c2c-4188-ac02-0dc536b464b3\coverage.cobertura.xml
  I:\Agent-Win-R\_work\489\s\XXXX.Business.Test\TestResults\5f62864f-6c2c-4188-ac02-0dc536b464b3\SVCGIDETFSProdBld01_MP-GIDE-522C_2021-07-01.04_17_58.coverage
Test Run Successful.
Total tests: 6
     Passed: 6
 Total time: 3.8813 Seconds

I believe there must be something different between my two branches that is causing it, but I've no idea what. I tried comparing Microsoft.Net.Test.SDK and both branches have 16.2.0, and coverlet.collector 1.0.1 added in my test project. 

Any thoughts, what I else I should be looking out for?
