### ISSUE TITLE
[Question]: Cannot build with nuget 401 errors

### ISSUE THREAD

**Issue by xturtle** [microsoft/azure-pipelines-agent#4327] opened 2023-06-22 04:59 UTC
### Describe your question

I got many of these messages when I run "dev.sh layout", does anything I misconfigured? thanks.

`Failed to download package 'System.Security.Cryptography.OpenSsl.4.3.0' from 'https://pkgs.dev.azure.com/mseng/c86767d8-af79-4303-a7e6-21da0ba435e2/_packaging/61a4ae2c-15fb-4085-b7f6-0044b9eb7b85/nuget/v3/flat2/system.security.cryptography.openssl/4.3.0/system.security.cryptography.openssl.4.3.0.nupkg'.
  Response status code does not indicate success: 401 (Unauthorized - No local versions of package 'system.security.cryptography.openssl'; please provide authentication to access versions from upstream that have not yet been saved to your feed. (DevOps Activity ID: 5F6BEB79-0DD1-4D3E-B282-0D39188B8656)).`

### Versions

3.220.5, RHEL 8 and MacOS 13.4, get the same result.

### Environment type (Please select at least one enviroment where you face this issue)

- [X] Self-Hosted
- [ ] Microsoft Hosted
- [ ] VMSS Pool
- [ ] Container

### Azure DevOps Server type

Azure DevOps Server (Please specify exact version in the textbox below)

### Operation system

RHEL 8 UBI

### Version controll system

git

**Comment by pixdrift** [comment] 2023-09-05 07:09
I have replicated the same issue, the `dev.sh` script doesn't appear to work, perhaps it's only an issue if run outside of the Microsoft network?

This is attempting build on RHEL 9 after recent fix in `dev.sh` script to to allow builds on RHEL 7+

Clean OS image with the following installed to support script execution
`dnf install git unzip libicu`

```
# ./dev.sh b
/azure-pipelines-agent/src /azure-pipelines-agent/src


-----------------------------------------
  Platform / RID detection
-----------------------------------------
Current platform: linux
Current runtime ID: linux-x64
Building for runtime ID: linux-x64


-----------------------------------------
  .NET SDK to path
-----------------------------------------
Adding .NET to PATH (/azure-pipelines-agent/src/../_dotnetsdk/6.0.405)
Path = /azure-pipelines-agent/src/../_dotnetsdk/6.0.405:/root/.local/bin:/root/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
.NET Version = 6.0.405


-----------------------------------------
  Pre-caching external resources for linux-x64
-----------------------------------------
Download exists: vso-task-lib.tar.gz
Download exists: node-v6.17.1-linux-x64.tar.gz
Download exists: node-v10.24.1-linux-x64.tar.gz
Download exists: node-v16.20.0-linux-x64.tar.gz
Download exists: node-v20.3.1-linux-x64.tar.gz
rm: cannot remove '/azure-pipelines-agent/_layout/linux-x64/externals/node/bin/npm': No such file or directory
rm: cannot remove '/azure-pipelines-agent/_layout/linux-x64/externals/node10/bin/npm': No such file or directory
rm: cannot remove '/azure-pipelines-agent/_layout/linux-x64/externals/node10/bin/npx': No such file or directory
rm: cannot remove '/azure-pipelines-agent/_layout/linux-x64/externals/node16/bin/npm': No such file or directory
rm: cannot remove '/azure-pipelines-agent/_layout/linux-x64/externals/node16/bin/npx': No such file or directory
rm: cannot remove '/azure-pipelines-agent/_layout/linux-x64/externals/node16/bin/corepack': No such file or directory
rm: cannot remove '/azure-pipelines-agent/_layout/linux-x64/externals/node20/bin/npm': No such file or directory
rm: cannot remove '/azure-pipelines-agent/_layout/linux-x64/externals/node20/bin/npx': No such file or directory
rm: cannot remove '/azure-pipelines-agent/_layout/linux-x64/externals/node20/bin/corepack': No such file or directory
Download exists: d9bafed4-0b18-4f58-968d-86655b4d2ce9.zip
Download exists: f9bafed4-0b18-4f58-968d-86655b4d2ce9.zip


-----------------------------------------
  Building
-----------------------------------------
MSBuild target = Build

Welcome to .NET 6.0!
---------------------
SDK Version: 6.0.405

Telemetry
---------
The .NET tools collect usage data in order to help us improve your experience. It is collected by Microsoft and shared with the community. You can opt-out of telemetry by setting the DOTNET_CLI_TELEMETRY_OPTOUT environment variable to '1' or 'true' using your favorite shell.

Read more about .NET CLI Tools telemetry: https://aka.ms/dotnet-cli-telemetry

----------------
Installed an ASP.NET Core HTTPS development certificate.
To trust the certificate run 'dotnet dev-certs https --trust' (Windows and macOS only).
Learn about HTTPS: https://aka.ms/dotnet-https
----------------
Write your first app: https://aka.ms/dotnet-hello-world
Find out what's new: https://aka.ms/dotnet-whats-new
Explore documentation: https://aka.ms/dotnet-docs
Report issues and find source on GitHub: https://github.com/dotnet/core
Use 'dotnet --help' to see available commands or visit: https://aka.ms/dotnet-cli
--------------------------------------------------------------------------------------
MSBuild version 17.3.2+561848881 for .NET
  /usr/bin/sh: line 1: warning: setlocale: LC_ALL: cannot change locale (en_US.UTF-8)
  /usr/bin/sh: line 1: warning: setlocale: LC_ALL: cannot change locale (en_US.UTF-8)
  9a7c35804c093a5e5f5a8bba3d5dfb383988edac
  Building /usr/bin/sh: line 1: warning: setlocale: LC_ALL: cannot change locale (en_US.UTF-8);/usr/bin/sh: line 1: warning: setlocale: LC_ALL: cannot change locale (en_US.UTF-8);9a7c35804c093a5e5f5a8bba3d5dfb383988edac --- linux-x64
  Determining projects to restore...
  Restored /azure-pipelines-agent/src/Agent.Sdk/Agent.Sdk.csproj (in 52.97 sec).
  Restored /azure-pipelines-agent/src/Microsoft.VisualStudio.Services.Agent/Microsoft.VisualStudio.Services.Agent.csproj (in 52.97 sec).
  Determining projects to restore...
  Failed to download package 'Microsoft.VisualStudio.Services.Client.16.205.1' from 'https://pkgs.dev.azure.com/mseng/c86767d8-af79-4303-a7e6-21da0ba435e2/_packaging/61a4ae2c-15fb-4085-b7f6-0044b9eb7b85/nuget/v3/flat2/microsoft.visualstudio.services.client/16.205.1/microsoft.visualstudio.services.client.16.205.1.nupkg'.
  Response status code does not indicate success: 401 (Unauthorized - No local versions of package 'microsoft.visualstudio.services.client'; please provide authentication to access versions from upstream that have not yet been saved to your feed. (DevOps Activity ID: 5496754F-0698-42DA-8F46-875AE493A424)).
  Failed to download package 'Microsoft.TeamFoundation.DistributedTask.Common.Contracts.16.205.1' from 'https://pkgs.dev.azure.com/mseng/c86767d8-af79-4303-a7e6-21da0ba435e2/_packaging/61a4ae2c-15fb-4085-b7f6-0044b9eb7b85/nuget/v3/flat2/microsoft.teamfoundation.distributedtask.common.contracts/16.205.1/microsoft.teamfoundation.distributedtask.common.contracts.16.205.1.nupkg'.
  Response status code does not indicate success: 401 (Unauthorized - No local versions of package 'microsoft.teamfoundation.distributedtask.common.contracts'; please provide authentication to access versions from upstream that have not yet been saved to your feed. (DevOps Activity ID: F2034F3C-6D83-4613-BDD9-2368F6D41776)).
  Failed to download package 'Microsoft.VisualStudio.Services.Client.16.205.1' from 'https://pkgs.dev.azure.com/mseng/c86767d8-af79-4303-a7e6-21da0ba435e2/_packaging/61a4ae2c-15fb-4085-b7f6-0044b9eb7b85/nuget/v3/flat2/microsoft.visualstudio.services.client/16.205.1/microsoft.visualstudio.services.client.16.205.1.nupkg'.
  Response status code does not indicate success: 401 (Unauthorized - No local versions of package 'microsoft.visualstudio.services.client'; please provide authentication to access versions from upstream that have not yet been saved to your feed. (DevOps Activity ID: F2034F33-6D83-4613-BDD9-2368F6D41776)).
  Failed to download package 'Microsoft.TeamFoundation.DistributedTask.Common.Contracts.16.205.1' from 'https://pkgs.dev.azure.com/mseng/c86767d8-af79-4303-a7e6-21da0ba435e2/_packaging/61a4ae2c-15fb-4085-b7f6-0044b9eb7b85/nuget/v3/flat2/microsoft.teamfoundation.distributedtask.common.contracts/16.205.1/microsoft.teamfoundation.distributedtask.common.contracts.16.205.1.nupkg'.
  Response status code does not indicate success: 401 (Unauthorized - No local versions of package 'microsoft.teamfoundation.distributedtask.common.contracts'; please provide authentication to access versions from upstream that have not yet been saved to your feed. (DevOps Activity ID: F2034F1A-6D83-4613-BDD9-2368F6D41776)).
  Failed to download package 'Microsoft.VisualStudio.Services.Client.16.205.1' from 'https://pkgs.dev.azure.com/mseng/c86767d8-af79-4303-a7e6-21da0ba435e2/_packaging/61a4ae2c-15fb-4085-b7f6-0044b9eb7b85/nuget/v3/flat2/microsoft.visualstudio.services.client/16.205.1/microsoft.visualstudio.services.client.16.205.1.nupkg'.
  Response status code does not indicate success: 401 (Unauthorized - No local versions of package 'microsoft.visualstudio.services.client'; please provide authentication to access versions from upstream that have not yet been saved to your feed. (DevOps Activity ID: F2034F6D-6D83-4613-BDD9-2368F6D41776)).
  Failed to download package 'Microsoft.TeamFoundation.DistributedTask.Common.Contracts.16.205.1' from 'https://pkgs.dev.azure.com/mseng/c86767d8-af79-4303-a7e6-21da0ba435e2/_packaging/61a4ae2c-15fb-4085-b7f6-0044b9eb7b85/nuget/v3/flat2/microsoft.teamfoundation.distributedtask.common.contracts/16.205.1/microsoft.teamfoundation.distributedtask.common.contracts.16.205.1.nupkg'.
  Response status code does not indicate success: 401 (Unauthorized - No local versions of package 'microsoft.teamfoundation.distributedtask.common.contracts'; please provide authentication to access versions from upstream that have not yet been saved to your feed. (DevOps Activity ID: 54967AFD-0698-42DA-8F46-875AE493A424)).
  Failed to download package 'Microsoft.VisualStudio.Services.Client.16.205.1' from 'https://pkgs.dev.azure.com/mseng/c86767d8-af79-4303-a7e6-21da0ba435e2/_packaging/61a4ae2c-15fb-4085-b7f6-0044b9eb7b85/nuget/v3/flat2/microsoft.visualstudio.services.client/16.205.1/microsoft.visualstudio.services.client.16.205.1.nupkg'.
  Response status code does not indicate success: 401 (Unauthorized - No local versions of package 'microsoft.visualstudio.services.client'; please provide authentication to access versions from upstream that have not yet been saved to your feed. (DevOps Activity ID: B56C300A-CB30-4900-8516-6EB5B3B162C6)).
  Failed to download package 'Microsoft.TeamFoundation.DistributedTask.Common.Contracts.16.205.1' from 'https://pkgs.dev.azure.com/mseng/c86767d8-af79-4303-a7e6-21da0ba435e2/_packaging/61a4ae2c-15fb-4085-b7f6-0044b9eb7b85/nuget/v3/flat2/microsoft.teamfoundation.distributedtask.common.contracts/16.205.1/microsoft.teamfoundation.distributedtask.common.contracts.16.205.1.nupkg'.
  Response status code does not indicate success: 401 (Unauthorized - No local versions of package 'microsoft.teamfoundation.distributedtask.common.contracts'; please provide authentication to access versions from upstream that have not yet been saved to your feed. (DevOps Activity ID: B56C3019-CB30-4900-8516-6EB5B3B162C6)).
  Failed to download package 'Microsoft.VisualStudio.Services.Client.16.205.1' from 'https://pkgs.dev.azure.com/mseng/c86767d8-af79-4303-a7e6-21da0ba435e2/_packaging/61a4ae2c-15fb-4085-b7f6-0044b9eb7b85/nuget/v3/flat2/microsoft.visualstudio.services.client/16.205.1/microsoft.visualstudio.services.client.16.205.1.nupkg'.
  Response status code does not indicate success: 401 (Unauthorized - No local versions of package 'microsoft.visualstudio.services.client'; please provide authentication to access versions from upstream that have not yet been saved to your feed. (DevOps Activity ID: B56C33AA-CB30-4900-8516-6EB5B3B162C6)).
  Failed to download package 'Microsoft.TeamFoundation.DistributedTask.Common.Contracts.16.205.1' from 'https://pkgs.dev.azure.com/mseng/c86767d8-af79-4303-a7e6-21da0ba435e2/_packaging/61a4ae2c-15fb-4085-b7f6-0044b9eb7b85/nuget/v3/flat2/microsoft.teamfoundation.distributedtask.common.contracts/16.205.1/microsoft.teamfoundation.distributedtask.common.contracts.16.205.1.nupkg'.
  Response status code does not indicate success: 401 (Unauthorized - No local versions of package 'microsoft.teamfoundation.distributedtask.common.contracts'; please provide authentication to access versions from upstream that have not yet been saved to your feed. (DevOps Activity ID: 54967BC6-0698-42DA-8F46-875AE493A424)).
/azure-pipelines-agent/_dotnetsdk/6.0.405/sdk/6.0.405/NuGet.targets(132,5): error : Failed to download package 'Microsoft.VisualStudio.Services.Client.16.205.1' from 'https://pkgs.dev.azure.com/mseng/c86767d8-af79-4303-a7e6-21da0ba435e2/_packaging/61a4ae2c-15fb-4085-b7f6-0044b9eb7b85/nuget/v3/flat2/microsoft.visualstudio.services.client/16.205.1/microsoft.visualstudio.services.client.16.205.1.nupkg'. [/azure-pipelines-agent/src/Agent.Listener/Agent.Listener.csproj]
/azure-pipelines-agent/_dotnetsdk/6.0.405/sdk/6.0.405/NuGet.targets(132,5): error : Response status code does not indicate success: 401 (Unauthorized - No local versions of package 'microsoft.visualstudio.services.client'; please provide authentication to access versions from upstream that have not yet been saved to your feed. (DevOps Activity ID: 54967B98-0698-42DA-8F46-875AE493A424)). [/azure-pipelines-agent/src/Agent.Listener/Agent.Listener.csproj]
/azure-pipelines-agent/_dotnetsdk/6.0.405/sdk/6.0.405/NuGet.targets(132,5): error : Failed to download package 'Microsoft.TeamFoundation.DistributedTask.Common.Contracts.16.205.1' from 'https://pkgs.dev.azure.com/mseng/c86767d8-af79-4303-a7e6-21da0ba435e2/_packaging/61a4ae2c-15fb-4085-b7f6-0044b9eb7b85/nuget/v3/flat2/microsoft.teamfoundation.distributedtask.common.contracts/16.205.1/microsoft.teamfoundation.distributedtask.common.contracts.16.205.1.nupkg'. [/azure-pipelines-agent/src/Agent.Listener/Agent.Listener.csproj]
/azure-pipelines-agent/_dotnetsdk/6.0.405/sdk/6.0.405/NuGet.targets(132,5): error : Response status code does not indicate success: 401 (Unauthorized - No local versions of package 'microsoft.teamfoundation.distributedtask.common.contracts'; please provide authentication to access versions from upstream that have not yet been saved to your feed. (DevOps Activity ID: B56C3341-CB30-4900-8516-6EB5B3B162C6)). [/azure-pipelines-agent/src/Agent.Listener/Agent.Listener.csproj]
  Failed to restore /azure-pipelines-agent/src/Agent.Listener/Agent.Listener.csproj (in 13.64 sec).
  2 of 3 projects are up-to-date for restore.
Failed: build
```

**Comment by pixdrift** [comment] 2023-09-06 06:31
I have a working solution for EL9 now, tested on a RockyLinux 9 base container (and should work for EL variants and EL8 too).

It appears the 401 errors are related to cruft in the layout directory, so it's critical that the layout step is run before the build step.

Additionally, this warning is actually critical:
`Building /usr/bin/sh: line 1: warning: setlocale: LC_ALL: cannot change locale (en_US.UTF-8);/usr/bin/sh: line 1: warning: setlocale: LC_ALL: cannot change locale (en_US.UTF-8);9a7c35804c093a5e5f5a8bba3d5dfb383988edac --- linux-x64
  Determining projects to restore...`
  
You need to ensure the correct UTF language pack is installed, otherwise the compiler throws errors due to what I can only assume are UTF characters for commas and other punctuation used throughout the source.

This is the sequence of commands run on a clean EL9 container that builds off latest master branch (v3.225.0)

```
dnf install git unzip libicu glibc-langpack-en -y
git clone https://github.com/microsoft/azure-pipelines-agent.git
./azure-pipelines-agent/src/dev.sh l
./azure-pipelines-agent/src/dev.sh b
./azure-pipelines-agent/src/dev.sh p
```

l = layout
b = build
p = package

This will result in a tarball with the compiled code. It builds cleanly, but I haven't yet validated the build with ADO.

**Comment by vmapetr** [comment] 2023-11-21 20:18
Hi @xturtle, sorry for the delayed response.
We uploaded the missing package, the issue is resolved now, we validated build on UBI9 and CentOS 8. I'm going to close this ticket but please feel free to reopen it if you have additional questions.

**Closed by vmapetr** 2023-11-21 20:18 UTC
Labels: question, Area: Agent
