### ISSUE TITLE
Offline agent stays in the pool after it's --once run

### ISSUE THREAD

**Issue by EwanNoble** [Microsoft/azure-pipelines-agent#2220] opened 2019-04-18 10:47 UTC
## Agent Version and Platform
Version of your agent? 2.149.2

OS of the machine running the agent? Linux

## Azure DevOps Type and Version
dev.azure.com (formerly visualstudio.com)

## What's not working?
With the latest agent release I am looking into using the run once flag (--once) to tear down our agent containers after they have completed a job. This is working correctly in terms of running but after the container has been stopped the offline agent still remains in the pool. I expected that it would execute it's normal stop procedure which involves removing itself from the agent pool. Is this by design or is it perhaps a bug in the run once functionality?

**Comment by TingluoHuang** [comment] 2019-04-18 14:03
@EwanNoble remove agent from pool (Unconfigure) requires admin privilege. the behavior you saw is by designed since `--once` don't have any credential from you. :)

**Comment by EwanNoble** [comment] 2019-04-18 14:13
Hi @TingluoHuang, thanks for the response. The admin credentials would be available to the service at this point as they are used for configuration, would there be scope for a feature to provide the 'run once' agent to access those credentials if available?

**Comment by TingluoHuang** [comment] 2019-04-18 14:33
@EwanNoble we don't have feature for that yet, but i think you can do it yourself.

Dockerfile:
`CMD "config.sh && run.sh --once && config.sh remove"`

**Comment by EwanNoble** [comment] 2019-04-18 15:16
@TingluoHuang that makes a lot of sense and it worked perfectly! Thanks for your help. 😊

**Comment by TingluoHuang** [comment] 2019-04-18 17:26
cool, i am going to close this issue, please reopen if you need more help. :)

**Closed by TingluoHuang** 2019-04-18 17:26 UTC
