### ISSUE TITLE
[BUG]: TimeoutException for Azure Blob Storage

### ISSUE THREAD

**Issue by t-moe** [microsoft/azure-pipelines-agent#4373] opened 2023-07-28 08:57 UTC
### What happened?

We're getting timeout and errors across various tasks:
* Publish Pipeline Artifacts
   *  `ArtifactHttpRetryMessageHandler.SendAsync: https://vsblobprodsu6weu.vsblob.visualstudio.com/****/_apis/dedup/nodes/***** attempt 2/6 failed with TimeoutException: 'The HTTP request timed out after 00:01:40.`
 * Cache
   * ```##[error]Chunk # 1 at offset 129832 with hash: 531900E528400AC256B0949D5D668CD7A8AADAE54E016033AC63A501A51331FB01 and size 97358: Expected chunk #0.```
   * ```##[error]HTTP 503 throttling.```

### Versions

Microsoft hosted agent 
windows-latest
3.224.1

### Environment type (Please select at least one enviroment where you face this issue)

- [ ] Self-Hosted
- [X] Microsoft Hosted
- [ ] VMSS Pool
- [ ] Container

### Azure DevOps Server type

dev.azure.com (formerly visualstudio.com)

**Comment by t-moe** [comment] 2023-07-28 09:31
Seems to be adressed in https://status.dev.azure.com/_event/410140881

**Comment by LiliaSabitova** [comment] 2023-07-31 10:45
Hi @t-moe, thank you for reporting this.
But the issue is not related to Agent, thus I'm closing the issue.
If the issue is still relevant, please re-open it at [Microsoft Developer Community](https://developercommunity.visualstudio.com/home).
It would be a right place to address this issue.

**Closed by LiliaSabitova** 2023-07-31 10:45 UTC
Labels: bug, Area: Agent
