### ISSUE TITLE
Registration fails if the agent pool name contains a 'space' character

### ISSUE THREAD

**Issue by JohannBlais** [microsoft/azure-pipelines-agent#2512] opened 2019-10-15 14:41 UTC
## Agent Version and Platform
Parameter|Value
-- | --
Agent.OS | Windows_NT
Agent.OSArchitecture | X64
Agent.OSVersion | 10.0.17134
Agent.Version | 2.158.0

## Azure DevOps Type and Version
Parameter|Value
-- | --
Azure DevOps Server|2019.1

## What's not working?
Hello,

I am registering UI test agents in our ADS instance using the following command line:

`& "$InstallPath\config.cmd" --unattended --replace --url $ServerUrl --auth pat --token $token --pool $ServerPool --agent $agent --runAsAutoLogon --windowslogonaccount $ServiceAccountName --windowslogonpassword $ServiceAccountPassword --sslskipcertvalidation`

Registering an agent fails if the agent pool contains a "space" like in "UI Automation".
```
[2019-10-15 07:52:34Z INFO Terminal] WRITE LINE: 
[2019-10-15 07:52:34Z INFO Terminal] WRITE LINE: >> Register Agent:
[2019-10-15 07:52:34Z INFO Terminal] WRITE LINE: 
[2019-10-15 07:52:34Z INFO CommandSettings] Arg 'pool': 'UI Automation'
[2019-10-15 07:52:34Z INFO CommandSettings] Remove pool from Arg dictionary.
[2019-10-15 07:52:34Z INFO CommandSettings] Flag 'unattended': 'True'
[2019-10-15 07:52:34Z ERR  Agent] Microsoft.TeamFoundation.DistributedTask.WebApi.TaskAgentPoolNotFoundException: Agent pool not found: 'UI Automation'
   at Microsoft.VisualStudio.Services.Agent.Listener.Configuration.BuildReleasesAgentConfigProvider.GetPoolIdAndName(AgentSettings agentSettings, CommandSettings command)
   at Microsoft.VisualStudio.Services.Agent.Listener.Configuration.ConfigurationManager.ConfigureAsync(CommandSettings command)
   at Microsoft.VisualStudio.Services.Agent.Listener.Agent.ExecuteCommand(CommandSettings command)
[2019-10-15 07:52:34Z ERR  Terminal] WRITE ERROR: Agent pool not found: 'UI Automation'

```
Creating a pool named "Automation"
```
[2019-10-15 14:19:53Z INFO RSAEncryptedFileKeyManager] Successfully saved RSA key parameters to file D:\B1\.credentials_rsaparams
[2019-10-15 14:19:53Z INFO Terminal] WRITE LINE: 
[2019-10-15 14:19:53Z INFO Terminal] WRITE LINE: >> Register Agent:
[2019-10-15 14:19:53Z INFO Terminal] WRITE LINE: 
[2019-10-15 14:19:53Z INFO CommandSettings] Arg 'pool': 'Automation'
[2019-10-15 14:19:53Z INFO CommandSettings] Remove pool from Arg dictionary.
[2019-10-15 14:19:53Z INFO BuildReleasesAgentConfigProvider] Found pool Automation with id 13 and name Automation
```

The pools have exactly the same configuration so I am sure it is not a permission issue.

**Comment by KseniaIV** [comment] 2019-11-05 10:11
I repro and also found that is was once closed
https://github.com/microsoft/azure-pipelines-agent/issues/802

**Comment by jtpetty** [comment] 2019-11-07 19:02
@JohannBlais - I was unable to reproduce this issue. One thing we can double check, can you use this (https://docs.microsoft.com/en-us/rest/api/azure/devops/distributedtask/pools/get%20agent%20pools?view=azure-devops-rest-5.1) REST endpoint to get a json dump of the pools in your org?

**Comment by JohannBlais** [comment] 2019-11-08 09:54
Please note that we had to rename our pool to proceed, so it does not contain a 'space' anymore.

```
{
    "count": 3,
    "value": [
        {
            "createdOn": "2016-02-01T13:58:40.233Z",
            "autoProvision": true,
            "autoSize": true,
            "targetSize": null,
            "agentCloudId": null,
            "createdBy": {
                "displayName": "[Agent Pools]\\Agent Pool Administrators",
                "url": "http://[redacted]/_apis/Identities/46bf9566-b291-4937-aa81-926a7f9aa97b",
                "id": "46bf9566-b291-4937-aa81-926a7f9aa97b",
                "uniqueName": "vstfs:///Framework/Generic/18968611-4fe9-4dc4-b08f-1e7796d63c3a\\Agent Pool Administrators",
                "imageUrl": "",
                "isContainer": true,
                "descriptor": "vssgp.Uy0xLTktMTU1MTM3NDI0NS0yOTQwMzI5MjAtMzkxNDMxODkyNS0yOTYyMTY5NDYzLTI1MzA2MjI1MjItMC0wLTAtMC0x"
            },
            "owner": {
                "displayName": "[Agent Pools]\\Agent Pool Administrators",
                "url": "http://[redacted]/_apis/Identities/46bf9566-b291-4937-aa81-926a7f9aa97b",
                "id": "46bf9566-b291-4937-aa81-926a7f9aa97b",
                "uniqueName": "vstfs:///Framework/Generic/18968611-4fe9-4dc4-b08f-1e7796d63c3a\\Agent Pool Administrators",
                "imageUrl": "",
                "isContainer": true,
                "descriptor": "vssgp.Uy0xLTktMTU1MTM3NDI0NS0yOTQwMzI5MjAtMzkxNDMxODkyNS0yOTYyMTY5NDYzLTI1MzA2MjI1MjItMC0wLTAtMC0x"
            },
            "id": 1,
            "scope": "b84b5e94-e5d5-436f-92da-74af8a3f4cfc",
            "name": "Default",
            "isHosted": false,
            "poolType": "automation",
            "size": 8,
            "isLegacy": false
        },
        {
            "createdOn": "2016-08-05T12:23:28.52Z",
            "autoProvision": true,
            "autoSize": true,
            "targetSize": null,
            "agentCloudId": null,
            "createdBy": {
                "displayName": "[redacted]",
                "url": "http://[redacted]/_apis/Identities/c35ddc8d-8a5e-401e-9c41-2a7b85fbac8e",
                "id": "c35ddc8d-8a5e-401e-9c41-2a7b85fbac8e",
                "uniqueName": "[redacted]",
                "imageUrl": "",
                "descriptor": "win.Uy0xLTUtMjEtMzk1NzI0MjcwNi0yOTA5MDkxNTkzLTM1Njc4MzQyNS0yMTM4"
            },
            "owner": {
                "displayName": "[redacted]",
                "url": "http://[redacted]/_apis/Identities/c35ddc8d-8a5e-401e-9c41-2a7b85fbac8e",
                "id": "c35ddc8d-8a5e-401e-9c41-2a7b85fbac8e",
                "uniqueName": "[redacted]",
                "imageUrl": "",
                "descriptor": "win.Uy0xLTUtMjEtMzk1NzI0MjcwNi0yOTA5MDkxNTkzLTM1Njc4MzQyNS0yMTM4"
            },
            "id": 2,
            "scope": "b84b5e94-e5d5-436f-92da-74af8a3f4cfc",
            "name": "Release",
            "isHosted": false,
            "poolType": "automation",
            "size": 8,
            "isLegacy": false
        },
        {
            "createdOn": "2019-10-15T14:18:02.157Z",
            "autoProvision": true,
            "autoSize": true,
            "targetSize": null,
            "agentCloudId": null,
            "createdBy": {
                "displayName": "[redacted]",
                "url": "http://[redacted]/_apis/Identities/e3b1afbe-d67f-46a9-8647-9cad21c4ea34",
                "id": "e3b1afbe-d67f-46a9-8647-9cad21c4ea34",
                "uniqueName": "[redacted]",
                "imageUrl": "",
                "descriptor": "win.Uy0xLTUtMjEtMzk1NzI0MjcwNi0yOTA5MDkxNTkzLTM1Njc4MzQyNS0yMTg1Mg"
            },
            "owner": {
                "displayName": "[redacted]",
                "url": "http://[redacted]/_apis/Identities/e3b1afbe-d67f-46a9-8647-9cad21c4ea34",
                "id": "e3b1afbe-d67f-46a9-8647-9cad21c4ea34",
                "uniqueName": "[redacted]",
                "imageUrl": "",
                "descriptor": "win.Uy0xLTUtMjEtMzk1NzI0MjcwNi0yOTA5MDkxNTkzLTM1Njc4MzQyNS0yMTg1Mg"
            },
            "id": 13,
            "scope": "b84b5e94-e5d5-436f-92da-74af8a3f4cfc",
            "name": "Automation",
            "isHosted": false,
            "poolType": "automation",
            "size": 2,
            "isLegacy": false
        }
    ]
}
```

**Comment by jtpetty** [comment] 2020-01-15 15:53
Since we were unable to reproduce this issue and we do not see anything obviously wrong in the JSON output you provided, and you have worked around the problem, I am closing this issue for now. If the symptoms reoccur, please open a new ticket and we can attempt to root cause the issue.

**Closed by jtpetty** 2020-01-15 15:53 UTC
