### ISSUE TITLE
Mac agent appears to be caching build.id

### ISSUE THREAD

**Issue by avectoauto** [microsoft/azure-pipelines-agent#1865] opened 2018-10-03 09:35 UTC
## Have you tried trouble shooting?
[Trouble shooting doc](https://www.visualstudio.com/en-us/docs/build/troubleshooting)

## Agent Version and Platform
v2.140.0

OS of the machine running the agent? OSX/Windows/Linux/...
OSX

## VSTS Type and Version
VisualStudio.com

If VisualStudio.com, what is your account name? http://account.visualstudio.com

Avecto

## What's not working?
We currently have an issue on our Mac VSTS agent where the Build id is being retained from a previous build. On the vsts side the build id is incrementing however this is not the case on the agent.  If we restart the agent the id resets. 

We use build.number to set overall build number (i.e. 2.0.1.0), however we have some components in our application which follow a different build number structure (i.e 1.0.1.0), we are using the build.id to set the incremental build number. Our build number variable is build from a fixed version 2.0.(build.id), within vsts this is incrementing, however when we come to use the build.id on the agent for stamping some components this uses the first build.id on the agent

**Comment by TingluoHuang** [comment] 2018-10-03 13:43
@avectoauto can you share some log? like run `set` to print out the build_id variables.

**Comment by avectoauto** [comment] 2018-10-08 15:00
To update, this only appears to happen when building from XCode

**Comment by TingluoHuang** [comment] 2018-10-08 15:02
@avectoauto is your XCode project change any environment variable?
can you print out build.id before your xcode task?

**Comment by avectoauto** [comment] 2018-10-08 15:32
Output from TFS variable: 
2018-10-08T15:09:27.2850790Z BUILD_BUILDID=28857
2018-10-08T15:09:27.2888250Z BUILD_BUILDNUMBER=5.2.28857.0

Output from Xcode build:

export AVECTO_BUILD_BUILDNUMBER=5.2.28856.0

**Comment by TingluoHuang** [comment] 2018-10-11 14:13
@avectoauto what set `AVECTO_BUILD_BUILDNUMBER`?
the variable we set is `BUILD_BUILDNUMBER`

**Comment by avectoauto** [comment] 2018-10-11 14:58
AVECTO_BUILD_BUILDNUMBER is set by BUILD_BUILD.ID with a static value appended in front

As mentioned in the description "Our build number variable is build from a fixed version 2.0.(build.id)"

**Comment by TingluoHuang** [comment] 2018-10-11 15:12
is `AVECTO_BUILD_BUILDNUMBER` a variable in your build definition? or it's only set when during your xcode task?
i am trying to figure whether `AVECTO_BUILD_BUILDNUMBER` is a variable that VSTS set its value.

**Comment by avectoauto** [comment] 2018-10-18 14:52
It is in the build def and passed into the xcode build step, the issue seems similar to this
https://developercommunity.visualstudio.com/content/problem/303198/the-buildid-variable-does-not-get-replaced-anymore.html

**Comment by jtpetty** [comment] 2020-01-27 18:36
The referenced issue was closed as not a bug. I am closing this issue as well. If this issue is still occurring, please open a new issue.

**Closed by jtpetty** 2020-01-27 18:36 UTC
Labels: investigate
