### ISSUE TITLE
What ARM platforms / OSes are supported?

### ISSUE THREAD

**Issue by xpp12345** [microsoft/azure-pipelines-agent#3379] opened 2021-04-21 09:58 UTC
Hi, can anyone tell me what **arm** OS and platforms are supported and give a list?  

we tried  **vsts-agent-linux-arm64-2.184.2.tar.gz**  on **centos 1810 arm64** and installed all prerequisites as the guide.
finally we failed to start pipeagent as following error:
![NoDependency](https://user-images.githubusercontent.com/46448635/115535100-0754f080-a2cb-11eb-8278-a803d8650ee3.png)

Is it supported or what steps we are missing?
Thank you

**Comment by dexterlea** [comment] 2021-04-22 09:29
Hi, @andy-mishechkin
Thanks for your detailed info. I've followed instruction listed on this link to install prerequites https://github.com/dotnet/core/blob/main/Documentation/build-and-install-rhel6-prerequisites.md#making-the-libraries-available-for-a-net-core-application.
I successfully installed `vsts-agent-linux-arm64-2.170.1.tar.gz` on below system.
![image-20210422150934984](https://user-images.githubusercontent.com/35717851/115689930-2321ca80-a38f-11eb-8abc-b1aab098a38c.png)
However, error `./bin/System.Net.Http.Native.so: /lib64/libcurl.so.4: no version information available (required by ./bin/System.Net.Http.Native.so)` still exited. 
![image-20210422152044943](https://user-images.githubusercontent.com/35717851/115690235-6da34700-a38f-11eb-9d4e-240b18844d7a.png)
And I think this will cause incomplete 'CURL' communications between Azure DevOps Server and Agent.
I've googled a lot and still didn't get a solution. Can you please help? 

Thanks,
Best Regards.

**Comment by andy-mishechkin** [comment] 2021-04-22 12:59
Hello, @dexterlea
I see, your agent version 2.170.1. Now is the last version 2.185.1 (https://github.com/microsoft/azure-pipelines-agent/releases)
Would you please update your agent first ?
I have no this issue in CentOS 7 with agent 2.184.2 - all works fine.
![image](https://user-images.githubusercontent.com/57713077/115718295-0768f500-a38c-11eb-892a-7eb48d5d3b1d.png)
Thank you

**Comment by dexterlea** [comment] 2021-04-23 03:09
Hi @andy-mishechkin 
Below is my OS release info.
![image](https://user-images.githubusercontent.com/35717851/115812063-5ca41580-a423-11eb-955f-c74cafc95c83.png)
I've tried the newest agent release. However, `libcurl.so.4: no version information available` still exists.
![image](https://user-images.githubusercontent.com/35717851/115805660-f960b600-a417-11eb-8a9f-c9f5edea8c47.png)
I've followed instruction listed below,
![image](https://user-images.githubusercontent.com/35717851/115812609-3763d700-a424-11eb-9e06-9e6bc4ed4998.png)
![image](https://user-images.githubusercontent.com/35717851/115812613-3a5ec780-a424-11eb-9213-561aa34f494a.png)
![image](https://user-images.githubusercontent.com/35717851/115812620-3cc12180-a424-11eb-886b-7086843e5df9.png)
Thank you

**Comment by andy-mishechkin** [comment] 2021-04-23 11:44
Hello, @dexterlea 
Here is the similar situation (but related to Ubuntu): https://stackoverflow.com/questions/30017397/error-curl-usr-local-lib-libcurl-so-4-no-version-information-available-requ
May you try this approach for resolving the issue ?

Thank you!

**Comment by dexterlea** [comment] 2021-04-25 09:22
Hi @andy-mishechkin 

Thanks for your advice, I've tried this link before. It didn't work for me.
I've successfully installed agent on centos 7.6 aarch64 platform (with a lot of undocumented prerequisites done) and it works fine for now.
However, I just don't know what undicovered impacts would be caused by this `libcurl.so.4: no version information available` issue. 

Thanks anyway!

**Comment by andy-mishechkin** [comment] 2021-04-26 06:32
Sounds good.
I think we can close this ticket. If you face with any issues with your Azure DevOps agent - please feel free to reopen.

**Closed by andy-mishechkin** 2021-04-26 06:32 UTC
Labels: Area: Agent, question
