### ISSUE TITLE
Every pipeline run creates new workspace directory

### ISSUE THREAD

**Issue by bartwitkowski** [microsoft/azure-pipelines-agent#3210] opened 2021-01-15 08:38 UTC
## Agent Version and Platform
2.173.0

## OS of the machine running the agent?
Ubuntu 18.04

## Azure DevOps Type and Version
dev.azure.com

## What's not working?
We have a problem with filling up the disk space.
Among others, we have a pipeline that runs Terraform code. It has 2 stages: Terraform PLAN, and Terraform APPLY.
The problem is, that each run of the pipeline creates a new workspace directory with clone git repo (e.g /home/user/agent/_work/5; /home/user/agent/_work/6 etc), even if the code hasn't changed.
So, after first run we have two dirs:
/home/user/agent/_work/5
/home/user/agent/_work/6
And after second run (code is the same):
/home/user/agent/_work/7
/home/user/agent/_work/8
Etc.

**Why every run creates a new directory?**

### PS
To clean the space, we tried to use
```
workspace:
      clean: all
```
But the debug shows, that the directory to be deleted is the new one and not the previous one.
E.g last run was /home/user/agent/_work/8, new pipeline run tries to delete /home/user/agent/_work/9 (which doesn't exists) and then runs the normal job creating /home/user/agent/_work/9.

**Comment by max-zaytsev** [comment] 2021-03-15 15:21
Hi @bartwitkowski,
I wasn't able to reproduce the issue. Could you please run your pipeline again with _Enable system diagnostics_ checkbox enabled and provide logs from `/home/user/agent/_diag` folder?

**Comment by max-zaytsev** [comment] 2021-03-29 20:27
Hi @bartwitkowski, is the issue still relevant for you?

**Comment by henryqinshield** [comment] 2021-03-30 18:46
@max-zaytsev Hello! we are seeing this as well on our builds. Specifically it is happening on a single job where we pass in a dynamic parameter (this parameter changes with every run). Is this expected behavior?

**Comment by max-zaytsev** [comment] 2021-03-31 11:39
Hi @henryqinshield, could you please provide us with logs? If there is some sensitive information and you don't want to share it publicly, you can send it to me by email v-mazayt@microsoft.com.

**Comment by henryqinshield** [comment] 2021-03-31 19:19
@max-zaytsev I don't have any specific logs to the problem (as the agents have disappeared...however we have isolated the problem. It seems to lie in the dynamic parameter that we are passing in. As a function of our pipeline, we kick off a pipeline with templated yaml files. At times, we will need to pass in a git commit hash that is for the same repo but a different hash than "self". This causes our pipeline ui to list two repos. Of note, we only every check out a single repo per stage (its just that some stages checkout the branch (using the self string) and other are checking out at a specific commit (which may sometimes be the same as self)

The first repo is listed as our repo at the branch we are testing. The second repo listed is the exact same repo, but at the commit parameter we pass in. This is sometimes the same commit but in specific circumstances, they are different. When we stick to passing in "self" the two listed repos disappear. Please let me know if you have nay questions.

**Comment by pierreyvesv** [comment] 2021-04-15 13:55
Hello,
I have the same issue, for now I do a workspace cleaning after each run:
 ```
         - script: |
             cd $(Pipeline.Workspace)/..
            echo "cleaning directory"
            rm -rf [0-9]
 ```

**Comment by max-zaytsev** [comment] 2021-04-28 19:38
@pierreyvesv, @henryqinshield Closing the ticket since this is expected behavior. 
If there are any changes in the repository identifier or repositoryUrl, a new sources directory will be created.

**Closed by max-zaytsev** 2021-04-28 19:38 UTC
Labels: Area: ABTT, Area: Agent, bug
