### ISSUE TITLE
Environment agent seems to be stuck in a running state

### ISSUE THREAD

**Issue by strtdusty** [microsoft/azure-pipelines-agent#3579] opened 2021-10-25 18:34 UTC
## Agent Version and Platform
Version of your agent? 2.144.0/2.144.1/...
2.193.1

OS of the machine running the agent? OSX/Windows/Linux/...
Windows Server 2016 Datacenter

## Azure DevOps Type and Version
dev.azure.com

If dev.azure.com, what is your organization name? https://dev.azure.com/Itron
Itron

## What's not working?
Environment agents seem to be stuck in a running state.  However, the agent is not doing anything and appears to be done.  Subsequent jobs/deployments in the pipeline end up stuck in a queued state.  This happens on different agents, but seems to happen every time we run.
The environment shows that an agent is still running:
![image](https://user-images.githubusercontent.com/1013039/138743238-5be2ab29-5b9a-4da4-8e05-91965f6e4ace.png)
The pipeline thinks it is done but is waiting to start the next phase (queued)
![image](https://user-images.githubusercontent.com/1013039/138743592-57069152-fbc6-4411-8929-76285f6c6664.png)

## Agent and Worker's Diagnostic Logs
Logs are located in the agent's `_diag` folder. The agent logs are prefixed with `Agent_` and the worker logs are prefixed with `Worker_`. All sensitive information should already be masked out, but please double-check before pasting here
[Worker_20211025-163049-utc.log](https://github.com/microsoft/azure-pipelines-agent/files/7412734/Worker_20211025-163049-utc.log)
[Agent_20211022-231144-utc.log](https://github.com/microsoft/azure-pipelines-agent/files/7412735/Agent_20211022-231144-utc.log)
.

**Comment by tinylabspace** [comment] 2021-11-29 16:55
Take a look at this doc, I ran into something similar recently where a YAML job named "deploy" caused an environment job to hang in a pending state indefinitely. Your worker log has a number of steps with "deployment" in the name, _Processing step: DisplayName='Backup Directory before Deployment'_.

https://docs.microsoft.com/en-us/azure/devops/pipelines/process/deployment-jobs?view=azure-devops

At the top:

_Important

Job and stage names cannot contain keywords (example: deployment)._

**Comment by strtdusty** [comment] 2021-11-29 17:10
@tinylabspace I had seen that but the docs didn't mention that tasks (just jobs/stages) couldn't have a displayName with Deployment in them.  Also, though it is a bit ambiguous, I believe the docs are saying that the actual name of the job/stage can't have deployment, but the displayName is not mentioned.  We have managed to work around this issue by reducing the number of total steps in the stages.  A few of our templates are called repeatedly with control parameters indicating which parts of the template should be run.  We moved that logic from "conditions" to template syntax so the step isn't even compiled in if it is not used.  That has allowed us to proceed without any more hangups.  Support has indicated there are limits on the number of steps and that there are backlog items to resolve issues like ours, but they have not definitively correlated our issue to the backlog items.

**Comment by anatolybolshakov** [comment] 2022-05-16 17:19
Hi @strtdusty do you still see this issue with the latest agent version? There have been some fixes related to race conditions for job execution some time ago.

**Comment by strtdusty** [comment] 2022-05-16 18:13
@anatolybolshakov  I will upgrade and do some testing

**Comment by alexander-smolyakov** [comment] 2022-07-11 07:30
@strtdusty do you have any updates?

**Comment by strtdusty** [comment] 2022-07-11 12:04
We still see the same behavior with the deployment stuck running forever
after upgrading to the latest agent version.

**Comment by ismayilov-ismayil** [comment] 2022-11-16 21:43
Hi @strtdusty, sorry for late response. I am trying to reproduce your issue. Meanwhile do you have a chance to check same pipeline with Microsoft hosted agent

**Comment by strtdusty** [comment] 2022-11-17 03:01
Unfortunately, we need private vnet access so it cannot be a hosted agent.

**Comment by ismayilov-ismayil** [comment] 2022-11-17 15:22
@strtdusty could you share your pipeline yaml file? 
Please, remove passwords, tokens and any confidential data from files

**Comment by ceilingfish** [comment] 2022-11-25 16:15
Reproduced with the following pipeline:

```yaml
parameters:
  - name: environmentName
    displayName: Environment Name
    type: string

trigger: none
      
stages:
  - stage: Deploy
    displayName: Deploy to ${{ parameters.environmentName }}
    jobs:
      - deployment: Deploy
        environment:
          name: $(EnvironmentName)
          resourceName: host
          resourceType: VirtualMachine
          tags: windows
        strategy:
          runOnce:
            deploy:
              steps:
                - pwsh: Write-Host "hello"
```

hangs indefinitely. However the following executes just fine:

```yaml
parameters:
  - name: environmentName
    displayName: Environment Name
    type: string

trigger: none
      
stages:
  - stage: Install
    displayName: Install on ${{ parameters.environmentName }}
    jobs:
      - deployment: Install
        environment:
          name: $(EnvironmentName)
          resourceName: host
          resourceType: VirtualMachine
          tags: windows
        strategy:
          runOnce:
            deploy:
              steps:
                - pwsh: Write-Host "hello"
```

**Comment by tinylabspace** [comment] 2022-11-25 16:27
I'm still following this thread because I still have users that end up in this situation. The user experience would improve if the YAML validation simply failed when a user tries to save a pipeline that uses a reserved word for a stage name.

If that can't be done because users might be using an external editor to edit the pipeline it might be better if the pipeline run failed immediately. Possibly with a YAML parsing error, vs allowing it to start then hang on the Deploy stage with no meaningful feedback in the UI.

**Comment by ismayilov-ismayil** [comment] 2022-11-27 19:56
Hi @ceilingfish and @tinylabspace,  thanks for your feedback. 
I will check and revert back soon.

**Comment by ismayilov-ismayil** [comment] 2022-12-14 22:33
Hi @strtdusty, @tinylabspace and @ceilingfish
I was able to reproduce issue and it seems the root cause is to use reserved keywords such as "deploy, deployment". 
`   - deployment: Deploy `  - We shouldn't use "Deploy" as the name of deployment jobs.

I close this issue and open new one regarding to improve YAML parsing stage to notify user with relevant message.
Feel free to ask any other questions or let us know if it's still relevant for you.

**Comment by strtdusty** [comment] 2022-12-14 23:28
Thanks.  I'm OK closing it but we did take steps to remove "Deploy" from any jobs.  We opened a support ticket and they attributed the problem to a maximum number of jobs per stage being exceeded.  [The limit is 256](https://learn.microsoft.com/en-us/azure/devops/pipelines/process/stages?view=azure-devops&tabs=yaml).  This is aggravated by the number of environments you have.  If you had 20 environments, 1 stage and 20 jobs you would exceed this limit and see the hanging issue we experienced.

**Closed** 2022-12-15 22:55 UTC
Labels: bug, Area: Agent

**Comment by uryszawa** [comment] 2023-01-19 14:10
> @tinylabspace I had seen that but the docs didn't mention that tasks (just jobs/stages) couldn't have a displayName with Deployment in them. Also, though it is a bit ambiguous, I believe the docs are saying that the actual name of the job/stage can't have deployment, but the displayName is not mentioned. We have managed to work around this issue by reducing the number of total steps in the stages. A few of our templates are called repeatedly with control parameters indicating which parts of the template should be run. We moved that logic from "conditions" to template syntax so the step isn't even compiled in if it is not used. That has allowed us to proceed without any more hangups. Support has indicated there are limits on the number of steps and that there are backlog items to resolve issues like ours, but they have not definitively correlated our issue to the backlog items.

I faced both of the issues mentioned here in my pipelines. Thanks to this comment I was able to workaround. Is it going to be fixed?

**Comment by anish-george88** [comment] 2024-07-30 02:25
I am using self-hosted agent in Linux machine. Facing this issue even for normal jobs, mainly when multiple stages are running in parallel.

Linux x64 Ubuntu 20
Parallel jobs - 13
Number of agents - 10 (2 build machines, 5 agents each)
Agent version: 3.242.1 (latest)

Any suggestions?
