### ISSUE TITLE
SourceFolder changes after second checkout

### ISSUE THREAD

**Issue by juergenB234** [microsoft/azure-pipelines-agent#3638] opened 2021-12-01 09:05 UTC
My Yaml steps at the beginning of the build pipeline:
  
- checkout: self
    clean: true
    path: s
  - checkout: Configs
    clean: true
    path: s/Configs
  - task: CopyFiles@2
  ...

##[debug]Repository requires to be placed at 'H:\Agent\_work\13\s', current location is 'H:\Agent\_work\13\s'
##[debug]Repository requires to be placed at 'H:\Agent\_work\13\s\Configs', current location is 'H:\Agent\_work\13\s\Configs'

Debug trace of copyFiles  $(Build.SourcesDirectory)
##[debug]SourceFolder=H:\Agent\_work\14\s

Tested with v2.195.0, v2.195.1, v2.196.0.
Agent is installed on premise on Windows Server 2012 R2 and connected with Azure DevOps Server.

With vsts-agent-win-x64-2.190.0 the variable $(Build.SourcesDirectory) is the corrected directory. 
##[debug]SourceFolder=H:\Agent\_work\13\s

**Comment by EzzhevNikita** [comment] 2021-12-03 12:09
Hey @juergenB234, I've looked at your issue. I didn't see any unexpected behavior while trying to reproduce your issue (I have checked all the agent versions that you mentioned in the ticket). What I see from provided logs is that the workspace part of the source directory changed in your case. This could happen in several situations,  workspace is changing when an organization, pipeline (defenitionId), or/and set of used repositories in the pipeline was changed. Could you, please check that no mentioned options changed between two runs where you see this problem.
Could you please provide a full agent and worker logs they are located in _diag folder?

**Comment by juergenB234** [comment] 2021-12-06 07:15
We implemented a workaround and I have to switch back to the old version to get the logs. Will take a while until I get that right. Probably on Wednesday.

**Comment by juergenB234** [comment] 2021-12-08 11:59
I attached the logs from buildagent (servername and accounts are removed). This build process uses 3 checkout. In the first task after checkouts the sourcefolder changed. With agent 2.190.0 the process runs fine. 
[Worker_20211208-113545-utc.log](https://github.com/microsoft/azure-pipelines-agent/files/7675822/Worker_20211208-113545-utc.log)
[1_BuildJob (1).txt](https://github.com/microsoft/azure-pipelines-agent/files/7675823/1_BuildJob.1.txt)
[1_BuildJob.txt](https://github.com/microsoft/azure-pipelines-agent/files/7675824/1_BuildJob.txt)
[Agent_20211208-113541-utc.log](https://github.com/microsoft/azure-pipelines-agent/files/7675825/Agent_20211208-113541-utc.log)

**Comment by danibyay** [comment] 2021-12-17 18:24
@juergenB234 could you share your workaround ? do you mean you switched to an older version of the agent? if you could tell us it would be very helpful, thank you

**Comment by golubev-ivan** [comment] 2021-12-23 09:00
Hi @juergenB234, fix for this issue is awaiting deployment, but due to deployment freeze the version of the agent with these changes will start the official release process after 10 Jan.

**Comment by golubev-ivan** [comment] 2022-01-14 12:17
Hey @juergenB234, the fix for this issue in the latest version of agent 2.196.2. I'm closing this issue, feel free to ping me if problem persists, or you still need any help.

**Closed by golubev-ivan** 2022-01-14 12:17 UTC
Labels: bug, awaiting deployment, Area: Agent
