### ISSUE TITLE
Failed to download and extract TEE

### ISSUE THREAD

**Issue by manishlak** [microsoft/azure-pipelines-agent#3761] opened 2022-02-22 08:03 UTC
Hi,
using agent (2.198.3), build is failed with below error
build is configured with TFVC on macOS

##[debug]TEE download progress: 100%.
##[debug]Downloaded /Volumes/Data/TEST/A4/_temp/tee_temp_dir/b0868a40-bc36-49e9-a847-0c24a3c234f5.zip
##[debug]Extracted /Volumes/Data/TEST/A4/_temp/tee_temp_dir/b0868a40-bc36-49e9-a847-0c24a3c234f5.zip to $/Volumes/Data/TEST/A4/_temp/tee_temp_dir/5c05f529-c274-4331-89cc-2bbe7d0cf51d
##[debug]Failed to download and extract TEE. Error: System.IO.IOException: **Cross-device link**
at System.IO.FileSystem.MoveDirectory(String sourceFullPath, String destFullPath)
at System.IO.Directory.Move(String sourceDirName, String destDirName)
at Microsoft.VisualStudio.Services.Agent.Util.TeeUtil.DownloadAndExtractTee()
at Microsoft.VisualStudio.Services.Agent.Util.TeeUtil.DownloadTeeIfAbsent()
##[debug]Cleaned up /Users/TEST/Agents/A4/externals/tee and /Volumes/Data/TEST/A4/_temp/tee_temp_dir
##[debug]Trying to download and extract TEE. Attempt: 3
.
.
##[debug]TEE download progress: 100%.
##[debug]Downloaded /Volumes/Data/TEST/A4/_temp/tee_temp_dir/be17d6a7-18b6-41d6-b68b-321691e95281.zip
##[debug]Extracted /Volumes/Data/TEST/A4/_temp/tee_temp_dir/be17d6a7-18b6-41d6-b68b-321691e95281.zip to $/Volumes/Data/TEST/A4/_temp/tee_temp_dir/e33a2978-238b-46a6-a7f1-860c3d1edcfc
**##[error]Cross-device link**
##[debug]Processed: ##vso[task.logissue type=error;]**Cross-device link**
##[debug]Processed: ##vso[task.complete result=Failed;]
##[debug]   at System.IO.FileSystem.MoveDirectory(String sourceFullPath, String destFullPath)
   at System.IO.Directory.Move(String sourceDirName, String destDirName)
   at Microsoft.VisualStudio.Services.Agent.Util.TeeUtil.DownloadAndExtractTee()
   at Microsoft.VisualStudio.Services.Agent.Util.TeeUtil.DownloadTeeIfAbsent()
   at Agent.Plugins.Repository.CheckoutTask.RunAsync(AgentTaskPluginExecutionContext executionContext, CancellationToken token)
   at Agent.PluginHost.Program.Main(String[] args)

**Comment by DaniilShmelev** [comment] 2022-02-22 08:31
Hi @manishlak! Thanks for submitting this issue, I was able to reproduce it. Looks like a known issue in dotnet: https://github.com/dotnet/runtime/issues/31149.
We're currently working on a fix.

**Comment by DaniilShmelev** [comment] 2022-02-22 08:40
As a workaround, you could set the agent's working directory to be on the same drive as the agent itself.

**Comment by DaniilShmelev** [comment] 2022-03-04 06:37
We've merged a fix for this issue and are going to release it in the next few weeks.

**Closed by DaniilShmelev** 2022-03-04 06:37 UTC
Labels: bug, Area: Agent
